// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package sort

import (
	"context"
	"eigenflux_server/kitex_gen/eigenflux/base"
	"fmt"
)

type SortItemsReq struct {
	AgentId       int64  `thrift:"agent_id,1,required" frugal:"1,required,i64" json:"agent_id"`
	LastUpdatedAt *int64 `thrift:"last_updated_at,2,optional" frugal:"2,optional,i64" json:"last_updated_at,omitempty"`
	Limit         *int32 `thrift:"limit,3,optional" frugal:"3,optional,i32" json:"limit,omitempty"`
}

func NewSortItemsReq() *SortItemsReq {
	return &SortItemsReq{}
}

func (p *SortItemsReq) InitDefault() {
}

func (p *SortItemsReq) GetAgentId() (v int64) {
	return p.AgentId
}

var SortItemsReq_LastUpdatedAt_DEFAULT int64

func (p *SortItemsReq) GetLastUpdatedAt() (v int64) {
	if !p.IsSetLastUpdatedAt() {
		return SortItemsReq_LastUpdatedAt_DEFAULT
	}
	return *p.LastUpdatedAt
}

var SortItemsReq_Limit_DEFAULT int32

func (p *SortItemsReq) GetLimit() (v int32) {
	if !p.IsSetLimit() {
		return SortItemsReq_Limit_DEFAULT
	}
	return *p.Limit
}
func (p *SortItemsReq) SetAgentId(val int64) {
	p.AgentId = val
}
func (p *SortItemsReq) SetLastUpdatedAt(val *int64) {
	p.LastUpdatedAt = val
}
func (p *SortItemsReq) SetLimit(val *int32) {
	p.Limit = val
}

func (p *SortItemsReq) IsSetLastUpdatedAt() bool {
	return p.LastUpdatedAt != nil
}

func (p *SortItemsReq) IsSetLimit() bool {
	return p.Limit != nil
}

func (p *SortItemsReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SortItemsReq(%+v)", *p)
}

var fieldIDToName_SortItemsReq = map[int16]string{
	1: "agent_id",
	2: "last_updated_at",
	3: "limit",
}

type SortedItem struct {
	ItemId        int64   `thrift:"item_id,1,required" frugal:"1,required,i64" json:"item_id"`
	Score         float64 `thrift:"score,2,required" frugal:"2,required,double" json:"score"`
	AgentFeatures *string `thrift:"agent_features,3,optional" frugal:"3,optional,string" json:"agent_features,omitempty"`
	ItemFeatures  *string `thrift:"item_features,4,optional" frugal:"4,optional,string" json:"item_features,omitempty"`
}

func NewSortedItem() *SortedItem {
	return &SortedItem{}
}

func (p *SortedItem) InitDefault() {
}

func (p *SortedItem) GetItemId() (v int64) {
	return p.ItemId
}

func (p *SortedItem) GetScore() (v float64) {
	return p.Score
}

var SortedItem_AgentFeatures_DEFAULT string

func (p *SortedItem) GetAgentFeatures() (v string) {
	if !p.IsSetAgentFeatures() {
		return SortedItem_AgentFeatures_DEFAULT
	}
	return *p.AgentFeatures
}

var SortedItem_ItemFeatures_DEFAULT string

func (p *SortedItem) GetItemFeatures() (v string) {
	if !p.IsSetItemFeatures() {
		return SortedItem_ItemFeatures_DEFAULT
	}
	return *p.ItemFeatures
}
func (p *SortedItem) SetItemId(val int64) {
	p.ItemId = val
}
func (p *SortedItem) SetScore(val float64) {
	p.Score = val
}
func (p *SortedItem) SetAgentFeatures(val *string) {
	p.AgentFeatures = val
}
func (p *SortedItem) SetItemFeatures(val *string) {
	p.ItemFeatures = val
}

func (p *SortedItem) IsSetAgentFeatures() bool {
	return p.AgentFeatures != nil
}

func (p *SortedItem) IsSetItemFeatures() bool {
	return p.ItemFeatures != nil
}

func (p *SortedItem) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SortedItem(%+v)", *p)
}

var fieldIDToName_SortedItem = map[int16]string{
	1: "item_id",
	2: "score",
	3: "agent_features",
	4: "item_features",
}

type SortItemsResp struct {
	ItemIds     []int64        `thrift:"item_ids,1,required" frugal:"1,required,list<i64>" json:"item_ids"`
	NextCursor  int64          `thrift:"next_cursor,2,required" frugal:"2,required,i64" json:"next_cursor"`
	SortedItems []*SortedItem  `thrift:"sorted_items,3,optional" frugal:"3,optional,list<SortedItem>" json:"sorted_items,omitempty"`
	BaseResp    *base.BaseResp `thrift:"base_resp,255,required" frugal:"255,required,base.BaseResp" json:"base_resp"`
}

func NewSortItemsResp() *SortItemsResp {
	return &SortItemsResp{}
}

func (p *SortItemsResp) InitDefault() {
}

func (p *SortItemsResp) GetItemIds() (v []int64) {
	return p.ItemIds
}

func (p *SortItemsResp) GetNextCursor() (v int64) {
	return p.NextCursor
}

var SortItemsResp_SortedItems_DEFAULT []*SortedItem

func (p *SortItemsResp) GetSortedItems() (v []*SortedItem) {
	if !p.IsSetSortedItems() {
		return SortItemsResp_SortedItems_DEFAULT
	}
	return p.SortedItems
}

var SortItemsResp_BaseResp_DEFAULT *base.BaseResp

func (p *SortItemsResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return SortItemsResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *SortItemsResp) SetItemIds(val []int64) {
	p.ItemIds = val
}
func (p *SortItemsResp) SetNextCursor(val int64) {
	p.NextCursor = val
}
func (p *SortItemsResp) SetSortedItems(val []*SortedItem) {
	p.SortedItems = val
}
func (p *SortItemsResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *SortItemsResp) IsSetSortedItems() bool {
	return p.SortedItems != nil
}

func (p *SortItemsResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *SortItemsResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SortItemsResp(%+v)", *p)
}

var fieldIDToName_SortItemsResp = map[int16]string{
	1:   "item_ids",
	2:   "next_cursor",
	3:   "sorted_items",
	255: "base_resp",
}

type SortService interface {
	SortItems(ctx context.Context, req *SortItemsReq) (r *SortItemsResp, err error)
}

type SortServiceSortItemsArgs struct {
	Req *SortItemsReq `thrift:"req,1" frugal:"1,default,SortItemsReq" json:"req"`
}

func NewSortServiceSortItemsArgs() *SortServiceSortItemsArgs {
	return &SortServiceSortItemsArgs{}
}

func (p *SortServiceSortItemsArgs) InitDefault() {
}

var SortServiceSortItemsArgs_Req_DEFAULT *SortItemsReq

func (p *SortServiceSortItemsArgs) GetReq() (v *SortItemsReq) {
	if !p.IsSetReq() {
		return SortServiceSortItemsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *SortServiceSortItemsArgs) SetReq(val *SortItemsReq) {
	p.Req = val
}

func (p *SortServiceSortItemsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *SortServiceSortItemsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SortServiceSortItemsArgs(%+v)", *p)
}

var fieldIDToName_SortServiceSortItemsArgs = map[int16]string{
	1: "req",
}

type SortServiceSortItemsResult struct {
	Success *SortItemsResp `thrift:"success,0,optional" frugal:"0,optional,SortItemsResp" json:"success,omitempty"`
}

func NewSortServiceSortItemsResult() *SortServiceSortItemsResult {
	return &SortServiceSortItemsResult{}
}

func (p *SortServiceSortItemsResult) InitDefault() {
}

var SortServiceSortItemsResult_Success_DEFAULT *SortItemsResp

func (p *SortServiceSortItemsResult) GetSuccess() (v *SortItemsResp) {
	if !p.IsSetSuccess() {
		return SortServiceSortItemsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *SortServiceSortItemsResult) SetSuccess(x interface{}) {
	p.Success = x.(*SortItemsResp)
}

func (p *SortServiceSortItemsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *SortServiceSortItemsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SortServiceSortItemsResult(%+v)", *p)
}

var fieldIDToName_SortServiceSortItemsResult = map[int16]string{
	0: "success",
}
