// Code generated by Kitex v0.16.1. DO NOT EDIT.

package authservice

import (
	"context"
	auth "eigenflux_server/kitex_gen/eigenflux/auth"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	StartLogin(ctx context.Context, req *auth.StartLoginReq, callOptions ...callopt.Option) (r *auth.StartLoginResp, err error)
	VerifyLogin(ctx context.Context, req *auth.VerifyLoginReq, callOptions ...callopt.Option) (r *auth.VerifyLoginResp, err error)
	ValidateSession(ctx context.Context, req *auth.ValidateSessionReq, callOptions ...callopt.Option) (r *auth.ValidateSessionResp, err error)
	Logout(ctx context.Context, req *auth.LogoutReq, callOptions ...callopt.Option) (r *auth.LogoutResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kAuthServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kAuthServiceClient struct {
	*kClient
}

func (p *kAuthServiceClient) StartLogin(ctx context.Context, req *auth.StartLoginReq, callOptions ...callopt.Option) (r *auth.StartLoginResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.StartLogin(ctx, req)
}

func (p *kAuthServiceClient) VerifyLogin(ctx context.Context, req *auth.VerifyLoginReq, callOptions ...callopt.Option) (r *auth.VerifyLoginResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.VerifyLogin(ctx, req)
}

func (p *kAuthServiceClient) ValidateSession(ctx context.Context, req *auth.ValidateSessionReq, callOptions ...callopt.Option) (r *auth.ValidateSessionResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ValidateSession(ctx, req)
}

func (p *kAuthServiceClient) Logout(ctx context.Context, req *auth.LogoutReq, callOptions ...callopt.Option) (r *auth.LogoutResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Logout(ctx, req)
}
