// Code generated by Kitex v0.14.1. DO NOT EDIT.

package notificationservice

import (
	"context"
	notification "eigenflux_server/kitex_gen/eigenflux/notification"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"ListPending": kitex.NewMethodInfo(
		listPendingHandler,
		newNotificationServiceListPendingArgs,
		newNotificationServiceListPendingResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"AckNotifications": kitex.NewMethodInfo(
		ackNotificationsHandler,
		newNotificationServiceAckNotificationsArgs,
		newNotificationServiceAckNotificationsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	notificationServiceServiceInfo                = NewServiceInfo()
	notificationServiceServiceInfoForClient       = NewServiceInfoForClient()
	notificationServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return notificationServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return notificationServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return notificationServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "NotificationService"
	handlerType := (*notification.NotificationService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "notification",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.14.1",
		Extra:           extra,
	}
	return svcInfo
}

func listPendingHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*notification.NotificationServiceListPendingArgs)
	realResult := result.(*notification.NotificationServiceListPendingResult)
	success, err := handler.(notification.NotificationService).ListPending(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newNotificationServiceListPendingArgs() interface{} {
	return notification.NewNotificationServiceListPendingArgs()
}

func newNotificationServiceListPendingResult() interface{} {
	return notification.NewNotificationServiceListPendingResult()
}

func ackNotificationsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*notification.NotificationServiceAckNotificationsArgs)
	realResult := result.(*notification.NotificationServiceAckNotificationsResult)
	success, err := handler.(notification.NotificationService).AckNotifications(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newNotificationServiceAckNotificationsArgs() interface{} {
	return notification.NewNotificationServiceAckNotificationsArgs()
}

func newNotificationServiceAckNotificationsResult() interface{} {
	return notification.NewNotificationServiceAckNotificationsResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) ListPending(ctx context.Context, req *notification.ListPendingReq) (r *notification.ListPendingResp, err error) {
	var _args notification.NotificationServiceListPendingArgs
	_args.Req = req
	var _result notification.NotificationServiceListPendingResult
	if err = p.c.Call(ctx, "ListPending", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) AckNotifications(ctx context.Context, req *notification.AckNotificationsReq) (r *notification.AckNotificationsResp, err error) {
	var _args notification.NotificationServiceAckNotificationsArgs
	_args.Req = req
	var _result notification.NotificationServiceAckNotificationsResult
	if err = p.c.Call(ctx, "AckNotifications", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
