// Code generated by Kitex v0.14.1. DO NOT EDIT.

package profileservice

import (
	"context"
	profile "eigenflux_server/kitex_gen/eigenflux/profile"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	RegisterAgent(ctx context.Context, req *profile.RegisterAgentReq, callOptions ...callopt.Option) (r *profile.RegisterAgentResp, err error)
	UpdateProfile(ctx context.Context, req *profile.UpdateProfileReq, callOptions ...callopt.Option) (r *profile.UpdateProfileResp, err error)
	GetAgent(ctx context.Context, req *profile.GetAgentReq, callOptions ...callopt.Option) (r *profile.GetAgentResp, err error)
	MatchAgentsByKeywords(ctx context.Context, req *profile.MatchAgentsByKeywordsReq, callOptions ...callopt.Option) (r *profile.MatchAgentsByKeywordsResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kProfileServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kProfileServiceClient struct {
	*kClient
}

func (p *kProfileServiceClient) RegisterAgent(ctx context.Context, req *profile.RegisterAgentReq, callOptions ...callopt.Option) (r *profile.RegisterAgentResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RegisterAgent(ctx, req)
}

func (p *kProfileServiceClient) UpdateProfile(ctx context.Context, req *profile.UpdateProfileReq, callOptions ...callopt.Option) (r *profile.UpdateProfileResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateProfile(ctx, req)
}

func (p *kProfileServiceClient) GetAgent(ctx context.Context, req *profile.GetAgentReq, callOptions ...callopt.Option) (r *profile.GetAgentResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetAgent(ctx, req)
}

func (p *kProfileServiceClient) MatchAgentsByKeywords(ctx context.Context, req *profile.MatchAgentsByKeywordsReq, callOptions ...callopt.Option) (r *profile.MatchAgentsByKeywordsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.MatchAgentsByKeywords(ctx, req)
}
