// Code generated by thriftgo (0.4.2). DO NOT EDIT.

package notification

import (
	"context"
	"eigenflux_server/kitex_gen/eigenflux/base"
	"fmt"
)

type PendingNotification struct {
	NotificationId  int64   `thrift:"notification_id,1,required" frugal:"1,required,i64" json:"notification_id"`
	SourceType      string  `thrift:"source_type,2,required" frugal:"2,required,string" json:"source_type"`
	Type            string  `thrift:"type,3,required" frugal:"3,required,string" json:"type"`
	Content         string  `thrift:"content,4,required" frugal:"4,required,string" json:"content"`
	CreatedAt       int64   `thrift:"created_at,5,required" frugal:"5,required,i64" json:"created_at"`
	PeerShortId     *string `thrift:"peer_short_id,6,optional" frugal:"6,optional,string" json:"peer_short_id,omitempty"`
	PeerDisplayName *string `thrift:"peer_display_name,7,optional" frugal:"7,optional,string" json:"peer_display_name,omitempty"`
	FriendUid       *int64  `thrift:"friend_uid,8,optional" frugal:"8,optional,i64" json:"friend_uid,omitempty"`
}

func NewPendingNotification() *PendingNotification {
	return &PendingNotification{}
}

func (p *PendingNotification) InitDefault() {
}

func (p *PendingNotification) GetNotificationId() (v int64) {
	return p.NotificationId
}

func (p *PendingNotification) GetSourceType() (v string) {
	return p.SourceType
}

func (p *PendingNotification) GetType() (v string) {
	return p.Type
}

func (p *PendingNotification) GetContent() (v string) {
	return p.Content
}

func (p *PendingNotification) GetCreatedAt() (v int64) {
	return p.CreatedAt
}

var PendingNotification_PeerShortId_DEFAULT string

func (p *PendingNotification) GetPeerShortId() (v string) {
	if !p.IsSetPeerShortId() {
		return PendingNotification_PeerShortId_DEFAULT
	}
	return *p.PeerShortId
}

var PendingNotification_PeerDisplayName_DEFAULT string

func (p *PendingNotification) GetPeerDisplayName() (v string) {
	if !p.IsSetPeerDisplayName() {
		return PendingNotification_PeerDisplayName_DEFAULT
	}
	return *p.PeerDisplayName
}

var PendingNotification_FriendUid_DEFAULT int64

func (p *PendingNotification) GetFriendUid() (v int64) {
	if !p.IsSetFriendUid() {
		return PendingNotification_FriendUid_DEFAULT
	}
	return *p.FriendUid
}
func (p *PendingNotification) SetNotificationId(val int64) {
	p.NotificationId = val
}
func (p *PendingNotification) SetSourceType(val string) {
	p.SourceType = val
}
func (p *PendingNotification) SetType(val string) {
	p.Type = val
}
func (p *PendingNotification) SetContent(val string) {
	p.Content = val
}
func (p *PendingNotification) SetCreatedAt(val int64) {
	p.CreatedAt = val
}
func (p *PendingNotification) SetPeerShortId(val *string) {
	p.PeerShortId = val
}
func (p *PendingNotification) SetPeerDisplayName(val *string) {
	p.PeerDisplayName = val
}
func (p *PendingNotification) SetFriendUid(val *int64) {
	p.FriendUid = val
}

func (p *PendingNotification) IsSetPeerShortId() bool {
	return p.PeerShortId != nil
}

func (p *PendingNotification) IsSetPeerDisplayName() bool {
	return p.PeerDisplayName != nil
}

func (p *PendingNotification) IsSetFriendUid() bool {
	return p.FriendUid != nil
}

func (p *PendingNotification) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PendingNotification(%+v)", *p)
}

var fieldIDToName_PendingNotification = map[int16]string{
	1: "notification_id",
	2: "source_type",
	3: "type",
	4: "content",
	5: "created_at",
	6: "peer_short_id",
	7: "peer_display_name",
	8: "friend_uid",
}

type AckNotificationItem struct {
	NotificationId int64  `thrift:"notification_id,1,required" frugal:"1,required,i64" json:"notification_id"`
	SourceType     string `thrift:"source_type,2,required" frugal:"2,required,string" json:"source_type"`
}

func NewAckNotificationItem() *AckNotificationItem {
	return &AckNotificationItem{}
}

func (p *AckNotificationItem) InitDefault() {
}

func (p *AckNotificationItem) GetNotificationId() (v int64) {
	return p.NotificationId
}

func (p *AckNotificationItem) GetSourceType() (v string) {
	return p.SourceType
}
func (p *AckNotificationItem) SetNotificationId(val int64) {
	p.NotificationId = val
}
func (p *AckNotificationItem) SetSourceType(val string) {
	p.SourceType = val
}

func (p *AckNotificationItem) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AckNotificationItem(%+v)", *p)
}

var fieldIDToName_AckNotificationItem = map[int16]string{
	1: "notification_id",
	2: "source_type",
}

type ListPendingReq struct {
	AgentId int64 `thrift:"agent_id,1,required" frugal:"1,required,i64" json:"agent_id"`
}

func NewListPendingReq() *ListPendingReq {
	return &ListPendingReq{}
}

func (p *ListPendingReq) InitDefault() {
}

func (p *ListPendingReq) GetAgentId() (v int64) {
	return p.AgentId
}
func (p *ListPendingReq) SetAgentId(val int64) {
	p.AgentId = val
}

func (p *ListPendingReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListPendingReq(%+v)", *p)
}

var fieldIDToName_ListPendingReq = map[int16]string{
	1: "agent_id",
}

type ListPendingResp struct {
	Notifications []*PendingNotification `thrift:"notifications,1,required" frugal:"1,required,list<PendingNotification>" json:"notifications"`
	BaseResp      *base.BaseResp         `thrift:"base_resp,255,required" frugal:"255,required,base.BaseResp" json:"base_resp"`
}

func NewListPendingResp() *ListPendingResp {
	return &ListPendingResp{}
}

func (p *ListPendingResp) InitDefault() {
}

func (p *ListPendingResp) GetNotifications() (v []*PendingNotification) {
	return p.Notifications
}

var ListPendingResp_BaseResp_DEFAULT *base.BaseResp

func (p *ListPendingResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return ListPendingResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *ListPendingResp) SetNotifications(val []*PendingNotification) {
	p.Notifications = val
}
func (p *ListPendingResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *ListPendingResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *ListPendingResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListPendingResp(%+v)", *p)
}

var fieldIDToName_ListPendingResp = map[int16]string{
	1:   "notifications",
	255: "base_resp",
}

type AckNotificationsReq struct {
	AgentId int64                  `thrift:"agent_id,1,required" frugal:"1,required,i64" json:"agent_id"`
	Items   []*AckNotificationItem `thrift:"items,2,required" frugal:"2,required,list<AckNotificationItem>" json:"items"`
}

func NewAckNotificationsReq() *AckNotificationsReq {
	return &AckNotificationsReq{}
}

func (p *AckNotificationsReq) InitDefault() {
}

func (p *AckNotificationsReq) GetAgentId() (v int64) {
	return p.AgentId
}

func (p *AckNotificationsReq) GetItems() (v []*AckNotificationItem) {
	return p.Items
}
func (p *AckNotificationsReq) SetAgentId(val int64) {
	p.AgentId = val
}
func (p *AckNotificationsReq) SetItems(val []*AckNotificationItem) {
	p.Items = val
}

func (p *AckNotificationsReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AckNotificationsReq(%+v)", *p)
}

var fieldIDToName_AckNotificationsReq = map[int16]string{
	1: "agent_id",
	2: "items",
}

type AckNotificationsResp struct {
	BaseResp *base.BaseResp `thrift:"base_resp,255,required" frugal:"255,required,base.BaseResp" json:"base_resp"`
}

func NewAckNotificationsResp() *AckNotificationsResp {
	return &AckNotificationsResp{}
}

func (p *AckNotificationsResp) InitDefault() {
}

var AckNotificationsResp_BaseResp_DEFAULT *base.BaseResp

func (p *AckNotificationsResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return AckNotificationsResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *AckNotificationsResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *AckNotificationsResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *AckNotificationsResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AckNotificationsResp(%+v)", *p)
}

var fieldIDToName_AckNotificationsResp = map[int16]string{
	255: "base_resp",
}

type NotificationService interface {
	ListPending(ctx context.Context, req *ListPendingReq) (r *ListPendingResp, err error)

	AckNotifications(ctx context.Context, req *AckNotificationsReq) (r *AckNotificationsResp, err error)
}

type NotificationServiceListPendingArgs struct {
	Req *ListPendingReq `thrift:"req,1" frugal:"1,default,ListPendingReq" json:"req"`
}

func NewNotificationServiceListPendingArgs() *NotificationServiceListPendingArgs {
	return &NotificationServiceListPendingArgs{}
}

func (p *NotificationServiceListPendingArgs) InitDefault() {
}

var NotificationServiceListPendingArgs_Req_DEFAULT *ListPendingReq

func (p *NotificationServiceListPendingArgs) GetReq() (v *ListPendingReq) {
	if !p.IsSetReq() {
		return NotificationServiceListPendingArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *NotificationServiceListPendingArgs) SetReq(val *ListPendingReq) {
	p.Req = val
}

func (p *NotificationServiceListPendingArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *NotificationServiceListPendingArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("NotificationServiceListPendingArgs(%+v)", *p)
}

var fieldIDToName_NotificationServiceListPendingArgs = map[int16]string{
	1: "req",
}

type NotificationServiceListPendingResult struct {
	Success *ListPendingResp `thrift:"success,0,optional" frugal:"0,optional,ListPendingResp" json:"success,omitempty"`
}

func NewNotificationServiceListPendingResult() *NotificationServiceListPendingResult {
	return &NotificationServiceListPendingResult{}
}

func (p *NotificationServiceListPendingResult) InitDefault() {
}

var NotificationServiceListPendingResult_Success_DEFAULT *ListPendingResp

func (p *NotificationServiceListPendingResult) GetSuccess() (v *ListPendingResp) {
	if !p.IsSetSuccess() {
		return NotificationServiceListPendingResult_Success_DEFAULT
	}
	return p.Success
}
func (p *NotificationServiceListPendingResult) SetSuccess(x interface{}) {
	p.Success = x.(*ListPendingResp)
}

func (p *NotificationServiceListPendingResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *NotificationServiceListPendingResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("NotificationServiceListPendingResult(%+v)", *p)
}

var fieldIDToName_NotificationServiceListPendingResult = map[int16]string{
	0: "success",
}

type NotificationServiceAckNotificationsArgs struct {
	Req *AckNotificationsReq `thrift:"req,1" frugal:"1,default,AckNotificationsReq" json:"req"`
}

func NewNotificationServiceAckNotificationsArgs() *NotificationServiceAckNotificationsArgs {
	return &NotificationServiceAckNotificationsArgs{}
}

func (p *NotificationServiceAckNotificationsArgs) InitDefault() {
}

var NotificationServiceAckNotificationsArgs_Req_DEFAULT *AckNotificationsReq

func (p *NotificationServiceAckNotificationsArgs) GetReq() (v *AckNotificationsReq) {
	if !p.IsSetReq() {
		return NotificationServiceAckNotificationsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *NotificationServiceAckNotificationsArgs) SetReq(val *AckNotificationsReq) {
	p.Req = val
}

func (p *NotificationServiceAckNotificationsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *NotificationServiceAckNotificationsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("NotificationServiceAckNotificationsArgs(%+v)", *p)
}

var fieldIDToName_NotificationServiceAckNotificationsArgs = map[int16]string{
	1: "req",
}

type NotificationServiceAckNotificationsResult struct {
	Success *AckNotificationsResp `thrift:"success,0,optional" frugal:"0,optional,AckNotificationsResp" json:"success,omitempty"`
}

func NewNotificationServiceAckNotificationsResult() *NotificationServiceAckNotificationsResult {
	return &NotificationServiceAckNotificationsResult{}
}

func (p *NotificationServiceAckNotificationsResult) InitDefault() {
}

var NotificationServiceAckNotificationsResult_Success_DEFAULT *AckNotificationsResp

func (p *NotificationServiceAckNotificationsResult) GetSuccess() (v *AckNotificationsResp) {
	if !p.IsSetSuccess() {
		return NotificationServiceAckNotificationsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *NotificationServiceAckNotificationsResult) SetSuccess(x interface{}) {
	p.Success = x.(*AckNotificationsResp)
}

func (p *NotificationServiceAckNotificationsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *NotificationServiceAckNotificationsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("NotificationServiceAckNotificationsResult(%+v)", *p)
}

var fieldIDToName_NotificationServiceAckNotificationsResult = map[int16]string{
	0: "success",
}
