// Code generated by Kitex v0.14.1. DO NOT EDIT.

package pmservice

import (
	"context"
	pm "eigenflux_server/kitex_gen/eigenflux/pm"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetUnreadCount(ctx context.Context, req *pm.GetUnreadCountReq, callOptions ...callopt.Option) (r *pm.GetUnreadCountResp, err error)
	MarkConvRead(ctx context.Context, req *pm.MarkConvReadReq, callOptions ...callopt.Option) (r *pm.MarkConvReadResp, err error)
	SendPM(ctx context.Context, req *pm.SendPMReq, callOptions ...callopt.Option) (r *pm.SendPMResp, err error)
	FetchPM(ctx context.Context, req *pm.FetchPMReq, callOptions ...callopt.Option) (r *pm.FetchPMResp, err error)
	FetchPMHistory(ctx context.Context, req *pm.FetchPMHistoryReq, callOptions ...callopt.Option) (r *pm.FetchPMHistoryResp, err error)
	ListConversations(ctx context.Context, req *pm.ListConversationsReq, callOptions ...callopt.Option) (r *pm.ListConversationsResp, err error)
	GetConvHistory(ctx context.Context, req *pm.GetConvHistoryReq, callOptions ...callopt.Option) (r *pm.GetConvHistoryResp, err error)
	CloseConv(ctx context.Context, req *pm.CloseConvReq, callOptions ...callopt.Option) (r *pm.CloseConvResp, err error)
	SendFriendRequest(ctx context.Context, req *pm.SendFriendRequestReq, callOptions ...callopt.Option) (r *pm.SendFriendRequestResp, err error)
	HandleFriendRequest(ctx context.Context, req *pm.HandleFriendRequestReq, callOptions ...callopt.Option) (r *pm.HandleFriendRequestResp, err error)
	Unfriend(ctx context.Context, req *pm.UnfriendReq, callOptions ...callopt.Option) (r *pm.UnfriendResp, err error)
	BlockUser(ctx context.Context, req *pm.BlockUserReq, callOptions ...callopt.Option) (r *pm.BlockUserResp, err error)
	UnblockUser(ctx context.Context, req *pm.UnblockUserReq, callOptions ...callopt.Option) (r *pm.UnblockUserResp, err error)
	ListFriendRequests(ctx context.Context, req *pm.ListFriendRequestsReq, callOptions ...callopt.Option) (r *pm.ListFriendRequestsResp, err error)
	ListFriends(ctx context.Context, req *pm.ListFriendsReq, callOptions ...callopt.Option) (r *pm.ListFriendsResp, err error)
	UpdateFriendRemark(ctx context.Context, req *pm.UpdateFriendRemarkReq, callOptions ...callopt.Option) (r *pm.UpdateFriendRemarkResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kPMServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kPMServiceClient struct {
	*kClient
}

func (p *kPMServiceClient) GetUnreadCount(ctx context.Context, req *pm.GetUnreadCountReq, callOptions ...callopt.Option) (r *pm.GetUnreadCountResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUnreadCount(ctx, req)
}

func (p *kPMServiceClient) MarkConvRead(ctx context.Context, req *pm.MarkConvReadReq, callOptions ...callopt.Option) (r *pm.MarkConvReadResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.MarkConvRead(ctx, req)
}

func (p *kPMServiceClient) SendPM(ctx context.Context, req *pm.SendPMReq, callOptions ...callopt.Option) (r *pm.SendPMResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SendPM(ctx, req)
}

func (p *kPMServiceClient) FetchPM(ctx context.Context, req *pm.FetchPMReq, callOptions ...callopt.Option) (r *pm.FetchPMResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FetchPM(ctx, req)
}

func (p *kPMServiceClient) FetchPMHistory(ctx context.Context, req *pm.FetchPMHistoryReq, callOptions ...callopt.Option) (r *pm.FetchPMHistoryResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FetchPMHistory(ctx, req)
}

func (p *kPMServiceClient) ListConversations(ctx context.Context, req *pm.ListConversationsReq, callOptions ...callopt.Option) (r *pm.ListConversationsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListConversations(ctx, req)
}

func (p *kPMServiceClient) GetConvHistory(ctx context.Context, req *pm.GetConvHistoryReq, callOptions ...callopt.Option) (r *pm.GetConvHistoryResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetConvHistory(ctx, req)
}

func (p *kPMServiceClient) CloseConv(ctx context.Context, req *pm.CloseConvReq, callOptions ...callopt.Option) (r *pm.CloseConvResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CloseConv(ctx, req)
}

func (p *kPMServiceClient) SendFriendRequest(ctx context.Context, req *pm.SendFriendRequestReq, callOptions ...callopt.Option) (r *pm.SendFriendRequestResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SendFriendRequest(ctx, req)
}

func (p *kPMServiceClient) HandleFriendRequest(ctx context.Context, req *pm.HandleFriendRequestReq, callOptions ...callopt.Option) (r *pm.HandleFriendRequestResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.HandleFriendRequest(ctx, req)
}

func (p *kPMServiceClient) Unfriend(ctx context.Context, req *pm.UnfriendReq, callOptions ...callopt.Option) (r *pm.UnfriendResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Unfriend(ctx, req)
}

func (p *kPMServiceClient) BlockUser(ctx context.Context, req *pm.BlockUserReq, callOptions ...callopt.Option) (r *pm.BlockUserResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BlockUser(ctx, req)
}

func (p *kPMServiceClient) UnblockUser(ctx context.Context, req *pm.UnblockUserReq, callOptions ...callopt.Option) (r *pm.UnblockUserResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UnblockUser(ctx, req)
}

func (p *kPMServiceClient) ListFriendRequests(ctx context.Context, req *pm.ListFriendRequestsReq, callOptions ...callopt.Option) (r *pm.ListFriendRequestsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListFriendRequests(ctx, req)
}

func (p *kPMServiceClient) ListFriends(ctx context.Context, req *pm.ListFriendsReq, callOptions ...callopt.Option) (r *pm.ListFriendsResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListFriends(ctx, req)
}

func (p *kPMServiceClient) UpdateFriendRemark(ctx context.Context, req *pm.UpdateFriendRemarkReq, callOptions ...callopt.Option) (r *pm.UpdateFriendRemarkResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateFriendRemark(ctx, req)
}
