// Code generated by Kitex v0.14.1. DO NOT EDIT.

package pmservice

import (
	"context"
	pm "eigenflux_server/kitex_gen/eigenflux/pm"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"GetUnreadCount": kitex.NewMethodInfo(
		getUnreadCountHandler,
		newPMServiceGetUnreadCountArgs,
		newPMServiceGetUnreadCountResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"MarkConvRead": kitex.NewMethodInfo(
		markConvReadHandler,
		newPMServiceMarkConvReadArgs,
		newPMServiceMarkConvReadResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SendPM": kitex.NewMethodInfo(
		sendPMHandler,
		newPMServiceSendPMArgs,
		newPMServiceSendPMResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"FetchPM": kitex.NewMethodInfo(
		fetchPMHandler,
		newPMServiceFetchPMArgs,
		newPMServiceFetchPMResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"FetchPMHistory": kitex.NewMethodInfo(
		fetchPMHistoryHandler,
		newPMServiceFetchPMHistoryArgs,
		newPMServiceFetchPMHistoryResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListConversations": kitex.NewMethodInfo(
		listConversationsHandler,
		newPMServiceListConversationsArgs,
		newPMServiceListConversationsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetConvHistory": kitex.NewMethodInfo(
		getConvHistoryHandler,
		newPMServiceGetConvHistoryArgs,
		newPMServiceGetConvHistoryResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"CloseConv": kitex.NewMethodInfo(
		closeConvHandler,
		newPMServiceCloseConvArgs,
		newPMServiceCloseConvResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SendFriendRequest": kitex.NewMethodInfo(
		sendFriendRequestHandler,
		newPMServiceSendFriendRequestArgs,
		newPMServiceSendFriendRequestResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"HandleFriendRequest": kitex.NewMethodInfo(
		handleFriendRequestHandler,
		newPMServiceHandleFriendRequestArgs,
		newPMServiceHandleFriendRequestResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Unfriend": kitex.NewMethodInfo(
		unfriendHandler,
		newPMServiceUnfriendArgs,
		newPMServiceUnfriendResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"BlockUser": kitex.NewMethodInfo(
		blockUserHandler,
		newPMServiceBlockUserArgs,
		newPMServiceBlockUserResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UnblockUser": kitex.NewMethodInfo(
		unblockUserHandler,
		newPMServiceUnblockUserArgs,
		newPMServiceUnblockUserResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListFriendRequests": kitex.NewMethodInfo(
		listFriendRequestsHandler,
		newPMServiceListFriendRequestsArgs,
		newPMServiceListFriendRequestsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListFriends": kitex.NewMethodInfo(
		listFriendsHandler,
		newPMServiceListFriendsArgs,
		newPMServiceListFriendsResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateFriendRemark": kitex.NewMethodInfo(
		updateFriendRemarkHandler,
		newPMServiceUpdateFriendRemarkArgs,
		newPMServiceUpdateFriendRemarkResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	pMServiceServiceInfo                = NewServiceInfo()
	pMServiceServiceInfoForClient       = NewServiceInfoForClient()
	pMServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return pMServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return pMServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return pMServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "PMService"
	handlerType := (*pm.PMService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "pm",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.14.1",
		Extra:           extra,
	}
	return svcInfo
}

func getUnreadCountHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*pm.PMServiceGetUnreadCountArgs)
	realResult := result.(*pm.PMServiceGetUnreadCountResult)
	success, err := handler.(pm.PMService).GetUnreadCount(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPMServiceGetUnreadCountArgs() interface{} {
	return pm.NewPMServiceGetUnreadCountArgs()
}

func newPMServiceGetUnreadCountResult() interface{} {
	return pm.NewPMServiceGetUnreadCountResult()
}

func markConvReadHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*pm.PMServiceMarkConvReadArgs)
	realResult := result.(*pm.PMServiceMarkConvReadResult)
	success, err := handler.(pm.PMService).MarkConvRead(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPMServiceMarkConvReadArgs() interface{} {
	return pm.NewPMServiceMarkConvReadArgs()
}

func newPMServiceMarkConvReadResult() interface{} {
	return pm.NewPMServiceMarkConvReadResult()
}

func sendPMHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*pm.PMServiceSendPMArgs)
	realResult := result.(*pm.PMServiceSendPMResult)
	success, err := handler.(pm.PMService).SendPM(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPMServiceSendPMArgs() interface{} {
	return pm.NewPMServiceSendPMArgs()
}

func newPMServiceSendPMResult() interface{} {
	return pm.NewPMServiceSendPMResult()
}

func fetchPMHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*pm.PMServiceFetchPMArgs)
	realResult := result.(*pm.PMServiceFetchPMResult)
	success, err := handler.(pm.PMService).FetchPM(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPMServiceFetchPMArgs() interface{} {
	return pm.NewPMServiceFetchPMArgs()
}

func newPMServiceFetchPMResult() interface{} {
	return pm.NewPMServiceFetchPMResult()
}

func fetchPMHistoryHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*pm.PMServiceFetchPMHistoryArgs)
	realResult := result.(*pm.PMServiceFetchPMHistoryResult)
	success, err := handler.(pm.PMService).FetchPMHistory(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPMServiceFetchPMHistoryArgs() interface{} {
	return pm.NewPMServiceFetchPMHistoryArgs()
}

func newPMServiceFetchPMHistoryResult() interface{} {
	return pm.NewPMServiceFetchPMHistoryResult()
}

func listConversationsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*pm.PMServiceListConversationsArgs)
	realResult := result.(*pm.PMServiceListConversationsResult)
	success, err := handler.(pm.PMService).ListConversations(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPMServiceListConversationsArgs() interface{} {
	return pm.NewPMServiceListConversationsArgs()
}

func newPMServiceListConversationsResult() interface{} {
	return pm.NewPMServiceListConversationsResult()
}

func getConvHistoryHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*pm.PMServiceGetConvHistoryArgs)
	realResult := result.(*pm.PMServiceGetConvHistoryResult)
	success, err := handler.(pm.PMService).GetConvHistory(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPMServiceGetConvHistoryArgs() interface{} {
	return pm.NewPMServiceGetConvHistoryArgs()
}

func newPMServiceGetConvHistoryResult() interface{} {
	return pm.NewPMServiceGetConvHistoryResult()
}

func closeConvHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*pm.PMServiceCloseConvArgs)
	realResult := result.(*pm.PMServiceCloseConvResult)
	success, err := handler.(pm.PMService).CloseConv(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPMServiceCloseConvArgs() interface{} {
	return pm.NewPMServiceCloseConvArgs()
}

func newPMServiceCloseConvResult() interface{} {
	return pm.NewPMServiceCloseConvResult()
}

func sendFriendRequestHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*pm.PMServiceSendFriendRequestArgs)
	realResult := result.(*pm.PMServiceSendFriendRequestResult)
	success, err := handler.(pm.PMService).SendFriendRequest(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPMServiceSendFriendRequestArgs() interface{} {
	return pm.NewPMServiceSendFriendRequestArgs()
}

func newPMServiceSendFriendRequestResult() interface{} {
	return pm.NewPMServiceSendFriendRequestResult()
}

func handleFriendRequestHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*pm.PMServiceHandleFriendRequestArgs)
	realResult := result.(*pm.PMServiceHandleFriendRequestResult)
	success, err := handler.(pm.PMService).HandleFriendRequest(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPMServiceHandleFriendRequestArgs() interface{} {
	return pm.NewPMServiceHandleFriendRequestArgs()
}

func newPMServiceHandleFriendRequestResult() interface{} {
	return pm.NewPMServiceHandleFriendRequestResult()
}

func unfriendHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*pm.PMServiceUnfriendArgs)
	realResult := result.(*pm.PMServiceUnfriendResult)
	success, err := handler.(pm.PMService).Unfriend(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPMServiceUnfriendArgs() interface{} {
	return pm.NewPMServiceUnfriendArgs()
}

func newPMServiceUnfriendResult() interface{} {
	return pm.NewPMServiceUnfriendResult()
}

func blockUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*pm.PMServiceBlockUserArgs)
	realResult := result.(*pm.PMServiceBlockUserResult)
	success, err := handler.(pm.PMService).BlockUser(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPMServiceBlockUserArgs() interface{} {
	return pm.NewPMServiceBlockUserArgs()
}

func newPMServiceBlockUserResult() interface{} {
	return pm.NewPMServiceBlockUserResult()
}

func unblockUserHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*pm.PMServiceUnblockUserArgs)
	realResult := result.(*pm.PMServiceUnblockUserResult)
	success, err := handler.(pm.PMService).UnblockUser(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPMServiceUnblockUserArgs() interface{} {
	return pm.NewPMServiceUnblockUserArgs()
}

func newPMServiceUnblockUserResult() interface{} {
	return pm.NewPMServiceUnblockUserResult()
}

func listFriendRequestsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*pm.PMServiceListFriendRequestsArgs)
	realResult := result.(*pm.PMServiceListFriendRequestsResult)
	success, err := handler.(pm.PMService).ListFriendRequests(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPMServiceListFriendRequestsArgs() interface{} {
	return pm.NewPMServiceListFriendRequestsArgs()
}

func newPMServiceListFriendRequestsResult() interface{} {
	return pm.NewPMServiceListFriendRequestsResult()
}

func listFriendsHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*pm.PMServiceListFriendsArgs)
	realResult := result.(*pm.PMServiceListFriendsResult)
	success, err := handler.(pm.PMService).ListFriends(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPMServiceListFriendsArgs() interface{} {
	return pm.NewPMServiceListFriendsArgs()
}

func newPMServiceListFriendsResult() interface{} {
	return pm.NewPMServiceListFriendsResult()
}

func updateFriendRemarkHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*pm.PMServiceUpdateFriendRemarkArgs)
	realResult := result.(*pm.PMServiceUpdateFriendRemarkResult)
	success, err := handler.(pm.PMService).UpdateFriendRemark(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newPMServiceUpdateFriendRemarkArgs() interface{} {
	return pm.NewPMServiceUpdateFriendRemarkArgs()
}

func newPMServiceUpdateFriendRemarkResult() interface{} {
	return pm.NewPMServiceUpdateFriendRemarkResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetUnreadCount(ctx context.Context, req *pm.GetUnreadCountReq) (r *pm.GetUnreadCountResp, err error) {
	var _args pm.PMServiceGetUnreadCountArgs
	_args.Req = req
	var _result pm.PMServiceGetUnreadCountResult
	if err = p.c.Call(ctx, "GetUnreadCount", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) MarkConvRead(ctx context.Context, req *pm.MarkConvReadReq) (r *pm.MarkConvReadResp, err error) {
	var _args pm.PMServiceMarkConvReadArgs
	_args.Req = req
	var _result pm.PMServiceMarkConvReadResult
	if err = p.c.Call(ctx, "MarkConvRead", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SendPM(ctx context.Context, req *pm.SendPMReq) (r *pm.SendPMResp, err error) {
	var _args pm.PMServiceSendPMArgs
	_args.Req = req
	var _result pm.PMServiceSendPMResult
	if err = p.c.Call(ctx, "SendPM", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) FetchPM(ctx context.Context, req *pm.FetchPMReq) (r *pm.FetchPMResp, err error) {
	var _args pm.PMServiceFetchPMArgs
	_args.Req = req
	var _result pm.PMServiceFetchPMResult
	if err = p.c.Call(ctx, "FetchPM", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) FetchPMHistory(ctx context.Context, req *pm.FetchPMHistoryReq) (r *pm.FetchPMHistoryResp, err error) {
	var _args pm.PMServiceFetchPMHistoryArgs
	_args.Req = req
	var _result pm.PMServiceFetchPMHistoryResult
	if err = p.c.Call(ctx, "FetchPMHistory", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListConversations(ctx context.Context, req *pm.ListConversationsReq) (r *pm.ListConversationsResp, err error) {
	var _args pm.PMServiceListConversationsArgs
	_args.Req = req
	var _result pm.PMServiceListConversationsResult
	if err = p.c.Call(ctx, "ListConversations", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetConvHistory(ctx context.Context, req *pm.GetConvHistoryReq) (r *pm.GetConvHistoryResp, err error) {
	var _args pm.PMServiceGetConvHistoryArgs
	_args.Req = req
	var _result pm.PMServiceGetConvHistoryResult
	if err = p.c.Call(ctx, "GetConvHistory", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CloseConv(ctx context.Context, req *pm.CloseConvReq) (r *pm.CloseConvResp, err error) {
	var _args pm.PMServiceCloseConvArgs
	_args.Req = req
	var _result pm.PMServiceCloseConvResult
	if err = p.c.Call(ctx, "CloseConv", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SendFriendRequest(ctx context.Context, req *pm.SendFriendRequestReq) (r *pm.SendFriendRequestResp, err error) {
	var _args pm.PMServiceSendFriendRequestArgs
	_args.Req = req
	var _result pm.PMServiceSendFriendRequestResult
	if err = p.c.Call(ctx, "SendFriendRequest", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) HandleFriendRequest(ctx context.Context, req *pm.HandleFriendRequestReq) (r *pm.HandleFriendRequestResp, err error) {
	var _args pm.PMServiceHandleFriendRequestArgs
	_args.Req = req
	var _result pm.PMServiceHandleFriendRequestResult
	if err = p.c.Call(ctx, "HandleFriendRequest", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Unfriend(ctx context.Context, req *pm.UnfriendReq) (r *pm.UnfriendResp, err error) {
	var _args pm.PMServiceUnfriendArgs
	_args.Req = req
	var _result pm.PMServiceUnfriendResult
	if err = p.c.Call(ctx, "Unfriend", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) BlockUser(ctx context.Context, req *pm.BlockUserReq) (r *pm.BlockUserResp, err error) {
	var _args pm.PMServiceBlockUserArgs
	_args.Req = req
	var _result pm.PMServiceBlockUserResult
	if err = p.c.Call(ctx, "BlockUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UnblockUser(ctx context.Context, req *pm.UnblockUserReq) (r *pm.UnblockUserResp, err error) {
	var _args pm.PMServiceUnblockUserArgs
	_args.Req = req
	var _result pm.PMServiceUnblockUserResult
	if err = p.c.Call(ctx, "UnblockUser", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListFriendRequests(ctx context.Context, req *pm.ListFriendRequestsReq) (r *pm.ListFriendRequestsResp, err error) {
	var _args pm.PMServiceListFriendRequestsArgs
	_args.Req = req
	var _result pm.PMServiceListFriendRequestsResult
	if err = p.c.Call(ctx, "ListFriendRequests", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListFriends(ctx context.Context, req *pm.ListFriendsReq) (r *pm.ListFriendsResp, err error) {
	var _args pm.PMServiceListFriendsArgs
	_args.Req = req
	var _result pm.PMServiceListFriendsResult
	if err = p.c.Call(ctx, "ListFriends", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateFriendRemark(ctx context.Context, req *pm.UpdateFriendRemarkReq) (r *pm.UpdateFriendRemarkResp, err error) {
	var _args pm.PMServiceUpdateFriendRemarkArgs
	_args.Req = req
	var _result pm.PMServiceUpdateFriendRemarkResult
	if err = p.c.Call(ctx, "UpdateFriendRemark", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
