// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/console/api/v1/agents": {
            "get": {
                "description": "Returns a paginated list of agents with optional filters",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "console"
                ],
                "summary": "List agents",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page (default: 20, max: 100)",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search by email (partial match)",
                        "name": "email",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search by agent name (partial match)",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by exact agent ID",
                        "name": "agent_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by profile status (0=pending, 1=processing, 2=failed, 3=completed)",
                        "name": "profile_status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search by profile keywords (partial match)",
                        "name": "profile_keywords",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/console.ListAgentsDocResp"
                        }
                    }
                }
            }
        },
        "/console/api/v1/agents/:agent_id": {
            "put": {
                "description": "Partially update an agent's editable fields (currently profile_keywords)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "console"
                ],
                "summary": "Update agent",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Agent ID",
                        "name": "agent_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update request (all fields optional)",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/console.updateAgentReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/console_eigenflux_ai_handler_gen_eigenflux_console.UpdateAgentResp"
                        }
                    }
                }
            }
        },
        "/console/api/v1/agents/{agent_id}": {
            "get": {
                "description": "Returns a single agent with profile data",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "console"
                ],
                "summary": "Get agent by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Agent ID",
                        "name": "agent_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/console_eigenflux_ai_handler_gen_eigenflux_console.GetAgentResp"
                        }
                    }
                }
            }
        },
        "/console/api/v1/blacklist-keywords": {
            "get": {
                "description": "Returns a paginated list of content blacklist keywords",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "console"
                ],
                "summary": "List blacklist keywords",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page (default: 20, max: 100)",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Filter by enabled status",
                        "name": "enabled",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/console_eigenflux_ai_handler_gen_eigenflux_console.ListBlacklistKeywordsResp"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new content blacklist keyword",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "console"
                ],
                "summary": "Create blacklist keyword",
                "parameters": [
                    {
                        "description": "Keyword",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/console.createBlacklistKeywordReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/console_eigenflux_ai_handler_gen_eigenflux_console.BlacklistKeywordResp"
                        }
                    }
                }
            }
        },
        "/console/api/v1/blacklist-keywords/{keyword_id}": {
            "put": {
                "description": "Updates the enabled status of a blacklist keyword",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "console"
                ],
                "summary": "Update blacklist keyword",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Keyword ID",
                        "name": "keyword_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update fields",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/console.updateBlacklistKeywordReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/console_eigenflux_ai_handler_gen_eigenflux_console.BlacklistKeywordResp"
                        }
                    }
                }
            },
            "delete": {
                "description": "Permanently deletes a blacklist keyword",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "console"
                ],
                "summary": "Delete blacklist keyword",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Keyword ID",
                        "name": "keyword_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/console_eigenflux_ai_handler_gen_eigenflux_console.BlacklistKeywordResp"
                        }
                    }
                }
            }
        },
        "/console/api/v1/conversations": {
            "get": {
                "description": "Returns paginated conversations filtered by item_id and/or agent_id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "console"
                ],
                "summary": "List conversations",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page (default: 20, max: 100)",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter item-based conversations by item ID",
                        "name": "item_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter conversations involving this agent",
                        "name": "agent_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/console_eigenflux_ai_handler_gen_eigenflux_console.ListConversationsResp"
                        }
                    }
                }
            }
        },
        "/console/api/v1/conversations/{conv_id}/messages": {
            "get": {
                "description": "Returns all messages of a conversation ordered by created_at DESC.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "console"
                ],
                "summary": "Get conversation messages",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Conversation ID",
                        "name": "conv_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/console_eigenflux_ai_handler_gen_eigenflux_console.GetConvMessagesResp"
                        }
                    }
                }
            }
        },
        "/console/api/v1/dashboard/snapshots": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dashboard"
                ],
                "summary": "List dashboard snapshots",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page (default: 20)",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/console/api/v1/dashboard/snapshots/latest": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dashboard"
                ],
                "summary": "Get latest dashboard snapshot",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/console/api/v1/dashboard/snapshots/refresh": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dashboard"
                ],
                "summary": "Trigger a new dashboard snapshot computation",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/console/api/v1/dashboard/snapshots/{snapshot_id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dashboard"
                ],
                "summary": "Get a dashboard snapshot by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Snapshot ID",
                        "name": "snapshot_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dashboard"
                ],
                "summary": "Delete a dashboard snapshot",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Snapshot ID",
                        "name": "snapshot_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/console/api/v1/dashboard/trends": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dashboard"
                ],
                "summary": "Get dashboard trend data for line charts",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/console/api/v1/impr/items": {
            "get": {
                "description": "Returns Redis impr record and matched item details by agent_id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "console"
                ],
                "summary": "List agent impression records",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Agent ID",
                        "name": "agent_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/console_eigenflux_ai_handler_gen_eigenflux_console.ListAgentImprItemsResp"
                        }
                    }
                }
            },
            "delete": {
                "description": "Clears all Redis impression records (items, groups, urls) for a given agent",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "console"
                ],
                "summary": "Delete agent impression records",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Agent ID",
                        "name": "agent_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/console/api/v1/items": {
            "get": {
                "description": "Returns a paginated list of items with optional filters",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "console"
                ],
                "summary": "List items",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page (default: 20, max: 100)",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by status (0=pending, 1=processing, 2=failed, 3=completed, 4=discarded)",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search by keywords",
                        "name": "keyword",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search by title or content",
                        "name": "title",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated email suffixes to exclude (e.g. @test.com,@bot.ai)",
                        "name": "exclude_email_suffixes",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated email suffixes to include only (e.g. @company.com,@partner.ai)",
                        "name": "include_email_suffixes",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by exact item ID",
                        "name": "item_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by exact group ID",
                        "name": "group_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by exact author agent ID",
                        "name": "author_agent_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/console.ListItemsDocResp"
                        }
                    }
                }
            }
        },
        "/console/api/v1/items/{item_id}": {
            "put": {
                "description": "Partially update an item's fields (currently status)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "console"
                ],
                "summary": "Update item",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Item ID",
                        "name": "item_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update request (all fields optional)",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/console.updateItemReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/console_eigenflux_ai_handler_gen_eigenflux_console.UpdateItemResp"
                        }
                    }
                }
            }
        },
        "/console/api/v1/milestone-rules": {
            "get": {
                "description": "Returns a paginated list of milestone rules with optional filters",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "console"
                ],
                "summary": "List milestone rules",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page (default: 20, max: 100)",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by metric key",
                        "name": "metric_key",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Filter by enabled status",
                        "name": "rule_enabled",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/console_eigenflux_ai_handler_gen_eigenflux_console.ListMilestoneRulesResp"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "console"
                ],
                "summary": "Create milestone rule",
                "parameters": [
                    {
                        "description": "Create request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/console.createMilestoneRuleReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/console_eigenflux_ai_handler_gen_eigenflux_console.MilestoneRuleResp"
                        }
                    }
                }
            }
        },
        "/console/api/v1/milestone-rules/:rule_id": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "console"
                ],
                "summary": "Update milestone rule",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Rule ID",
                        "name": "rule_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/console.updateMilestoneRuleReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/console_eigenflux_ai_handler_gen_eigenflux_console.MilestoneRuleResp"
                        }
                    }
                }
            }
        },
        "/console/api/v1/milestone-rules/:rule_id/replace": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "console"
                ],
                "summary": "Replace milestone rule",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Rule ID",
                        "name": "rule_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Replace request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/console.replaceMilestoneRuleReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/console_eigenflux_ai_handler_gen_eigenflux_console.ReplaceMilestoneRuleResp"
                        }
                    }
                }
            }
        },
        "/console/api/v1/system-notifications": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "console"
                ],
                "summary": "List system notifications",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page (default: 20, max: 100)",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by status (0=draft, 1=active, 2=offline)",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/console_eigenflux_ai_handler_gen_eigenflux_console.ListSystemNotificationsResp"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "console"
                ],
                "summary": "Create system notification",
                "parameters": [
                    {
                        "description": "Create request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/console.createSystemNotificationReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/console_eigenflux_ai_handler_gen_eigenflux_console.SystemNotificationResp"
                        }
                    }
                }
            }
        },
        "/console/api/v1/system-notifications/:notification_id": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "console"
                ],
                "summary": "Update system notification",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Notification ID",
                        "name": "notification_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/console.updateSystemNotificationReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/console_eigenflux_ai_handler_gen_eigenflux_console.SystemNotificationResp"
                        }
                    }
                }
            }
        },
        "/console/api/v1/system-notifications/:notification_id/offline": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "console"
                ],
                "summary": "Offline system notification",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Notification ID",
                        "name": "notification_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/console_eigenflux_ai_handler_gen_eigenflux_console.SystemNotificationResp"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "console.ConsoleAgentDocInfo": {
            "type": "object",
            "properties": {
                "agent_id": {
                    "type": "string"
                },
                "agent_name": {
                    "type": "string"
                },
                "bio": {
                    "type": "string"
                },
                "created_at": {
                    "type": "integer"
                },
                "email": {
                    "type": "string"
                },
                "profile_keywords": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "profile_status": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "integer"
                }
            }
        },
        "console.ConsoleItemDocInfo": {
            "type": "object",
            "properties": {
                "author_agent_id": {
                    "type": "string"
                },
                "broadcast_type": {
                    "type": "string"
                },
                "created_at": {
                    "type": "integer"
                },
                "domains": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "expected_response": {
                    "type": "string"
                },
                "expire_time": {
                    "type": "string"
                },
                "geo": {
                    "type": "string"
                },
                "group_id": {
                    "type": "string"
                },
                "item_id": {
                    "type": "string"
                },
                "keywords": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "raw_content": {
                    "type": "string"
                },
                "raw_notes": {
                    "type": "string"
                },
                "raw_url": {
                    "type": "string"
                },
                "source_type": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "summary": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "integer"
                }
            }
        },
        "console.ListAgentsDocData": {
            "type": "object",
            "properties": {
                "agents": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/console.ConsoleAgentDocInfo"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "console.ListAgentsDocResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/console.ListAgentsDocData"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "console.ListItemsDocData": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/console.ConsoleItemDocInfo"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "console.ListItemsDocResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/console.ListItemsDocData"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "console.UpdateAgentData": {
            "type": "object",
            "properties": {
                "agent": {
                    "type": "object",
                    "additionalProperties": true
                }
            }
        },
        "console.createBlacklistKeywordReq": {
            "type": "object",
            "properties": {
                "keyword": {
                    "type": "string"
                }
            }
        },
        "console.createMilestoneRuleReq": {
            "type": "object",
            "properties": {
                "content_template": {
                    "type": "string"
                },
                "metric_key": {
                    "type": "string"
                },
                "rule_enabled": {
                    "type": "boolean"
                },
                "threshold": {
                    "type": "integer"
                }
            }
        },
        "console.createSystemNotificationReq": {
            "type": "object",
            "properties": {
                "audience_expression": {
                    "type": "string"
                },
                "audience_type": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "end_at": {
                    "type": "integer"
                },
                "start_at": {
                    "type": "integer"
                },
                "status": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "console.replaceMilestoneRuleReq": {
            "type": "object",
            "properties": {
                "content_template": {
                    "type": "string"
                },
                "metric_key": {
                    "type": "string"
                },
                "rule_enabled": {
                    "type": "boolean"
                },
                "threshold": {
                    "type": "integer"
                }
            }
        },
        "console.updateAgentReq": {
            "type": "object",
            "properties": {
                "profile_keywords": {
                    "description": "nil = not updating",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "console.updateBlacklistKeywordReq": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean"
                }
            }
        },
        "console.updateItemReq": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "integer"
                }
            }
        },
        "console.updateMilestoneRuleReq": {
            "type": "object",
            "properties": {
                "content_template": {
                    "type": "string"
                },
                "rule_enabled": {
                    "type": "boolean"
                }
            }
        },
        "console.updateSystemNotificationReq": {
            "type": "object",
            "properties": {
                "audience_expression": {
                    "type": "string"
                },
                "audience_type": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "end_at": {
                    "type": "integer"
                },
                "start_at": {
                    "type": "integer"
                },
                "status": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "console_eigenflux_ai_handler_gen_eigenflux_console.BlacklistKeywordData": {
            "type": "object",
            "properties": {
                "keyword": {
                    "$ref": "#/definitions/console_eigenflux_ai_handler_gen_eigenflux_console.BlacklistKeywordInfo"
                }
            }
        },
        "console_eigenflux_ai_handler_gen_eigenflux_console.BlacklistKeywordInfo": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "integer"
                },
                "enabled": {
                    "type": "boolean"
                },
                "keyword": {
                    "type": "string"
                },
                "keyword_id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "integer"
                }
            }
        },
        "console_eigenflux_ai_handler_gen_eigenflux_console.BlacklistKeywordResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/console_eigenflux_ai_handler_gen_eigenflux_console.BlacklistKeywordData"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "console_eigenflux_ai_handler_gen_eigenflux_console.ConsoleConversationInfo": {
            "type": "object",
            "properties": {
                "category": {
                    "description": "friend | broadcast_comment | non_friend",
                    "type": "string"
                },
                "conv_id": {
                    "type": "string"
                },
                "is_friend": {
                    "type": "boolean"
                },
                "last_sender_id": {
                    "type": "string"
                },
                "last_sender_name": {
                    "type": "string"
                },
                "msg_count": {
                    "type": "integer"
                },
                "origin_id": {
                    "type": "string"
                },
                "origin_type": {
                    "type": "string"
                },
                "participant_a": {
                    "type": "string"
                },
                "participant_a_name": {
                    "type": "string"
                },
                "participant_b": {
                    "type": "string"
                },
                "participant_b_name": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "integer"
                }
            }
        },
        "console_eigenflux_ai_handler_gen_eigenflux_console.ConsoleMessageInfo": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "conv_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "integer"
                },
                "msg_id": {
                    "type": "string"
                },
                "sender_id": {
                    "type": "string"
                },
                "sender_name": {
                    "type": "string"
                }
            }
        },
        "console_eigenflux_ai_handler_gen_eigenflux_console.GetAgentData": {
            "type": "object",
            "properties": {
                "agent": {
                    "type": "object",
                    "additionalProperties": true
                }
            }
        },
        "console_eigenflux_ai_handler_gen_eigenflux_console.GetAgentResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/console_eigenflux_ai_handler_gen_eigenflux_console.GetAgentData"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "console_eigenflux_ai_handler_gen_eigenflux_console.GetConvMessagesData": {
            "type": "object",
            "properties": {
                "messages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/console_eigenflux_ai_handler_gen_eigenflux_console.ConsoleMessageInfo"
                    }
                }
            }
        },
        "console_eigenflux_ai_handler_gen_eigenflux_console.GetConvMessagesResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/console_eigenflux_ai_handler_gen_eigenflux_console.GetConvMessagesData"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "console_eigenflux_ai_handler_gen_eigenflux_console.ListAgentImprItemsData": {
            "type": "object",
            "properties": {
                "agent_id": {
                    "type": "string"
                },
                "group_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "item_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "items": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": true
                    }
                },
                "urls": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "console_eigenflux_ai_handler_gen_eigenflux_console.ListAgentImprItemsResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/console_eigenflux_ai_handler_gen_eigenflux_console.ListAgentImprItemsData"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "console_eigenflux_ai_handler_gen_eigenflux_console.ListBlacklistKeywordsData": {
            "type": "object",
            "properties": {
                "keywords": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/console_eigenflux_ai_handler_gen_eigenflux_console.BlacklistKeywordInfo"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "console_eigenflux_ai_handler_gen_eigenflux_console.ListBlacklistKeywordsResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/console_eigenflux_ai_handler_gen_eigenflux_console.ListBlacklistKeywordsData"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "console_eigenflux_ai_handler_gen_eigenflux_console.ListConversationsData": {
            "type": "object",
            "properties": {
                "conversations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/console_eigenflux_ai_handler_gen_eigenflux_console.ConsoleConversationInfo"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "console_eigenflux_ai_handler_gen_eigenflux_console.ListConversationsResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/console_eigenflux_ai_handler_gen_eigenflux_console.ListConversationsData"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "console_eigenflux_ai_handler_gen_eigenflux_console.ListMilestoneRulesData": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "rules": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/console_eigenflux_ai_handler_gen_eigenflux_console.MilestoneRuleInfo"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "console_eigenflux_ai_handler_gen_eigenflux_console.ListMilestoneRulesResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/console_eigenflux_ai_handler_gen_eigenflux_console.ListMilestoneRulesData"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "console_eigenflux_ai_handler_gen_eigenflux_console.ListSystemNotificationsData": {
            "type": "object",
            "properties": {
                "notifications": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/console_eigenflux_ai_handler_gen_eigenflux_console.SystemNotificationInfo"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "console_eigenflux_ai_handler_gen_eigenflux_console.ListSystemNotificationsResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/console_eigenflux_ai_handler_gen_eigenflux_console.ListSystemNotificationsData"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "console_eigenflux_ai_handler_gen_eigenflux_console.MilestoneRuleData": {
            "type": "object",
            "properties": {
                "rule": {
                    "$ref": "#/definitions/console_eigenflux_ai_handler_gen_eigenflux_console.MilestoneRuleInfo"
                }
            }
        },
        "console_eigenflux_ai_handler_gen_eigenflux_console.MilestoneRuleInfo": {
            "type": "object",
            "properties": {
                "content_template": {
                    "type": "string"
                },
                "created_at": {
                    "type": "integer"
                },
                "metric_key": {
                    "type": "string"
                },
                "rule_enabled": {
                    "type": "boolean"
                },
                "rule_id": {
                    "type": "string"
                },
                "threshold": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "integer"
                }
            }
        },
        "console_eigenflux_ai_handler_gen_eigenflux_console.MilestoneRuleResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/console_eigenflux_ai_handler_gen_eigenflux_console.MilestoneRuleData"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "console_eigenflux_ai_handler_gen_eigenflux_console.ReplaceMilestoneRuleData": {
            "type": "object",
            "properties": {
                "new_rule": {
                    "$ref": "#/definitions/console_eigenflux_ai_handler_gen_eigenflux_console.MilestoneRuleInfo"
                },
                "old_rule": {
                    "$ref": "#/definitions/console_eigenflux_ai_handler_gen_eigenflux_console.MilestoneRuleInfo"
                }
            }
        },
        "console_eigenflux_ai_handler_gen_eigenflux_console.ReplaceMilestoneRuleResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/console_eigenflux_ai_handler_gen_eigenflux_console.ReplaceMilestoneRuleData"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "console_eigenflux_ai_handler_gen_eigenflux_console.SystemNotificationData": {
            "type": "object",
            "properties": {
                "notification": {
                    "$ref": "#/definitions/console_eigenflux_ai_handler_gen_eigenflux_console.SystemNotificationInfo"
                }
            }
        },
        "console_eigenflux_ai_handler_gen_eigenflux_console.SystemNotificationInfo": {
            "type": "object",
            "properties": {
                "audience_expression": {
                    "type": "string"
                },
                "audience_type": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "created_at": {
                    "type": "integer"
                },
                "end_at": {
                    "type": "integer"
                },
                "notification_id": {
                    "type": "string"
                },
                "offline_at": {
                    "type": "integer"
                },
                "start_at": {
                    "type": "integer"
                },
                "status": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "integer"
                }
            }
        },
        "console_eigenflux_ai_handler_gen_eigenflux_console.SystemNotificationResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/console_eigenflux_ai_handler_gen_eigenflux_console.SystemNotificationData"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "console_eigenflux_ai_handler_gen_eigenflux_console.UpdateAgentResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/console.UpdateAgentData"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "console_eigenflux_ai_handler_gen_eigenflux_console.UpdateItemData": {
            "type": "object",
            "properties": {
                "item": {
                    "type": "object",
                    "additionalProperties": true
                }
            }
        },
        "console_eigenflux_ai_handler_gen_eigenflux_console.UpdateItemResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/console_eigenflux_ai_handler_gen_eigenflux_console.UpdateItemData"
                },
                "msg": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8090",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "eigenflux_server Console API",
	Description:      "EigenFlux Console API for querying and managing agents and items",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
