// Code generated by thriftgo (0.4.2). DO NOT EDIT.

package pm

import (
	"context"
	"database/sql"
	"database/sql/driver"
	"eigenflux_server/kitex_gen/eigenflux/base"
	"fmt"
)

type FriendRequestAction int64

const (
	FriendRequestAction_ACCEPT FriendRequestAction = 1
	FriendRequestAction_REJECT FriendRequestAction = 2
	FriendRequestAction_CANCEL FriendRequestAction = 3
)

func (p FriendRequestAction) String() string {
	switch p {
	case FriendRequestAction_ACCEPT:
		return "ACCEPT"
	case FriendRequestAction_REJECT:
		return "REJECT"
	case FriendRequestAction_CANCEL:
		return "CANCEL"
	}
	return "<UNSET>"
}

func FriendRequestActionFromString(s string) (FriendRequestAction, error) {
	switch s {
	case "ACCEPT":
		return FriendRequestAction_ACCEPT, nil
	case "REJECT":
		return FriendRequestAction_REJECT, nil
	case "CANCEL":
		return FriendRequestAction_CANCEL, nil
	}
	return FriendRequestAction(0), fmt.Errorf("not a valid FriendRequestAction string")
}

func FriendRequestActionPtr(v FriendRequestAction) *FriendRequestAction { return &v }
func (p *FriendRequestAction) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = FriendRequestAction(result.Int64)
	return
}

func (p *FriendRequestAction) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type SendPMReq struct {
	SenderId   int64  `thrift:"sender_id,1,required" frugal:"1,required,i64" json:"sender_id"`
	ReceiverId int64  `thrift:"receiver_id,2,required" frugal:"2,required,i64" json:"receiver_id"`
	Content    string `thrift:"content,3,required" frugal:"3,required,string" json:"content"`
	ItemId     *int64 `thrift:"item_id,4,optional" frugal:"4,optional,i64" json:"item_id,omitempty"`
	ConvId     *int64 `thrift:"conv_id,5,optional" frugal:"5,optional,i64" json:"conv_id,omitempty"`
}

func NewSendPMReq() *SendPMReq {
	return &SendPMReq{}
}

func (p *SendPMReq) InitDefault() {
}

func (p *SendPMReq) GetSenderId() (v int64) {
	return p.SenderId
}

func (p *SendPMReq) GetReceiverId() (v int64) {
	return p.ReceiverId
}

func (p *SendPMReq) GetContent() (v string) {
	return p.Content
}

var SendPMReq_ItemId_DEFAULT int64

func (p *SendPMReq) GetItemId() (v int64) {
	if !p.IsSetItemId() {
		return SendPMReq_ItemId_DEFAULT
	}
	return *p.ItemId
}

var SendPMReq_ConvId_DEFAULT int64

func (p *SendPMReq) GetConvId() (v int64) {
	if !p.IsSetConvId() {
		return SendPMReq_ConvId_DEFAULT
	}
	return *p.ConvId
}
func (p *SendPMReq) SetSenderId(val int64) {
	p.SenderId = val
}
func (p *SendPMReq) SetReceiverId(val int64) {
	p.ReceiverId = val
}
func (p *SendPMReq) SetContent(val string) {
	p.Content = val
}
func (p *SendPMReq) SetItemId(val *int64) {
	p.ItemId = val
}
func (p *SendPMReq) SetConvId(val *int64) {
	p.ConvId = val
}

func (p *SendPMReq) IsSetItemId() bool {
	return p.ItemId != nil
}

func (p *SendPMReq) IsSetConvId() bool {
	return p.ConvId != nil
}

func (p *SendPMReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SendPMReq(%+v)", *p)
}

var fieldIDToName_SendPMReq = map[int16]string{
	1: "sender_id",
	2: "receiver_id",
	3: "content",
	4: "item_id",
	5: "conv_id",
}

type SendPMResp struct {
	MsgId    int64          `thrift:"msg_id,1,required" frugal:"1,required,i64" json:"msg_id"`
	ConvId   int64          `thrift:"conv_id,2,required" frugal:"2,required,i64" json:"conv_id"`
	BaseResp *base.BaseResp `thrift:"base_resp,255,required" frugal:"255,required,base.BaseResp" json:"base_resp"`
}

func NewSendPMResp() *SendPMResp {
	return &SendPMResp{}
}

func (p *SendPMResp) InitDefault() {
}

func (p *SendPMResp) GetMsgId() (v int64) {
	return p.MsgId
}

func (p *SendPMResp) GetConvId() (v int64) {
	return p.ConvId
}

var SendPMResp_BaseResp_DEFAULT *base.BaseResp

func (p *SendPMResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return SendPMResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *SendPMResp) SetMsgId(val int64) {
	p.MsgId = val
}
func (p *SendPMResp) SetConvId(val int64) {
	p.ConvId = val
}
func (p *SendPMResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *SendPMResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *SendPMResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SendPMResp(%+v)", *p)
}

var fieldIDToName_SendPMResp = map[int16]string{
	1:   "msg_id",
	2:   "conv_id",
	255: "base_resp",
}

type FetchPMReq struct {
	AgentId int64  `thrift:"agent_id,1,required" frugal:"1,required,i64" json:"agent_id"`
	Cursor  *int64 `thrift:"cursor,2,optional" frugal:"2,optional,i64" json:"cursor,omitempty"`
	Limit   *int32 `thrift:"limit,3,optional" frugal:"3,optional,i32" json:"limit,omitempty"`
}

func NewFetchPMReq() *FetchPMReq {
	return &FetchPMReq{}
}

func (p *FetchPMReq) InitDefault() {
}

func (p *FetchPMReq) GetAgentId() (v int64) {
	return p.AgentId
}

var FetchPMReq_Cursor_DEFAULT int64

func (p *FetchPMReq) GetCursor() (v int64) {
	if !p.IsSetCursor() {
		return FetchPMReq_Cursor_DEFAULT
	}
	return *p.Cursor
}

var FetchPMReq_Limit_DEFAULT int32

func (p *FetchPMReq) GetLimit() (v int32) {
	if !p.IsSetLimit() {
		return FetchPMReq_Limit_DEFAULT
	}
	return *p.Limit
}
func (p *FetchPMReq) SetAgentId(val int64) {
	p.AgentId = val
}
func (p *FetchPMReq) SetCursor(val *int64) {
	p.Cursor = val
}
func (p *FetchPMReq) SetLimit(val *int32) {
	p.Limit = val
}

func (p *FetchPMReq) IsSetCursor() bool {
	return p.Cursor != nil
}

func (p *FetchPMReq) IsSetLimit() bool {
	return p.Limit != nil
}

func (p *FetchPMReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FetchPMReq(%+v)", *p)
}

var fieldIDToName_FetchPMReq = map[int16]string{
	1: "agent_id",
	2: "cursor",
	3: "limit",
}

type PMMessage struct {
	MsgId            int64   `thrift:"msg_id,1,required" frugal:"1,required,i64" json:"msg_id"`
	ConvId           int64   `thrift:"conv_id,2,required" frugal:"2,required,i64" json:"conv_id"`
	SenderId         int64   `thrift:"sender_id,3,required" frugal:"3,required,i64" json:"sender_id"`
	ReceiverId       int64   `thrift:"receiver_id,4,required" frugal:"4,required,i64" json:"receiver_id"`
	Content          string  `thrift:"content,5,required" frugal:"5,required,string" json:"content"`
	IsRead           bool    `thrift:"is_read,6,required" frugal:"6,required,bool" json:"is_read"`
	CreatedAt        int64   `thrift:"created_at,7,required" frugal:"7,required,i64" json:"created_at"`
	SenderName       *string `thrift:"sender_name,8,optional" frugal:"8,optional,string" json:"sender_name,omitempty"`
	ReceiverName     *string `thrift:"receiver_name,9,optional" frugal:"9,optional,string" json:"receiver_name,omitempty"`
	SenderIsOfficial *bool   `thrift:"sender_is_official,10,optional" frugal:"10,optional,bool" json:"sender_is_official,omitempty"`
}

func NewPMMessage() *PMMessage {
	return &PMMessage{}
}

func (p *PMMessage) InitDefault() {
}

func (p *PMMessage) GetMsgId() (v int64) {
	return p.MsgId
}

func (p *PMMessage) GetConvId() (v int64) {
	return p.ConvId
}

func (p *PMMessage) GetSenderId() (v int64) {
	return p.SenderId
}

func (p *PMMessage) GetReceiverId() (v int64) {
	return p.ReceiverId
}

func (p *PMMessage) GetContent() (v string) {
	return p.Content
}

func (p *PMMessage) GetIsRead() (v bool) {
	return p.IsRead
}

func (p *PMMessage) GetCreatedAt() (v int64) {
	return p.CreatedAt
}

var PMMessage_SenderName_DEFAULT string

func (p *PMMessage) GetSenderName() (v string) {
	if !p.IsSetSenderName() {
		return PMMessage_SenderName_DEFAULT
	}
	return *p.SenderName
}

var PMMessage_ReceiverName_DEFAULT string

func (p *PMMessage) GetReceiverName() (v string) {
	if !p.IsSetReceiverName() {
		return PMMessage_ReceiverName_DEFAULT
	}
	return *p.ReceiverName
}

var PMMessage_SenderIsOfficial_DEFAULT bool

func (p *PMMessage) GetSenderIsOfficial() (v bool) {
	if !p.IsSetSenderIsOfficial() {
		return PMMessage_SenderIsOfficial_DEFAULT
	}
	return *p.SenderIsOfficial
}
func (p *PMMessage) SetMsgId(val int64) {
	p.MsgId = val
}
func (p *PMMessage) SetConvId(val int64) {
	p.ConvId = val
}
func (p *PMMessage) SetSenderId(val int64) {
	p.SenderId = val
}
func (p *PMMessage) SetReceiverId(val int64) {
	p.ReceiverId = val
}
func (p *PMMessage) SetContent(val string) {
	p.Content = val
}
func (p *PMMessage) SetIsRead(val bool) {
	p.IsRead = val
}
func (p *PMMessage) SetCreatedAt(val int64) {
	p.CreatedAt = val
}
func (p *PMMessage) SetSenderName(val *string) {
	p.SenderName = val
}
func (p *PMMessage) SetReceiverName(val *string) {
	p.ReceiverName = val
}
func (p *PMMessage) SetSenderIsOfficial(val *bool) {
	p.SenderIsOfficial = val
}

func (p *PMMessage) IsSetSenderName() bool {
	return p.SenderName != nil
}

func (p *PMMessage) IsSetReceiverName() bool {
	return p.ReceiverName != nil
}

func (p *PMMessage) IsSetSenderIsOfficial() bool {
	return p.SenderIsOfficial != nil
}

func (p *PMMessage) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PMMessage(%+v)", *p)
}

var fieldIDToName_PMMessage = map[int16]string{
	1:  "msg_id",
	2:  "conv_id",
	3:  "sender_id",
	4:  "receiver_id",
	5:  "content",
	6:  "is_read",
	7:  "created_at",
	8:  "sender_name",
	9:  "receiver_name",
	10: "sender_is_official",
}

type FetchPMResp struct {
	Messages   []*PMMessage   `thrift:"messages,1,required" frugal:"1,required,list<PMMessage>" json:"messages"`
	NextCursor int64          `thrift:"next_cursor,2,required" frugal:"2,required,i64" json:"next_cursor"`
	BaseResp   *base.BaseResp `thrift:"base_resp,255,required" frugal:"255,required,base.BaseResp" json:"base_resp"`
}

func NewFetchPMResp() *FetchPMResp {
	return &FetchPMResp{}
}

func (p *FetchPMResp) InitDefault() {
}

func (p *FetchPMResp) GetMessages() (v []*PMMessage) {
	return p.Messages
}

func (p *FetchPMResp) GetNextCursor() (v int64) {
	return p.NextCursor
}

var FetchPMResp_BaseResp_DEFAULT *base.BaseResp

func (p *FetchPMResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return FetchPMResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *FetchPMResp) SetMessages(val []*PMMessage) {
	p.Messages = val
}
func (p *FetchPMResp) SetNextCursor(val int64) {
	p.NextCursor = val
}
func (p *FetchPMResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *FetchPMResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *FetchPMResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FetchPMResp(%+v)", *p)
}

var fieldIDToName_FetchPMResp = map[int16]string{
	1:   "messages",
	2:   "next_cursor",
	255: "base_resp",
}

type FetchPMHistoryReq struct {
	AgentId int64  `thrift:"agent_id,1,required" frugal:"1,required,i64" json:"agent_id"`
	Limit   *int32 `thrift:"limit,2,optional" frugal:"2,optional,i32" json:"limit,omitempty"`
}

func NewFetchPMHistoryReq() *FetchPMHistoryReq {
	return &FetchPMHistoryReq{}
}

func (p *FetchPMHistoryReq) InitDefault() {
}

func (p *FetchPMHistoryReq) GetAgentId() (v int64) {
	return p.AgentId
}

var FetchPMHistoryReq_Limit_DEFAULT int32

func (p *FetchPMHistoryReq) GetLimit() (v int32) {
	if !p.IsSetLimit() {
		return FetchPMHistoryReq_Limit_DEFAULT
	}
	return *p.Limit
}
func (p *FetchPMHistoryReq) SetAgentId(val int64) {
	p.AgentId = val
}
func (p *FetchPMHistoryReq) SetLimit(val *int32) {
	p.Limit = val
}

func (p *FetchPMHistoryReq) IsSetLimit() bool {
	return p.Limit != nil
}

func (p *FetchPMHistoryReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FetchPMHistoryReq(%+v)", *p)
}

var fieldIDToName_FetchPMHistoryReq = map[int16]string{
	1: "agent_id",
	2: "limit",
}

type FetchPMHistoryResp struct {
	Messages []*PMMessage   `thrift:"messages,1,required" frugal:"1,required,list<PMMessage>" json:"messages"`
	BaseResp *base.BaseResp `thrift:"base_resp,255,required" frugal:"255,required,base.BaseResp" json:"base_resp"`
}

func NewFetchPMHistoryResp() *FetchPMHistoryResp {
	return &FetchPMHistoryResp{}
}

func (p *FetchPMHistoryResp) InitDefault() {
}

func (p *FetchPMHistoryResp) GetMessages() (v []*PMMessage) {
	return p.Messages
}

var FetchPMHistoryResp_BaseResp_DEFAULT *base.BaseResp

func (p *FetchPMHistoryResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return FetchPMHistoryResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *FetchPMHistoryResp) SetMessages(val []*PMMessage) {
	p.Messages = val
}
func (p *FetchPMHistoryResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *FetchPMHistoryResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *FetchPMHistoryResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FetchPMHistoryResp(%+v)", *p)
}

var fieldIDToName_FetchPMHistoryResp = map[int16]string{
	1:   "messages",
	255: "base_resp",
}

type ListConversationsReq struct {
	AgentId    int64   `thrift:"agent_id,1,required" frugal:"1,required,i64" json:"agent_id"`
	Cursor     *int64  `thrift:"cursor,2,optional" frugal:"2,optional,i64" json:"cursor,omitempty"`
	Limit      *int32  `thrift:"limit,3,optional" frugal:"3,optional,i32" json:"limit,omitempty"`
	OriginType *string `thrift:"origin_type,4,optional" frugal:"4,optional,string" json:"origin_type,omitempty"`
}

func NewListConversationsReq() *ListConversationsReq {
	return &ListConversationsReq{}
}

func (p *ListConversationsReq) InitDefault() {
}

func (p *ListConversationsReq) GetAgentId() (v int64) {
	return p.AgentId
}

var ListConversationsReq_Cursor_DEFAULT int64

func (p *ListConversationsReq) GetCursor() (v int64) {
	if !p.IsSetCursor() {
		return ListConversationsReq_Cursor_DEFAULT
	}
	return *p.Cursor
}

var ListConversationsReq_Limit_DEFAULT int32

func (p *ListConversationsReq) GetLimit() (v int32) {
	if !p.IsSetLimit() {
		return ListConversationsReq_Limit_DEFAULT
	}
	return *p.Limit
}

var ListConversationsReq_OriginType_DEFAULT string

func (p *ListConversationsReq) GetOriginType() (v string) {
	if !p.IsSetOriginType() {
		return ListConversationsReq_OriginType_DEFAULT
	}
	return *p.OriginType
}
func (p *ListConversationsReq) SetAgentId(val int64) {
	p.AgentId = val
}
func (p *ListConversationsReq) SetCursor(val *int64) {
	p.Cursor = val
}
func (p *ListConversationsReq) SetLimit(val *int32) {
	p.Limit = val
}
func (p *ListConversationsReq) SetOriginType(val *string) {
	p.OriginType = val
}

func (p *ListConversationsReq) IsSetCursor() bool {
	return p.Cursor != nil
}

func (p *ListConversationsReq) IsSetLimit() bool {
	return p.Limit != nil
}

func (p *ListConversationsReq) IsSetOriginType() bool {
	return p.OriginType != nil
}

func (p *ListConversationsReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListConversationsReq(%+v)", *p)
}

var fieldIDToName_ListConversationsReq = map[int16]string{
	1: "agent_id",
	2: "cursor",
	3: "limit",
	4: "origin_type",
}

type ConversationInfo struct {
	ConvId             int64   `thrift:"conv_id,1,required" frugal:"1,required,i64" json:"conv_id"`
	ParticipantA       int64   `thrift:"participant_a,2,required" frugal:"2,required,i64" json:"participant_a"`
	ParticipantB       int64   `thrift:"participant_b,3,required" frugal:"3,required,i64" json:"participant_b"`
	UpdatedAt          int64   `thrift:"updated_at,4,required" frugal:"4,required,i64" json:"updated_at"`
	ParticipantAName   *string `thrift:"participant_a_name,6,optional" frugal:"6,optional,string" json:"participant_a_name,omitempty"`
	ParticipantBName   *string `thrift:"participant_b_name,7,optional" frugal:"7,optional,string" json:"participant_b_name,omitempty"`
	OriginType         *string `thrift:"origin_type,8,optional" frugal:"8,optional,string" json:"origin_type,omitempty"`
	OriginId           *int64  `thrift:"origin_id,9,optional" frugal:"9,optional,i64" json:"origin_id,omitempty"`
	PeerName           *string `thrift:"peer_name,10,optional" frugal:"10,optional,string" json:"peer_name,omitempty"`
	LastMessagePreview *string `thrift:"last_message_preview,11,optional" frugal:"11,optional,string" json:"last_message_preview,omitempty"`
	UnreadCount        *int32  `thrift:"unread_count,12,optional" frugal:"12,optional,i32" json:"unread_count,omitempty"`
	MsgCount           *int32  `thrift:"msg_count,13,optional" frugal:"13,optional,i32" json:"msg_count,omitempty"`
	Remark             *string `thrift:"remark,14,optional" frugal:"14,optional,string" json:"remark,omitempty"`
	IsFriend           *bool   `thrift:"is_friend,15,optional" frugal:"15,optional,bool" json:"is_friend,omitempty"`
	Category           *string `thrift:"category,16,optional" frugal:"16,optional,string" json:"category,omitempty"`
}

func NewConversationInfo() *ConversationInfo {
	return &ConversationInfo{}
}

func (p *ConversationInfo) InitDefault() {
}

func (p *ConversationInfo) GetConvId() (v int64) {
	return p.ConvId
}

func (p *ConversationInfo) GetParticipantA() (v int64) {
	return p.ParticipantA
}

func (p *ConversationInfo) GetParticipantB() (v int64) {
	return p.ParticipantB
}

func (p *ConversationInfo) GetUpdatedAt() (v int64) {
	return p.UpdatedAt
}

var ConversationInfo_ParticipantAName_DEFAULT string

func (p *ConversationInfo) GetParticipantAName() (v string) {
	if !p.IsSetParticipantAName() {
		return ConversationInfo_ParticipantAName_DEFAULT
	}
	return *p.ParticipantAName
}

var ConversationInfo_ParticipantBName_DEFAULT string

func (p *ConversationInfo) GetParticipantBName() (v string) {
	if !p.IsSetParticipantBName() {
		return ConversationInfo_ParticipantBName_DEFAULT
	}
	return *p.ParticipantBName
}

var ConversationInfo_OriginType_DEFAULT string

func (p *ConversationInfo) GetOriginType() (v string) {
	if !p.IsSetOriginType() {
		return ConversationInfo_OriginType_DEFAULT
	}
	return *p.OriginType
}

var ConversationInfo_OriginId_DEFAULT int64

func (p *ConversationInfo) GetOriginId() (v int64) {
	if !p.IsSetOriginId() {
		return ConversationInfo_OriginId_DEFAULT
	}
	return *p.OriginId
}

var ConversationInfo_PeerName_DEFAULT string

func (p *ConversationInfo) GetPeerName() (v string) {
	if !p.IsSetPeerName() {
		return ConversationInfo_PeerName_DEFAULT
	}
	return *p.PeerName
}

var ConversationInfo_LastMessagePreview_DEFAULT string

func (p *ConversationInfo) GetLastMessagePreview() (v string) {
	if !p.IsSetLastMessagePreview() {
		return ConversationInfo_LastMessagePreview_DEFAULT
	}
	return *p.LastMessagePreview
}

var ConversationInfo_UnreadCount_DEFAULT int32

func (p *ConversationInfo) GetUnreadCount() (v int32) {
	if !p.IsSetUnreadCount() {
		return ConversationInfo_UnreadCount_DEFAULT
	}
	return *p.UnreadCount
}

var ConversationInfo_MsgCount_DEFAULT int32

func (p *ConversationInfo) GetMsgCount() (v int32) {
	if !p.IsSetMsgCount() {
		return ConversationInfo_MsgCount_DEFAULT
	}
	return *p.MsgCount
}

var ConversationInfo_Remark_DEFAULT string

func (p *ConversationInfo) GetRemark() (v string) {
	if !p.IsSetRemark() {
		return ConversationInfo_Remark_DEFAULT
	}
	return *p.Remark
}

var ConversationInfo_IsFriend_DEFAULT bool

func (p *ConversationInfo) GetIsFriend() (v bool) {
	if !p.IsSetIsFriend() {
		return ConversationInfo_IsFriend_DEFAULT
	}
	return *p.IsFriend
}

var ConversationInfo_Category_DEFAULT string

func (p *ConversationInfo) GetCategory() (v string) {
	if !p.IsSetCategory() {
		return ConversationInfo_Category_DEFAULT
	}
	return *p.Category
}
func (p *ConversationInfo) SetConvId(val int64) {
	p.ConvId = val
}
func (p *ConversationInfo) SetParticipantA(val int64) {
	p.ParticipantA = val
}
func (p *ConversationInfo) SetParticipantB(val int64) {
	p.ParticipantB = val
}
func (p *ConversationInfo) SetUpdatedAt(val int64) {
	p.UpdatedAt = val
}
func (p *ConversationInfo) SetParticipantAName(val *string) {
	p.ParticipantAName = val
}
func (p *ConversationInfo) SetParticipantBName(val *string) {
	p.ParticipantBName = val
}
func (p *ConversationInfo) SetOriginType(val *string) {
	p.OriginType = val
}
func (p *ConversationInfo) SetOriginId(val *int64) {
	p.OriginId = val
}
func (p *ConversationInfo) SetPeerName(val *string) {
	p.PeerName = val
}
func (p *ConversationInfo) SetLastMessagePreview(val *string) {
	p.LastMessagePreview = val
}
func (p *ConversationInfo) SetUnreadCount(val *int32) {
	p.UnreadCount = val
}
func (p *ConversationInfo) SetMsgCount(val *int32) {
	p.MsgCount = val
}
func (p *ConversationInfo) SetRemark(val *string) {
	p.Remark = val
}
func (p *ConversationInfo) SetIsFriend(val *bool) {
	p.IsFriend = val
}
func (p *ConversationInfo) SetCategory(val *string) {
	p.Category = val
}

func (p *ConversationInfo) IsSetParticipantAName() bool {
	return p.ParticipantAName != nil
}

func (p *ConversationInfo) IsSetParticipantBName() bool {
	return p.ParticipantBName != nil
}

func (p *ConversationInfo) IsSetOriginType() bool {
	return p.OriginType != nil
}

func (p *ConversationInfo) IsSetOriginId() bool {
	return p.OriginId != nil
}

func (p *ConversationInfo) IsSetPeerName() bool {
	return p.PeerName != nil
}

func (p *ConversationInfo) IsSetLastMessagePreview() bool {
	return p.LastMessagePreview != nil
}

func (p *ConversationInfo) IsSetUnreadCount() bool {
	return p.UnreadCount != nil
}

func (p *ConversationInfo) IsSetMsgCount() bool {
	return p.MsgCount != nil
}

func (p *ConversationInfo) IsSetRemark() bool {
	return p.Remark != nil
}

func (p *ConversationInfo) IsSetIsFriend() bool {
	return p.IsFriend != nil
}

func (p *ConversationInfo) IsSetCategory() bool {
	return p.Category != nil
}

func (p *ConversationInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ConversationInfo(%+v)", *p)
}

var fieldIDToName_ConversationInfo = map[int16]string{
	1:  "conv_id",
	2:  "participant_a",
	3:  "participant_b",
	4:  "updated_at",
	6:  "participant_a_name",
	7:  "participant_b_name",
	8:  "origin_type",
	9:  "origin_id",
	10: "peer_name",
	11: "last_message_preview",
	12: "unread_count",
	13: "msg_count",
	14: "remark",
	15: "is_friend",
	16: "category",
}

type ListConversationsResp struct {
	Conversations []*ConversationInfo `thrift:"conversations,1,required" frugal:"1,required,list<ConversationInfo>" json:"conversations"`
	NextCursor    int64               `thrift:"next_cursor,2,required" frugal:"2,required,i64" json:"next_cursor"`
	BaseResp      *base.BaseResp      `thrift:"base_resp,255,required" frugal:"255,required,base.BaseResp" json:"base_resp"`
}

func NewListConversationsResp() *ListConversationsResp {
	return &ListConversationsResp{}
}

func (p *ListConversationsResp) InitDefault() {
}

func (p *ListConversationsResp) GetConversations() (v []*ConversationInfo) {
	return p.Conversations
}

func (p *ListConversationsResp) GetNextCursor() (v int64) {
	return p.NextCursor
}

var ListConversationsResp_BaseResp_DEFAULT *base.BaseResp

func (p *ListConversationsResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return ListConversationsResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *ListConversationsResp) SetConversations(val []*ConversationInfo) {
	p.Conversations = val
}
func (p *ListConversationsResp) SetNextCursor(val int64) {
	p.NextCursor = val
}
func (p *ListConversationsResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *ListConversationsResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *ListConversationsResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListConversationsResp(%+v)", *p)
}

var fieldIDToName_ListConversationsResp = map[int16]string{
	1:   "conversations",
	2:   "next_cursor",
	255: "base_resp",
}

type GetConvHistoryReq struct {
	AgentId int64  `thrift:"agent_id,1,required" frugal:"1,required,i64" json:"agent_id"`
	ConvId  int64  `thrift:"conv_id,2,required" frugal:"2,required,i64" json:"conv_id"`
	Cursor  *int64 `thrift:"cursor,3,optional" frugal:"3,optional,i64" json:"cursor,omitempty"`
	Limit   *int32 `thrift:"limit,4,optional" frugal:"4,optional,i32" json:"limit,omitempty"`
}

func NewGetConvHistoryReq() *GetConvHistoryReq {
	return &GetConvHistoryReq{}
}

func (p *GetConvHistoryReq) InitDefault() {
}

func (p *GetConvHistoryReq) GetAgentId() (v int64) {
	return p.AgentId
}

func (p *GetConvHistoryReq) GetConvId() (v int64) {
	return p.ConvId
}

var GetConvHistoryReq_Cursor_DEFAULT int64

func (p *GetConvHistoryReq) GetCursor() (v int64) {
	if !p.IsSetCursor() {
		return GetConvHistoryReq_Cursor_DEFAULT
	}
	return *p.Cursor
}

var GetConvHistoryReq_Limit_DEFAULT int32

func (p *GetConvHistoryReq) GetLimit() (v int32) {
	if !p.IsSetLimit() {
		return GetConvHistoryReq_Limit_DEFAULT
	}
	return *p.Limit
}
func (p *GetConvHistoryReq) SetAgentId(val int64) {
	p.AgentId = val
}
func (p *GetConvHistoryReq) SetConvId(val int64) {
	p.ConvId = val
}
func (p *GetConvHistoryReq) SetCursor(val *int64) {
	p.Cursor = val
}
func (p *GetConvHistoryReq) SetLimit(val *int32) {
	p.Limit = val
}

func (p *GetConvHistoryReq) IsSetCursor() bool {
	return p.Cursor != nil
}

func (p *GetConvHistoryReq) IsSetLimit() bool {
	return p.Limit != nil
}

func (p *GetConvHistoryReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetConvHistoryReq(%+v)", *p)
}

var fieldIDToName_GetConvHistoryReq = map[int16]string{
	1: "agent_id",
	2: "conv_id",
	3: "cursor",
	4: "limit",
}

type GetConvHistoryResp struct {
	Messages   []*PMMessage   `thrift:"messages,1,required" frugal:"1,required,list<PMMessage>" json:"messages"`
	NextCursor int64          `thrift:"next_cursor,2,required" frugal:"2,required,i64" json:"next_cursor"`
	BaseResp   *base.BaseResp `thrift:"base_resp,255,required" frugal:"255,required,base.BaseResp" json:"base_resp"`
}

func NewGetConvHistoryResp() *GetConvHistoryResp {
	return &GetConvHistoryResp{}
}

func (p *GetConvHistoryResp) InitDefault() {
}

func (p *GetConvHistoryResp) GetMessages() (v []*PMMessage) {
	return p.Messages
}

func (p *GetConvHistoryResp) GetNextCursor() (v int64) {
	return p.NextCursor
}

var GetConvHistoryResp_BaseResp_DEFAULT *base.BaseResp

func (p *GetConvHistoryResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return GetConvHistoryResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *GetConvHistoryResp) SetMessages(val []*PMMessage) {
	p.Messages = val
}
func (p *GetConvHistoryResp) SetNextCursor(val int64) {
	p.NextCursor = val
}
func (p *GetConvHistoryResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *GetConvHistoryResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *GetConvHistoryResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetConvHistoryResp(%+v)", *p)
}

var fieldIDToName_GetConvHistoryResp = map[int16]string{
	1:   "messages",
	2:   "next_cursor",
	255: "base_resp",
}

type CloseConvReq struct {
	AgentId int64 `thrift:"agent_id,1,required" frugal:"1,required,i64" json:"agent_id"`
	ConvId  int64 `thrift:"conv_id,2,required" frugal:"2,required,i64" json:"conv_id"`
}

func NewCloseConvReq() *CloseConvReq {
	return &CloseConvReq{}
}

func (p *CloseConvReq) InitDefault() {
}

func (p *CloseConvReq) GetAgentId() (v int64) {
	return p.AgentId
}

func (p *CloseConvReq) GetConvId() (v int64) {
	return p.ConvId
}
func (p *CloseConvReq) SetAgentId(val int64) {
	p.AgentId = val
}
func (p *CloseConvReq) SetConvId(val int64) {
	p.ConvId = val
}

func (p *CloseConvReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CloseConvReq(%+v)", *p)
}

var fieldIDToName_CloseConvReq = map[int16]string{
	1: "agent_id",
	2: "conv_id",
}

type CloseConvResp struct {
	BaseResp *base.BaseResp `thrift:"base_resp,255,required" frugal:"255,required,base.BaseResp" json:"base_resp"`
}

func NewCloseConvResp() *CloseConvResp {
	return &CloseConvResp{}
}

func (p *CloseConvResp) InitDefault() {
}

var CloseConvResp_BaseResp_DEFAULT *base.BaseResp

func (p *CloseConvResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return CloseConvResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *CloseConvResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *CloseConvResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *CloseConvResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CloseConvResp(%+v)", *p)
}

var fieldIDToName_CloseConvResp = map[int16]string{
	255: "base_resp",
}

type SendFriendRequestReq struct {
	FromUid  int64   `thrift:"from_uid,1,required" frugal:"1,required,i64" json:"from_uid"`
	ToUid    int64   `thrift:"to_uid,2,required" frugal:"2,required,i64" json:"to_uid"`
	Greeting *string `thrift:"greeting,3,optional" frugal:"3,optional,string" json:"greeting,omitempty"`
	Remark   *string `thrift:"remark,4,optional" frugal:"4,optional,string" json:"remark,omitempty"`
}

func NewSendFriendRequestReq() *SendFriendRequestReq {
	return &SendFriendRequestReq{}
}

func (p *SendFriendRequestReq) InitDefault() {
}

func (p *SendFriendRequestReq) GetFromUid() (v int64) {
	return p.FromUid
}

func (p *SendFriendRequestReq) GetToUid() (v int64) {
	return p.ToUid
}

var SendFriendRequestReq_Greeting_DEFAULT string

func (p *SendFriendRequestReq) GetGreeting() (v string) {
	if !p.IsSetGreeting() {
		return SendFriendRequestReq_Greeting_DEFAULT
	}
	return *p.Greeting
}

var SendFriendRequestReq_Remark_DEFAULT string

func (p *SendFriendRequestReq) GetRemark() (v string) {
	if !p.IsSetRemark() {
		return SendFriendRequestReq_Remark_DEFAULT
	}
	return *p.Remark
}
func (p *SendFriendRequestReq) SetFromUid(val int64) {
	p.FromUid = val
}
func (p *SendFriendRequestReq) SetToUid(val int64) {
	p.ToUid = val
}
func (p *SendFriendRequestReq) SetGreeting(val *string) {
	p.Greeting = val
}
func (p *SendFriendRequestReq) SetRemark(val *string) {
	p.Remark = val
}

func (p *SendFriendRequestReq) IsSetGreeting() bool {
	return p.Greeting != nil
}

func (p *SendFriendRequestReq) IsSetRemark() bool {
	return p.Remark != nil
}

func (p *SendFriendRequestReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SendFriendRequestReq(%+v)", *p)
}

var fieldIDToName_SendFriendRequestReq = map[int16]string{
	1: "from_uid",
	2: "to_uid",
	3: "greeting",
	4: "remark",
}

type SendFriendRequestResp struct {
	RequestId int64          `thrift:"request_id,1,required" frugal:"1,required,i64" json:"request_id"`
	BaseResp  *base.BaseResp `thrift:"base_resp,255,required" frugal:"255,required,base.BaseResp" json:"base_resp"`
}

func NewSendFriendRequestResp() *SendFriendRequestResp {
	return &SendFriendRequestResp{}
}

func (p *SendFriendRequestResp) InitDefault() {
}

func (p *SendFriendRequestResp) GetRequestId() (v int64) {
	return p.RequestId
}

var SendFriendRequestResp_BaseResp_DEFAULT *base.BaseResp

func (p *SendFriendRequestResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return SendFriendRequestResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *SendFriendRequestResp) SetRequestId(val int64) {
	p.RequestId = val
}
func (p *SendFriendRequestResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *SendFriendRequestResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *SendFriendRequestResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SendFriendRequestResp(%+v)", *p)
}

var fieldIDToName_SendFriendRequestResp = map[int16]string{
	1:   "request_id",
	255: "base_resp",
}

type HandleFriendRequestReq struct {
	AgentId   int64               `thrift:"agent_id,1,required" frugal:"1,required,i64" json:"agent_id"`
	RequestId int64               `thrift:"request_id,2,required" frugal:"2,required,i64" json:"request_id"`
	Action    FriendRequestAction `thrift:"action,3,required" frugal:"3,required,FriendRequestAction" json:"action"`
	Remark    *string             `thrift:"remark,4,optional" frugal:"4,optional,string" json:"remark,omitempty"`
	Reason    *string             `thrift:"reason,5,optional" frugal:"5,optional,string" json:"reason,omitempty"`
}

func NewHandleFriendRequestReq() *HandleFriendRequestReq {
	return &HandleFriendRequestReq{}
}

func (p *HandleFriendRequestReq) InitDefault() {
}

func (p *HandleFriendRequestReq) GetAgentId() (v int64) {
	return p.AgentId
}

func (p *HandleFriendRequestReq) GetRequestId() (v int64) {
	return p.RequestId
}

func (p *HandleFriendRequestReq) GetAction() (v FriendRequestAction) {
	return p.Action
}

var HandleFriendRequestReq_Remark_DEFAULT string

func (p *HandleFriendRequestReq) GetRemark() (v string) {
	if !p.IsSetRemark() {
		return HandleFriendRequestReq_Remark_DEFAULT
	}
	return *p.Remark
}

var HandleFriendRequestReq_Reason_DEFAULT string

func (p *HandleFriendRequestReq) GetReason() (v string) {
	if !p.IsSetReason() {
		return HandleFriendRequestReq_Reason_DEFAULT
	}
	return *p.Reason
}
func (p *HandleFriendRequestReq) SetAgentId(val int64) {
	p.AgentId = val
}
func (p *HandleFriendRequestReq) SetRequestId(val int64) {
	p.RequestId = val
}
func (p *HandleFriendRequestReq) SetAction(val FriendRequestAction) {
	p.Action = val
}
func (p *HandleFriendRequestReq) SetRemark(val *string) {
	p.Remark = val
}
func (p *HandleFriendRequestReq) SetReason(val *string) {
	p.Reason = val
}

func (p *HandleFriendRequestReq) IsSetRemark() bool {
	return p.Remark != nil
}

func (p *HandleFriendRequestReq) IsSetReason() bool {
	return p.Reason != nil
}

func (p *HandleFriendRequestReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("HandleFriendRequestReq(%+v)", *p)
}

var fieldIDToName_HandleFriendRequestReq = map[int16]string{
	1: "agent_id",
	2: "request_id",
	3: "action",
	4: "remark",
	5: "reason",
}

type HandleFriendRequestResp struct {
	BaseResp *base.BaseResp `thrift:"base_resp,255,required" frugal:"255,required,base.BaseResp" json:"base_resp"`
}

func NewHandleFriendRequestResp() *HandleFriendRequestResp {
	return &HandleFriendRequestResp{}
}

func (p *HandleFriendRequestResp) InitDefault() {
}

var HandleFriendRequestResp_BaseResp_DEFAULT *base.BaseResp

func (p *HandleFriendRequestResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return HandleFriendRequestResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *HandleFriendRequestResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *HandleFriendRequestResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *HandleFriendRequestResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("HandleFriendRequestResp(%+v)", *p)
}

var fieldIDToName_HandleFriendRequestResp = map[int16]string{
	255: "base_resp",
}

type UpdateFriendRemarkReq struct {
	AgentId   int64  `thrift:"agent_id,1,required" frugal:"1,required,i64" json:"agent_id"`
	FriendUid int64  `thrift:"friend_uid,2,required" frugal:"2,required,i64" json:"friend_uid"`
	Remark    string `thrift:"remark,3,required" frugal:"3,required,string" json:"remark"`
}

func NewUpdateFriendRemarkReq() *UpdateFriendRemarkReq {
	return &UpdateFriendRemarkReq{}
}

func (p *UpdateFriendRemarkReq) InitDefault() {
}

func (p *UpdateFriendRemarkReq) GetAgentId() (v int64) {
	return p.AgentId
}

func (p *UpdateFriendRemarkReq) GetFriendUid() (v int64) {
	return p.FriendUid
}

func (p *UpdateFriendRemarkReq) GetRemark() (v string) {
	return p.Remark
}
func (p *UpdateFriendRemarkReq) SetAgentId(val int64) {
	p.AgentId = val
}
func (p *UpdateFriendRemarkReq) SetFriendUid(val int64) {
	p.FriendUid = val
}
func (p *UpdateFriendRemarkReq) SetRemark(val string) {
	p.Remark = val
}

func (p *UpdateFriendRemarkReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateFriendRemarkReq(%+v)", *p)
}

var fieldIDToName_UpdateFriendRemarkReq = map[int16]string{
	1: "agent_id",
	2: "friend_uid",
	3: "remark",
}

type UpdateFriendRemarkResp struct {
	BaseResp *base.BaseResp `thrift:"base_resp,255,required" frugal:"255,required,base.BaseResp" json:"base_resp"`
}

func NewUpdateFriendRemarkResp() *UpdateFriendRemarkResp {
	return &UpdateFriendRemarkResp{}
}

func (p *UpdateFriendRemarkResp) InitDefault() {
}

var UpdateFriendRemarkResp_BaseResp_DEFAULT *base.BaseResp

func (p *UpdateFriendRemarkResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return UpdateFriendRemarkResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *UpdateFriendRemarkResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *UpdateFriendRemarkResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *UpdateFriendRemarkResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateFriendRemarkResp(%+v)", *p)
}

var fieldIDToName_UpdateFriendRemarkResp = map[int16]string{
	255: "base_resp",
}

type BlockUserReq struct {
	FromUid int64   `thrift:"from_uid,1,required" frugal:"1,required,i64" json:"from_uid"`
	ToUid   int64   `thrift:"to_uid,2,required" frugal:"2,required,i64" json:"to_uid"`
	Remark  *string `thrift:"remark,3,optional" frugal:"3,optional,string" json:"remark,omitempty"`
}

func NewBlockUserReq() *BlockUserReq {
	return &BlockUserReq{}
}

func (p *BlockUserReq) InitDefault() {
}

func (p *BlockUserReq) GetFromUid() (v int64) {
	return p.FromUid
}

func (p *BlockUserReq) GetToUid() (v int64) {
	return p.ToUid
}

var BlockUserReq_Remark_DEFAULT string

func (p *BlockUserReq) GetRemark() (v string) {
	if !p.IsSetRemark() {
		return BlockUserReq_Remark_DEFAULT
	}
	return *p.Remark
}
func (p *BlockUserReq) SetFromUid(val int64) {
	p.FromUid = val
}
func (p *BlockUserReq) SetToUid(val int64) {
	p.ToUid = val
}
func (p *BlockUserReq) SetRemark(val *string) {
	p.Remark = val
}

func (p *BlockUserReq) IsSetRemark() bool {
	return p.Remark != nil
}

func (p *BlockUserReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BlockUserReq(%+v)", *p)
}

var fieldIDToName_BlockUserReq = map[int16]string{
	1: "from_uid",
	2: "to_uid",
	3: "remark",
}

type BlockUserResp struct {
	BaseResp *base.BaseResp `thrift:"base_resp,255,required" frugal:"255,required,base.BaseResp" json:"base_resp"`
}

func NewBlockUserResp() *BlockUserResp {
	return &BlockUserResp{}
}

func (p *BlockUserResp) InitDefault() {
}

var BlockUserResp_BaseResp_DEFAULT *base.BaseResp

func (p *BlockUserResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return BlockUserResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *BlockUserResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *BlockUserResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *BlockUserResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BlockUserResp(%+v)", *p)
}

var fieldIDToName_BlockUserResp = map[int16]string{
	255: "base_resp",
}

type UnblockUserReq struct {
	FromUid int64 `thrift:"from_uid,1,required" frugal:"1,required,i64" json:"from_uid"`
	ToUid   int64 `thrift:"to_uid,2,required" frugal:"2,required,i64" json:"to_uid"`
}

func NewUnblockUserReq() *UnblockUserReq {
	return &UnblockUserReq{}
}

func (p *UnblockUserReq) InitDefault() {
}

func (p *UnblockUserReq) GetFromUid() (v int64) {
	return p.FromUid
}

func (p *UnblockUserReq) GetToUid() (v int64) {
	return p.ToUid
}
func (p *UnblockUserReq) SetFromUid(val int64) {
	p.FromUid = val
}
func (p *UnblockUserReq) SetToUid(val int64) {
	p.ToUid = val
}

func (p *UnblockUserReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UnblockUserReq(%+v)", *p)
}

var fieldIDToName_UnblockUserReq = map[int16]string{
	1: "from_uid",
	2: "to_uid",
}

type UnblockUserResp struct {
	BaseResp *base.BaseResp `thrift:"base_resp,255,required" frugal:"255,required,base.BaseResp" json:"base_resp"`
}

func NewUnblockUserResp() *UnblockUserResp {
	return &UnblockUserResp{}
}

func (p *UnblockUserResp) InitDefault() {
}

var UnblockUserResp_BaseResp_DEFAULT *base.BaseResp

func (p *UnblockUserResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return UnblockUserResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *UnblockUserResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *UnblockUserResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *UnblockUserResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UnblockUserResp(%+v)", *p)
}

var fieldIDToName_UnblockUserResp = map[int16]string{
	255: "base_resp",
}

type UnfriendReq struct {
	FromUid int64 `thrift:"from_uid,1,required" frugal:"1,required,i64" json:"from_uid"`
	ToUid   int64 `thrift:"to_uid,2,required" frugal:"2,required,i64" json:"to_uid"`
}

func NewUnfriendReq() *UnfriendReq {
	return &UnfriendReq{}
}

func (p *UnfriendReq) InitDefault() {
}

func (p *UnfriendReq) GetFromUid() (v int64) {
	return p.FromUid
}

func (p *UnfriendReq) GetToUid() (v int64) {
	return p.ToUid
}
func (p *UnfriendReq) SetFromUid(val int64) {
	p.FromUid = val
}
func (p *UnfriendReq) SetToUid(val int64) {
	p.ToUid = val
}

func (p *UnfriendReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UnfriendReq(%+v)", *p)
}

var fieldIDToName_UnfriendReq = map[int16]string{
	1: "from_uid",
	2: "to_uid",
}

type UnfriendResp struct {
	BaseResp *base.BaseResp `thrift:"base_resp,255,required" frugal:"255,required,base.BaseResp" json:"base_resp"`
}

func NewUnfriendResp() *UnfriendResp {
	return &UnfriendResp{}
}

func (p *UnfriendResp) InitDefault() {
}

var UnfriendResp_BaseResp_DEFAULT *base.BaseResp

func (p *UnfriendResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return UnfriendResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *UnfriendResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *UnfriendResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *UnfriendResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UnfriendResp(%+v)", *p)
}

var fieldIDToName_UnfriendResp = map[int16]string{
	255: "base_resp",
}

type ListFriendRequestsReq struct {
	AgentId   int64  `thrift:"agent_id,1,required" frugal:"1,required,i64" json:"agent_id"`
	Direction string `thrift:"direction,2,required" frugal:"2,required,string" json:"direction"`
	Cursor    *int64 `thrift:"cursor,3,optional" frugal:"3,optional,i64" json:"cursor,omitempty"`
	Limit     *int32 `thrift:"limit,4,optional" frugal:"4,optional,i32" json:"limit,omitempty"`
}

func NewListFriendRequestsReq() *ListFriendRequestsReq {
	return &ListFriendRequestsReq{}
}

func (p *ListFriendRequestsReq) InitDefault() {
}

func (p *ListFriendRequestsReq) GetAgentId() (v int64) {
	return p.AgentId
}

func (p *ListFriendRequestsReq) GetDirection() (v string) {
	return p.Direction
}

var ListFriendRequestsReq_Cursor_DEFAULT int64

func (p *ListFriendRequestsReq) GetCursor() (v int64) {
	if !p.IsSetCursor() {
		return ListFriendRequestsReq_Cursor_DEFAULT
	}
	return *p.Cursor
}

var ListFriendRequestsReq_Limit_DEFAULT int32

func (p *ListFriendRequestsReq) GetLimit() (v int32) {
	if !p.IsSetLimit() {
		return ListFriendRequestsReq_Limit_DEFAULT
	}
	return *p.Limit
}
func (p *ListFriendRequestsReq) SetAgentId(val int64) {
	p.AgentId = val
}
func (p *ListFriendRequestsReq) SetDirection(val string) {
	p.Direction = val
}
func (p *ListFriendRequestsReq) SetCursor(val *int64) {
	p.Cursor = val
}
func (p *ListFriendRequestsReq) SetLimit(val *int32) {
	p.Limit = val
}

func (p *ListFriendRequestsReq) IsSetCursor() bool {
	return p.Cursor != nil
}

func (p *ListFriendRequestsReq) IsSetLimit() bool {
	return p.Limit != nil
}

func (p *ListFriendRequestsReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListFriendRequestsReq(%+v)", *p)
}

var fieldIDToName_ListFriendRequestsReq = map[int16]string{
	1: "agent_id",
	2: "direction",
	3: "cursor",
	4: "limit",
}

type FriendRequestInfo struct {
	RequestId       int64   `thrift:"request_id,1,required" frugal:"1,required,i64" json:"request_id"`
	FromUid         int64   `thrift:"from_uid,2,required" frugal:"2,required,i64" json:"from_uid"`
	ToUid           int64   `thrift:"to_uid,3,required" frugal:"3,required,i64" json:"to_uid"`
	CreatedAt       int64   `thrift:"created_at,4,required" frugal:"4,required,i64" json:"created_at"`
	FromName        *string `thrift:"from_name,5,optional" frugal:"5,optional,string" json:"from_name,omitempty"`
	ToName          *string `thrift:"to_name,6,optional" frugal:"6,optional,string" json:"to_name,omitempty"`
	Greeting        *string `thrift:"greeting,7,optional" frugal:"7,optional,string" json:"greeting,omitempty"`
	FromIsOfficial  *bool   `thrift:"from_is_official,8,optional" frugal:"8,optional,bool" json:"from_is_official,omitempty"`
	FromShortId     *string `thrift:"from_short_id,9,optional" frugal:"9,optional,string" json:"from_short_id,omitempty"`
	ToShortId       *string `thrift:"to_short_id,10,optional" frugal:"10,optional,string" json:"to_short_id,omitempty"`
	FromDisplayName *string `thrift:"from_display_name,11,optional" frugal:"11,optional,string" json:"from_display_name,omitempty"`
	ToDisplayName   *string `thrift:"to_display_name,12,optional" frugal:"12,optional,string" json:"to_display_name,omitempty"`
}

func NewFriendRequestInfo() *FriendRequestInfo {
	return &FriendRequestInfo{}
}

func (p *FriendRequestInfo) InitDefault() {
}

func (p *FriendRequestInfo) GetRequestId() (v int64) {
	return p.RequestId
}

func (p *FriendRequestInfo) GetFromUid() (v int64) {
	return p.FromUid
}

func (p *FriendRequestInfo) GetToUid() (v int64) {
	return p.ToUid
}

func (p *FriendRequestInfo) GetCreatedAt() (v int64) {
	return p.CreatedAt
}

var FriendRequestInfo_FromName_DEFAULT string

func (p *FriendRequestInfo) GetFromName() (v string) {
	if !p.IsSetFromName() {
		return FriendRequestInfo_FromName_DEFAULT
	}
	return *p.FromName
}

var FriendRequestInfo_ToName_DEFAULT string

func (p *FriendRequestInfo) GetToName() (v string) {
	if !p.IsSetToName() {
		return FriendRequestInfo_ToName_DEFAULT
	}
	return *p.ToName
}

var FriendRequestInfo_Greeting_DEFAULT string

func (p *FriendRequestInfo) GetGreeting() (v string) {
	if !p.IsSetGreeting() {
		return FriendRequestInfo_Greeting_DEFAULT
	}
	return *p.Greeting
}

var FriendRequestInfo_FromIsOfficial_DEFAULT bool

func (p *FriendRequestInfo) GetFromIsOfficial() (v bool) {
	if !p.IsSetFromIsOfficial() {
		return FriendRequestInfo_FromIsOfficial_DEFAULT
	}
	return *p.FromIsOfficial
}

var FriendRequestInfo_FromShortId_DEFAULT string

func (p *FriendRequestInfo) GetFromShortId() (v string) {
	if !p.IsSetFromShortId() {
		return FriendRequestInfo_FromShortId_DEFAULT
	}
	return *p.FromShortId
}

var FriendRequestInfo_ToShortId_DEFAULT string

func (p *FriendRequestInfo) GetToShortId() (v string) {
	if !p.IsSetToShortId() {
		return FriendRequestInfo_ToShortId_DEFAULT
	}
	return *p.ToShortId
}

var FriendRequestInfo_FromDisplayName_DEFAULT string

func (p *FriendRequestInfo) GetFromDisplayName() (v string) {
	if !p.IsSetFromDisplayName() {
		return FriendRequestInfo_FromDisplayName_DEFAULT
	}
	return *p.FromDisplayName
}

var FriendRequestInfo_ToDisplayName_DEFAULT string

func (p *FriendRequestInfo) GetToDisplayName() (v string) {
	if !p.IsSetToDisplayName() {
		return FriendRequestInfo_ToDisplayName_DEFAULT
	}
	return *p.ToDisplayName
}
func (p *FriendRequestInfo) SetRequestId(val int64) {
	p.RequestId = val
}
func (p *FriendRequestInfo) SetFromUid(val int64) {
	p.FromUid = val
}
func (p *FriendRequestInfo) SetToUid(val int64) {
	p.ToUid = val
}
func (p *FriendRequestInfo) SetCreatedAt(val int64) {
	p.CreatedAt = val
}
func (p *FriendRequestInfo) SetFromName(val *string) {
	p.FromName = val
}
func (p *FriendRequestInfo) SetToName(val *string) {
	p.ToName = val
}
func (p *FriendRequestInfo) SetGreeting(val *string) {
	p.Greeting = val
}
func (p *FriendRequestInfo) SetFromIsOfficial(val *bool) {
	p.FromIsOfficial = val
}
func (p *FriendRequestInfo) SetFromShortId(val *string) {
	p.FromShortId = val
}
func (p *FriendRequestInfo) SetToShortId(val *string) {
	p.ToShortId = val
}
func (p *FriendRequestInfo) SetFromDisplayName(val *string) {
	p.FromDisplayName = val
}
func (p *FriendRequestInfo) SetToDisplayName(val *string) {
	p.ToDisplayName = val
}

func (p *FriendRequestInfo) IsSetFromName() bool {
	return p.FromName != nil
}

func (p *FriendRequestInfo) IsSetToName() bool {
	return p.ToName != nil
}

func (p *FriendRequestInfo) IsSetGreeting() bool {
	return p.Greeting != nil
}

func (p *FriendRequestInfo) IsSetFromIsOfficial() bool {
	return p.FromIsOfficial != nil
}

func (p *FriendRequestInfo) IsSetFromShortId() bool {
	return p.FromShortId != nil
}

func (p *FriendRequestInfo) IsSetToShortId() bool {
	return p.ToShortId != nil
}

func (p *FriendRequestInfo) IsSetFromDisplayName() bool {
	return p.FromDisplayName != nil
}

func (p *FriendRequestInfo) IsSetToDisplayName() bool {
	return p.ToDisplayName != nil
}

func (p *FriendRequestInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FriendRequestInfo(%+v)", *p)
}

var fieldIDToName_FriendRequestInfo = map[int16]string{
	1:  "request_id",
	2:  "from_uid",
	3:  "to_uid",
	4:  "created_at",
	5:  "from_name",
	6:  "to_name",
	7:  "greeting",
	8:  "from_is_official",
	9:  "from_short_id",
	10: "to_short_id",
	11: "from_display_name",
	12: "to_display_name",
}

type ListFriendRequestsResp struct {
	Requests   []*FriendRequestInfo `thrift:"requests,1,required" frugal:"1,required,list<FriendRequestInfo>" json:"requests"`
	NextCursor int64                `thrift:"next_cursor,2,required" frugal:"2,required,i64" json:"next_cursor"`
	HasMore    *bool                `thrift:"has_more,3,optional" frugal:"3,optional,bool" json:"has_more,omitempty"`
	BaseResp   *base.BaseResp       `thrift:"base_resp,255,required" frugal:"255,required,base.BaseResp" json:"base_resp"`
}

func NewListFriendRequestsResp() *ListFriendRequestsResp {
	return &ListFriendRequestsResp{}
}

func (p *ListFriendRequestsResp) InitDefault() {
}

func (p *ListFriendRequestsResp) GetRequests() (v []*FriendRequestInfo) {
	return p.Requests
}

func (p *ListFriendRequestsResp) GetNextCursor() (v int64) {
	return p.NextCursor
}

var ListFriendRequestsResp_HasMore_DEFAULT bool

func (p *ListFriendRequestsResp) GetHasMore() (v bool) {
	if !p.IsSetHasMore() {
		return ListFriendRequestsResp_HasMore_DEFAULT
	}
	return *p.HasMore
}

var ListFriendRequestsResp_BaseResp_DEFAULT *base.BaseResp

func (p *ListFriendRequestsResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return ListFriendRequestsResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *ListFriendRequestsResp) SetRequests(val []*FriendRequestInfo) {
	p.Requests = val
}
func (p *ListFriendRequestsResp) SetNextCursor(val int64) {
	p.NextCursor = val
}
func (p *ListFriendRequestsResp) SetHasMore(val *bool) {
	p.HasMore = val
}
func (p *ListFriendRequestsResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *ListFriendRequestsResp) IsSetHasMore() bool {
	return p.HasMore != nil
}

func (p *ListFriendRequestsResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *ListFriendRequestsResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListFriendRequestsResp(%+v)", *p)
}

var fieldIDToName_ListFriendRequestsResp = map[int16]string{
	1:   "requests",
	2:   "next_cursor",
	3:   "has_more",
	255: "base_resp",
}

type ListFriendsReq struct {
	AgentId int64  `thrift:"agent_id,1,required" frugal:"1,required,i64" json:"agent_id"`
	Cursor  *int64 `thrift:"cursor,2,optional" frugal:"2,optional,i64" json:"cursor,omitempty"`
	Limit   *int32 `thrift:"limit,3,optional" frugal:"3,optional,i32" json:"limit,omitempty"`
}

func NewListFriendsReq() *ListFriendsReq {
	return &ListFriendsReq{}
}

func (p *ListFriendsReq) InitDefault() {
}

func (p *ListFriendsReq) GetAgentId() (v int64) {
	return p.AgentId
}

var ListFriendsReq_Cursor_DEFAULT int64

func (p *ListFriendsReq) GetCursor() (v int64) {
	if !p.IsSetCursor() {
		return ListFriendsReq_Cursor_DEFAULT
	}
	return *p.Cursor
}

var ListFriendsReq_Limit_DEFAULT int32

func (p *ListFriendsReq) GetLimit() (v int32) {
	if !p.IsSetLimit() {
		return ListFriendsReq_Limit_DEFAULT
	}
	return *p.Limit
}
func (p *ListFriendsReq) SetAgentId(val int64) {
	p.AgentId = val
}
func (p *ListFriendsReq) SetCursor(val *int64) {
	p.Cursor = val
}
func (p *ListFriendsReq) SetLimit(val *int32) {
	p.Limit = val
}

func (p *ListFriendsReq) IsSetCursor() bool {
	return p.Cursor != nil
}

func (p *ListFriendsReq) IsSetLimit() bool {
	return p.Limit != nil
}

func (p *ListFriendsReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListFriendsReq(%+v)", *p)
}

var fieldIDToName_ListFriendsReq = map[int16]string{
	1: "agent_id",
	2: "cursor",
	3: "limit",
}

type FriendInfo struct {
	AgentId       int64   `thrift:"agent_id,1,required" frugal:"1,required,i64" json:"agent_id"`
	AgentName     string  `thrift:"agent_name,2,required" frugal:"2,required,string" json:"agent_name"`
	FriendSince   int64   `thrift:"friend_since,3,required" frugal:"3,required,i64" json:"friend_since"`
	Remark        *string `thrift:"remark,4,optional" frugal:"4,optional,string" json:"remark,omitempty"`
	Bio           *string `thrift:"bio,5,optional" frugal:"5,optional,string" json:"bio,omitempty"`
	LastDmPreview *string `thrift:"last_dm_preview,6,optional" frugal:"6,optional,string" json:"last_dm_preview,omitempty"`
	LastDmTime    *int64  `thrift:"last_dm_time,7,optional" frugal:"7,optional,i64" json:"last_dm_time,omitempty"`
	ShortId       *string `thrift:"short_id,8,optional" frugal:"8,optional,string" json:"short_id,omitempty"`
	DisplayName   *string `thrift:"display_name,9,optional" frugal:"9,optional,string" json:"display_name,omitempty"`
}

func NewFriendInfo() *FriendInfo {
	return &FriendInfo{}
}

func (p *FriendInfo) InitDefault() {
}

func (p *FriendInfo) GetAgentId() (v int64) {
	return p.AgentId
}

func (p *FriendInfo) GetAgentName() (v string) {
	return p.AgentName
}

func (p *FriendInfo) GetFriendSince() (v int64) {
	return p.FriendSince
}

var FriendInfo_Remark_DEFAULT string

func (p *FriendInfo) GetRemark() (v string) {
	if !p.IsSetRemark() {
		return FriendInfo_Remark_DEFAULT
	}
	return *p.Remark
}

var FriendInfo_Bio_DEFAULT string

func (p *FriendInfo) GetBio() (v string) {
	if !p.IsSetBio() {
		return FriendInfo_Bio_DEFAULT
	}
	return *p.Bio
}

var FriendInfo_LastDmPreview_DEFAULT string

func (p *FriendInfo) GetLastDmPreview() (v string) {
	if !p.IsSetLastDmPreview() {
		return FriendInfo_LastDmPreview_DEFAULT
	}
	return *p.LastDmPreview
}

var FriendInfo_LastDmTime_DEFAULT int64

func (p *FriendInfo) GetLastDmTime() (v int64) {
	if !p.IsSetLastDmTime() {
		return FriendInfo_LastDmTime_DEFAULT
	}
	return *p.LastDmTime
}

var FriendInfo_ShortId_DEFAULT string

func (p *FriendInfo) GetShortId() (v string) {
	if !p.IsSetShortId() {
		return FriendInfo_ShortId_DEFAULT
	}
	return *p.ShortId
}

var FriendInfo_DisplayName_DEFAULT string

func (p *FriendInfo) GetDisplayName() (v string) {
	if !p.IsSetDisplayName() {
		return FriendInfo_DisplayName_DEFAULT
	}
	return *p.DisplayName
}
func (p *FriendInfo) SetAgentId(val int64) {
	p.AgentId = val
}
func (p *FriendInfo) SetAgentName(val string) {
	p.AgentName = val
}
func (p *FriendInfo) SetFriendSince(val int64) {
	p.FriendSince = val
}
func (p *FriendInfo) SetRemark(val *string) {
	p.Remark = val
}
func (p *FriendInfo) SetBio(val *string) {
	p.Bio = val
}
func (p *FriendInfo) SetLastDmPreview(val *string) {
	p.LastDmPreview = val
}
func (p *FriendInfo) SetLastDmTime(val *int64) {
	p.LastDmTime = val
}
func (p *FriendInfo) SetShortId(val *string) {
	p.ShortId = val
}
func (p *FriendInfo) SetDisplayName(val *string) {
	p.DisplayName = val
}

func (p *FriendInfo) IsSetRemark() bool {
	return p.Remark != nil
}

func (p *FriendInfo) IsSetBio() bool {
	return p.Bio != nil
}

func (p *FriendInfo) IsSetLastDmPreview() bool {
	return p.LastDmPreview != nil
}

func (p *FriendInfo) IsSetLastDmTime() bool {
	return p.LastDmTime != nil
}

func (p *FriendInfo) IsSetShortId() bool {
	return p.ShortId != nil
}

func (p *FriendInfo) IsSetDisplayName() bool {
	return p.DisplayName != nil
}

func (p *FriendInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("FriendInfo(%+v)", *p)
}

var fieldIDToName_FriendInfo = map[int16]string{
	1: "agent_id",
	2: "agent_name",
	3: "friend_since",
	4: "remark",
	5: "bio",
	6: "last_dm_preview",
	7: "last_dm_time",
	8: "short_id",
	9: "display_name",
}

type ListFriendsResp struct {
	Friends    []*FriendInfo  `thrift:"friends,1,required" frugal:"1,required,list<FriendInfo>" json:"friends"`
	NextCursor int64          `thrift:"next_cursor,2,required" frugal:"2,required,i64" json:"next_cursor"`
	Total      *int64         `thrift:"total,3,optional" frugal:"3,optional,i64" json:"total,omitempty"`
	BaseResp   *base.BaseResp `thrift:"base_resp,255,required" frugal:"255,required,base.BaseResp" json:"base_resp"`
}

func NewListFriendsResp() *ListFriendsResp {
	return &ListFriendsResp{}
}

func (p *ListFriendsResp) InitDefault() {
}

func (p *ListFriendsResp) GetFriends() (v []*FriendInfo) {
	return p.Friends
}

func (p *ListFriendsResp) GetNextCursor() (v int64) {
	return p.NextCursor
}

var ListFriendsResp_Total_DEFAULT int64

func (p *ListFriendsResp) GetTotal() (v int64) {
	if !p.IsSetTotal() {
		return ListFriendsResp_Total_DEFAULT
	}
	return *p.Total
}

var ListFriendsResp_BaseResp_DEFAULT *base.BaseResp

func (p *ListFriendsResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return ListFriendsResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *ListFriendsResp) SetFriends(val []*FriendInfo) {
	p.Friends = val
}
func (p *ListFriendsResp) SetNextCursor(val int64) {
	p.NextCursor = val
}
func (p *ListFriendsResp) SetTotal(val *int64) {
	p.Total = val
}
func (p *ListFriendsResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *ListFriendsResp) IsSetTotal() bool {
	return p.Total != nil
}

func (p *ListFriendsResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *ListFriendsResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListFriendsResp(%+v)", *p)
}

var fieldIDToName_ListFriendsResp = map[int16]string{
	1:   "friends",
	2:   "next_cursor",
	3:   "total",
	255: "base_resp",
}

type GetUnreadCountReq struct {
	AgentId int64 `thrift:"agent_id,1,required" frugal:"1,required,i64" json:"agent_id"`
}

func NewGetUnreadCountReq() *GetUnreadCountReq {
	return &GetUnreadCountReq{}
}

func (p *GetUnreadCountReq) InitDefault() {
}

func (p *GetUnreadCountReq) GetAgentId() (v int64) {
	return p.AgentId
}
func (p *GetUnreadCountReq) SetAgentId(val int64) {
	p.AgentId = val
}

func (p *GetUnreadCountReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUnreadCountReq(%+v)", *p)
}

var fieldIDToName_GetUnreadCountReq = map[int16]string{
	1: "agent_id",
}

type GetUnreadCountResp struct {
	Count                 int64          `thrift:"count,1,required" frugal:"1,required,i64" json:"count"`
	CountBroadcast        *int64         `thrift:"count_broadcast,2,optional" frugal:"2,optional,i64" json:"count_broadcast,omitempty"`
	CountFriend           *int64         `thrift:"count_friend,3,optional" frugal:"3,optional,i64" json:"count_friend,omitempty"`
	CountBroadcastComment *int64         `thrift:"count_broadcast_comment,4,optional" frugal:"4,optional,i64" json:"count_broadcast_comment,omitempty"`
	CountNonFriend        *int64         `thrift:"count_non_friend,5,optional" frugal:"5,optional,i64" json:"count_non_friend,omitempty"`
	BaseResp              *base.BaseResp `thrift:"base_resp,255,required" frugal:"255,required,base.BaseResp" json:"base_resp"`
}

func NewGetUnreadCountResp() *GetUnreadCountResp {
	return &GetUnreadCountResp{}
}

func (p *GetUnreadCountResp) InitDefault() {
}

func (p *GetUnreadCountResp) GetCount() (v int64) {
	return p.Count
}

var GetUnreadCountResp_CountBroadcast_DEFAULT int64

func (p *GetUnreadCountResp) GetCountBroadcast() (v int64) {
	if !p.IsSetCountBroadcast() {
		return GetUnreadCountResp_CountBroadcast_DEFAULT
	}
	return *p.CountBroadcast
}

var GetUnreadCountResp_CountFriend_DEFAULT int64

func (p *GetUnreadCountResp) GetCountFriend() (v int64) {
	if !p.IsSetCountFriend() {
		return GetUnreadCountResp_CountFriend_DEFAULT
	}
	return *p.CountFriend
}

var GetUnreadCountResp_CountBroadcastComment_DEFAULT int64

func (p *GetUnreadCountResp) GetCountBroadcastComment() (v int64) {
	if !p.IsSetCountBroadcastComment() {
		return GetUnreadCountResp_CountBroadcastComment_DEFAULT
	}
	return *p.CountBroadcastComment
}

var GetUnreadCountResp_CountNonFriend_DEFAULT int64

func (p *GetUnreadCountResp) GetCountNonFriend() (v int64) {
	if !p.IsSetCountNonFriend() {
		return GetUnreadCountResp_CountNonFriend_DEFAULT
	}
	return *p.CountNonFriend
}

var GetUnreadCountResp_BaseResp_DEFAULT *base.BaseResp

func (p *GetUnreadCountResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return GetUnreadCountResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *GetUnreadCountResp) SetCount(val int64) {
	p.Count = val
}
func (p *GetUnreadCountResp) SetCountBroadcast(val *int64) {
	p.CountBroadcast = val
}
func (p *GetUnreadCountResp) SetCountFriend(val *int64) {
	p.CountFriend = val
}
func (p *GetUnreadCountResp) SetCountBroadcastComment(val *int64) {
	p.CountBroadcastComment = val
}
func (p *GetUnreadCountResp) SetCountNonFriend(val *int64) {
	p.CountNonFriend = val
}
func (p *GetUnreadCountResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *GetUnreadCountResp) IsSetCountBroadcast() bool {
	return p.CountBroadcast != nil
}

func (p *GetUnreadCountResp) IsSetCountFriend() bool {
	return p.CountFriend != nil
}

func (p *GetUnreadCountResp) IsSetCountBroadcastComment() bool {
	return p.CountBroadcastComment != nil
}

func (p *GetUnreadCountResp) IsSetCountNonFriend() bool {
	return p.CountNonFriend != nil
}

func (p *GetUnreadCountResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *GetUnreadCountResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUnreadCountResp(%+v)", *p)
}

var fieldIDToName_GetUnreadCountResp = map[int16]string{
	1:   "count",
	2:   "count_broadcast",
	3:   "count_friend",
	4:   "count_broadcast_comment",
	5:   "count_non_friend",
	255: "base_resp",
}

type MarkConvReadReq struct {
	AgentId int64 `thrift:"agent_id,1,required" frugal:"1,required,i64" json:"agent_id"`
	ConvId  int64 `thrift:"conv_id,2,required" frugal:"2,required,i64" json:"conv_id"`
}

func NewMarkConvReadReq() *MarkConvReadReq {
	return &MarkConvReadReq{}
}

func (p *MarkConvReadReq) InitDefault() {
}

func (p *MarkConvReadReq) GetAgentId() (v int64) {
	return p.AgentId
}

func (p *MarkConvReadReq) GetConvId() (v int64) {
	return p.ConvId
}
func (p *MarkConvReadReq) SetAgentId(val int64) {
	p.AgentId = val
}
func (p *MarkConvReadReq) SetConvId(val int64) {
	p.ConvId = val
}

func (p *MarkConvReadReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MarkConvReadReq(%+v)", *p)
}

var fieldIDToName_MarkConvReadReq = map[int16]string{
	1: "agent_id",
	2: "conv_id",
}

type MarkConvReadResp struct {
	BaseResp *base.BaseResp `thrift:"base_resp,255,required" frugal:"255,required,base.BaseResp" json:"base_resp"`
}

func NewMarkConvReadResp() *MarkConvReadResp {
	return &MarkConvReadResp{}
}

func (p *MarkConvReadResp) InitDefault() {
}

var MarkConvReadResp_BaseResp_DEFAULT *base.BaseResp

func (p *MarkConvReadResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return MarkConvReadResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *MarkConvReadResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *MarkConvReadResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *MarkConvReadResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MarkConvReadResp(%+v)", *p)
}

var fieldIDToName_MarkConvReadResp = map[int16]string{
	255: "base_resp",
}

type PMService interface {
	GetUnreadCount(ctx context.Context, req *GetUnreadCountReq) (r *GetUnreadCountResp, err error)

	MarkConvRead(ctx context.Context, req *MarkConvReadReq) (r *MarkConvReadResp, err error)

	SendPM(ctx context.Context, req *SendPMReq) (r *SendPMResp, err error)

	FetchPM(ctx context.Context, req *FetchPMReq) (r *FetchPMResp, err error)

	FetchPMHistory(ctx context.Context, req *FetchPMHistoryReq) (r *FetchPMHistoryResp, err error)

	ListConversations(ctx context.Context, req *ListConversationsReq) (r *ListConversationsResp, err error)

	GetConvHistory(ctx context.Context, req *GetConvHistoryReq) (r *GetConvHistoryResp, err error)

	CloseConv(ctx context.Context, req *CloseConvReq) (r *CloseConvResp, err error)

	SendFriendRequest(ctx context.Context, req *SendFriendRequestReq) (r *SendFriendRequestResp, err error)

	HandleFriendRequest(ctx context.Context, req *HandleFriendRequestReq) (r *HandleFriendRequestResp, err error)

	Unfriend(ctx context.Context, req *UnfriendReq) (r *UnfriendResp, err error)

	BlockUser(ctx context.Context, req *BlockUserReq) (r *BlockUserResp, err error)

	UnblockUser(ctx context.Context, req *UnblockUserReq) (r *UnblockUserResp, err error)

	ListFriendRequests(ctx context.Context, req *ListFriendRequestsReq) (r *ListFriendRequestsResp, err error)

	ListFriends(ctx context.Context, req *ListFriendsReq) (r *ListFriendsResp, err error)

	UpdateFriendRemark(ctx context.Context, req *UpdateFriendRemarkReq) (r *UpdateFriendRemarkResp, err error)
}

type PMServiceGetUnreadCountArgs struct {
	Req *GetUnreadCountReq `thrift:"req,1" frugal:"1,default,GetUnreadCountReq" json:"req"`
}

func NewPMServiceGetUnreadCountArgs() *PMServiceGetUnreadCountArgs {
	return &PMServiceGetUnreadCountArgs{}
}

func (p *PMServiceGetUnreadCountArgs) InitDefault() {
}

var PMServiceGetUnreadCountArgs_Req_DEFAULT *GetUnreadCountReq

func (p *PMServiceGetUnreadCountArgs) GetReq() (v *GetUnreadCountReq) {
	if !p.IsSetReq() {
		return PMServiceGetUnreadCountArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PMServiceGetUnreadCountArgs) SetReq(val *GetUnreadCountReq) {
	p.Req = val
}

func (p *PMServiceGetUnreadCountArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PMServiceGetUnreadCountArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PMServiceGetUnreadCountArgs(%+v)", *p)
}

var fieldIDToName_PMServiceGetUnreadCountArgs = map[int16]string{
	1: "req",
}

type PMServiceGetUnreadCountResult struct {
	Success *GetUnreadCountResp `thrift:"success,0,optional" frugal:"0,optional,GetUnreadCountResp" json:"success,omitempty"`
}

func NewPMServiceGetUnreadCountResult() *PMServiceGetUnreadCountResult {
	return &PMServiceGetUnreadCountResult{}
}

func (p *PMServiceGetUnreadCountResult) InitDefault() {
}

var PMServiceGetUnreadCountResult_Success_DEFAULT *GetUnreadCountResp

func (p *PMServiceGetUnreadCountResult) GetSuccess() (v *GetUnreadCountResp) {
	if !p.IsSetSuccess() {
		return PMServiceGetUnreadCountResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PMServiceGetUnreadCountResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetUnreadCountResp)
}

func (p *PMServiceGetUnreadCountResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PMServiceGetUnreadCountResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PMServiceGetUnreadCountResult(%+v)", *p)
}

var fieldIDToName_PMServiceGetUnreadCountResult = map[int16]string{
	0: "success",
}

type PMServiceMarkConvReadArgs struct {
	Req *MarkConvReadReq `thrift:"req,1" frugal:"1,default,MarkConvReadReq" json:"req"`
}

func NewPMServiceMarkConvReadArgs() *PMServiceMarkConvReadArgs {
	return &PMServiceMarkConvReadArgs{}
}

func (p *PMServiceMarkConvReadArgs) InitDefault() {
}

var PMServiceMarkConvReadArgs_Req_DEFAULT *MarkConvReadReq

func (p *PMServiceMarkConvReadArgs) GetReq() (v *MarkConvReadReq) {
	if !p.IsSetReq() {
		return PMServiceMarkConvReadArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PMServiceMarkConvReadArgs) SetReq(val *MarkConvReadReq) {
	p.Req = val
}

func (p *PMServiceMarkConvReadArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PMServiceMarkConvReadArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PMServiceMarkConvReadArgs(%+v)", *p)
}

var fieldIDToName_PMServiceMarkConvReadArgs = map[int16]string{
	1: "req",
}

type PMServiceMarkConvReadResult struct {
	Success *MarkConvReadResp `thrift:"success,0,optional" frugal:"0,optional,MarkConvReadResp" json:"success,omitempty"`
}

func NewPMServiceMarkConvReadResult() *PMServiceMarkConvReadResult {
	return &PMServiceMarkConvReadResult{}
}

func (p *PMServiceMarkConvReadResult) InitDefault() {
}

var PMServiceMarkConvReadResult_Success_DEFAULT *MarkConvReadResp

func (p *PMServiceMarkConvReadResult) GetSuccess() (v *MarkConvReadResp) {
	if !p.IsSetSuccess() {
		return PMServiceMarkConvReadResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PMServiceMarkConvReadResult) SetSuccess(x interface{}) {
	p.Success = x.(*MarkConvReadResp)
}

func (p *PMServiceMarkConvReadResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PMServiceMarkConvReadResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PMServiceMarkConvReadResult(%+v)", *p)
}

var fieldIDToName_PMServiceMarkConvReadResult = map[int16]string{
	0: "success",
}

type PMServiceSendPMArgs struct {
	Req *SendPMReq `thrift:"req,1" frugal:"1,default,SendPMReq" json:"req"`
}

func NewPMServiceSendPMArgs() *PMServiceSendPMArgs {
	return &PMServiceSendPMArgs{}
}

func (p *PMServiceSendPMArgs) InitDefault() {
}

var PMServiceSendPMArgs_Req_DEFAULT *SendPMReq

func (p *PMServiceSendPMArgs) GetReq() (v *SendPMReq) {
	if !p.IsSetReq() {
		return PMServiceSendPMArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PMServiceSendPMArgs) SetReq(val *SendPMReq) {
	p.Req = val
}

func (p *PMServiceSendPMArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PMServiceSendPMArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PMServiceSendPMArgs(%+v)", *p)
}

var fieldIDToName_PMServiceSendPMArgs = map[int16]string{
	1: "req",
}

type PMServiceSendPMResult struct {
	Success *SendPMResp `thrift:"success,0,optional" frugal:"0,optional,SendPMResp" json:"success,omitempty"`
}

func NewPMServiceSendPMResult() *PMServiceSendPMResult {
	return &PMServiceSendPMResult{}
}

func (p *PMServiceSendPMResult) InitDefault() {
}

var PMServiceSendPMResult_Success_DEFAULT *SendPMResp

func (p *PMServiceSendPMResult) GetSuccess() (v *SendPMResp) {
	if !p.IsSetSuccess() {
		return PMServiceSendPMResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PMServiceSendPMResult) SetSuccess(x interface{}) {
	p.Success = x.(*SendPMResp)
}

func (p *PMServiceSendPMResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PMServiceSendPMResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PMServiceSendPMResult(%+v)", *p)
}

var fieldIDToName_PMServiceSendPMResult = map[int16]string{
	0: "success",
}

type PMServiceFetchPMArgs struct {
	Req *FetchPMReq `thrift:"req,1" frugal:"1,default,FetchPMReq" json:"req"`
}

func NewPMServiceFetchPMArgs() *PMServiceFetchPMArgs {
	return &PMServiceFetchPMArgs{}
}

func (p *PMServiceFetchPMArgs) InitDefault() {
}

var PMServiceFetchPMArgs_Req_DEFAULT *FetchPMReq

func (p *PMServiceFetchPMArgs) GetReq() (v *FetchPMReq) {
	if !p.IsSetReq() {
		return PMServiceFetchPMArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PMServiceFetchPMArgs) SetReq(val *FetchPMReq) {
	p.Req = val
}

func (p *PMServiceFetchPMArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PMServiceFetchPMArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PMServiceFetchPMArgs(%+v)", *p)
}

var fieldIDToName_PMServiceFetchPMArgs = map[int16]string{
	1: "req",
}

type PMServiceFetchPMResult struct {
	Success *FetchPMResp `thrift:"success,0,optional" frugal:"0,optional,FetchPMResp" json:"success,omitempty"`
}

func NewPMServiceFetchPMResult() *PMServiceFetchPMResult {
	return &PMServiceFetchPMResult{}
}

func (p *PMServiceFetchPMResult) InitDefault() {
}

var PMServiceFetchPMResult_Success_DEFAULT *FetchPMResp

func (p *PMServiceFetchPMResult) GetSuccess() (v *FetchPMResp) {
	if !p.IsSetSuccess() {
		return PMServiceFetchPMResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PMServiceFetchPMResult) SetSuccess(x interface{}) {
	p.Success = x.(*FetchPMResp)
}

func (p *PMServiceFetchPMResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PMServiceFetchPMResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PMServiceFetchPMResult(%+v)", *p)
}

var fieldIDToName_PMServiceFetchPMResult = map[int16]string{
	0: "success",
}

type PMServiceFetchPMHistoryArgs struct {
	Req *FetchPMHistoryReq `thrift:"req,1" frugal:"1,default,FetchPMHistoryReq" json:"req"`
}

func NewPMServiceFetchPMHistoryArgs() *PMServiceFetchPMHistoryArgs {
	return &PMServiceFetchPMHistoryArgs{}
}

func (p *PMServiceFetchPMHistoryArgs) InitDefault() {
}

var PMServiceFetchPMHistoryArgs_Req_DEFAULT *FetchPMHistoryReq

func (p *PMServiceFetchPMHistoryArgs) GetReq() (v *FetchPMHistoryReq) {
	if !p.IsSetReq() {
		return PMServiceFetchPMHistoryArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PMServiceFetchPMHistoryArgs) SetReq(val *FetchPMHistoryReq) {
	p.Req = val
}

func (p *PMServiceFetchPMHistoryArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PMServiceFetchPMHistoryArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PMServiceFetchPMHistoryArgs(%+v)", *p)
}

var fieldIDToName_PMServiceFetchPMHistoryArgs = map[int16]string{
	1: "req",
}

type PMServiceFetchPMHistoryResult struct {
	Success *FetchPMHistoryResp `thrift:"success,0,optional" frugal:"0,optional,FetchPMHistoryResp" json:"success,omitempty"`
}

func NewPMServiceFetchPMHistoryResult() *PMServiceFetchPMHistoryResult {
	return &PMServiceFetchPMHistoryResult{}
}

func (p *PMServiceFetchPMHistoryResult) InitDefault() {
}

var PMServiceFetchPMHistoryResult_Success_DEFAULT *FetchPMHistoryResp

func (p *PMServiceFetchPMHistoryResult) GetSuccess() (v *FetchPMHistoryResp) {
	if !p.IsSetSuccess() {
		return PMServiceFetchPMHistoryResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PMServiceFetchPMHistoryResult) SetSuccess(x interface{}) {
	p.Success = x.(*FetchPMHistoryResp)
}

func (p *PMServiceFetchPMHistoryResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PMServiceFetchPMHistoryResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PMServiceFetchPMHistoryResult(%+v)", *p)
}

var fieldIDToName_PMServiceFetchPMHistoryResult = map[int16]string{
	0: "success",
}

type PMServiceListConversationsArgs struct {
	Req *ListConversationsReq `thrift:"req,1" frugal:"1,default,ListConversationsReq" json:"req"`
}

func NewPMServiceListConversationsArgs() *PMServiceListConversationsArgs {
	return &PMServiceListConversationsArgs{}
}

func (p *PMServiceListConversationsArgs) InitDefault() {
}

var PMServiceListConversationsArgs_Req_DEFAULT *ListConversationsReq

func (p *PMServiceListConversationsArgs) GetReq() (v *ListConversationsReq) {
	if !p.IsSetReq() {
		return PMServiceListConversationsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PMServiceListConversationsArgs) SetReq(val *ListConversationsReq) {
	p.Req = val
}

func (p *PMServiceListConversationsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PMServiceListConversationsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PMServiceListConversationsArgs(%+v)", *p)
}

var fieldIDToName_PMServiceListConversationsArgs = map[int16]string{
	1: "req",
}

type PMServiceListConversationsResult struct {
	Success *ListConversationsResp `thrift:"success,0,optional" frugal:"0,optional,ListConversationsResp" json:"success,omitempty"`
}

func NewPMServiceListConversationsResult() *PMServiceListConversationsResult {
	return &PMServiceListConversationsResult{}
}

func (p *PMServiceListConversationsResult) InitDefault() {
}

var PMServiceListConversationsResult_Success_DEFAULT *ListConversationsResp

func (p *PMServiceListConversationsResult) GetSuccess() (v *ListConversationsResp) {
	if !p.IsSetSuccess() {
		return PMServiceListConversationsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PMServiceListConversationsResult) SetSuccess(x interface{}) {
	p.Success = x.(*ListConversationsResp)
}

func (p *PMServiceListConversationsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PMServiceListConversationsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PMServiceListConversationsResult(%+v)", *p)
}

var fieldIDToName_PMServiceListConversationsResult = map[int16]string{
	0: "success",
}

type PMServiceGetConvHistoryArgs struct {
	Req *GetConvHistoryReq `thrift:"req,1" frugal:"1,default,GetConvHistoryReq" json:"req"`
}

func NewPMServiceGetConvHistoryArgs() *PMServiceGetConvHistoryArgs {
	return &PMServiceGetConvHistoryArgs{}
}

func (p *PMServiceGetConvHistoryArgs) InitDefault() {
}

var PMServiceGetConvHistoryArgs_Req_DEFAULT *GetConvHistoryReq

func (p *PMServiceGetConvHistoryArgs) GetReq() (v *GetConvHistoryReq) {
	if !p.IsSetReq() {
		return PMServiceGetConvHistoryArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PMServiceGetConvHistoryArgs) SetReq(val *GetConvHistoryReq) {
	p.Req = val
}

func (p *PMServiceGetConvHistoryArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PMServiceGetConvHistoryArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PMServiceGetConvHistoryArgs(%+v)", *p)
}

var fieldIDToName_PMServiceGetConvHistoryArgs = map[int16]string{
	1: "req",
}

type PMServiceGetConvHistoryResult struct {
	Success *GetConvHistoryResp `thrift:"success,0,optional" frugal:"0,optional,GetConvHistoryResp" json:"success,omitempty"`
}

func NewPMServiceGetConvHistoryResult() *PMServiceGetConvHistoryResult {
	return &PMServiceGetConvHistoryResult{}
}

func (p *PMServiceGetConvHistoryResult) InitDefault() {
}

var PMServiceGetConvHistoryResult_Success_DEFAULT *GetConvHistoryResp

func (p *PMServiceGetConvHistoryResult) GetSuccess() (v *GetConvHistoryResp) {
	if !p.IsSetSuccess() {
		return PMServiceGetConvHistoryResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PMServiceGetConvHistoryResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetConvHistoryResp)
}

func (p *PMServiceGetConvHistoryResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PMServiceGetConvHistoryResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PMServiceGetConvHistoryResult(%+v)", *p)
}

var fieldIDToName_PMServiceGetConvHistoryResult = map[int16]string{
	0: "success",
}

type PMServiceCloseConvArgs struct {
	Req *CloseConvReq `thrift:"req,1" frugal:"1,default,CloseConvReq" json:"req"`
}

func NewPMServiceCloseConvArgs() *PMServiceCloseConvArgs {
	return &PMServiceCloseConvArgs{}
}

func (p *PMServiceCloseConvArgs) InitDefault() {
}

var PMServiceCloseConvArgs_Req_DEFAULT *CloseConvReq

func (p *PMServiceCloseConvArgs) GetReq() (v *CloseConvReq) {
	if !p.IsSetReq() {
		return PMServiceCloseConvArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PMServiceCloseConvArgs) SetReq(val *CloseConvReq) {
	p.Req = val
}

func (p *PMServiceCloseConvArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PMServiceCloseConvArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PMServiceCloseConvArgs(%+v)", *p)
}

var fieldIDToName_PMServiceCloseConvArgs = map[int16]string{
	1: "req",
}

type PMServiceCloseConvResult struct {
	Success *CloseConvResp `thrift:"success,0,optional" frugal:"0,optional,CloseConvResp" json:"success,omitempty"`
}

func NewPMServiceCloseConvResult() *PMServiceCloseConvResult {
	return &PMServiceCloseConvResult{}
}

func (p *PMServiceCloseConvResult) InitDefault() {
}

var PMServiceCloseConvResult_Success_DEFAULT *CloseConvResp

func (p *PMServiceCloseConvResult) GetSuccess() (v *CloseConvResp) {
	if !p.IsSetSuccess() {
		return PMServiceCloseConvResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PMServiceCloseConvResult) SetSuccess(x interface{}) {
	p.Success = x.(*CloseConvResp)
}

func (p *PMServiceCloseConvResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PMServiceCloseConvResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PMServiceCloseConvResult(%+v)", *p)
}

var fieldIDToName_PMServiceCloseConvResult = map[int16]string{
	0: "success",
}

type PMServiceSendFriendRequestArgs struct {
	Req *SendFriendRequestReq `thrift:"req,1" frugal:"1,default,SendFriendRequestReq" json:"req"`
}

func NewPMServiceSendFriendRequestArgs() *PMServiceSendFriendRequestArgs {
	return &PMServiceSendFriendRequestArgs{}
}

func (p *PMServiceSendFriendRequestArgs) InitDefault() {
}

var PMServiceSendFriendRequestArgs_Req_DEFAULT *SendFriendRequestReq

func (p *PMServiceSendFriendRequestArgs) GetReq() (v *SendFriendRequestReq) {
	if !p.IsSetReq() {
		return PMServiceSendFriendRequestArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PMServiceSendFriendRequestArgs) SetReq(val *SendFriendRequestReq) {
	p.Req = val
}

func (p *PMServiceSendFriendRequestArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PMServiceSendFriendRequestArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PMServiceSendFriendRequestArgs(%+v)", *p)
}

var fieldIDToName_PMServiceSendFriendRequestArgs = map[int16]string{
	1: "req",
}

type PMServiceSendFriendRequestResult struct {
	Success *SendFriendRequestResp `thrift:"success,0,optional" frugal:"0,optional,SendFriendRequestResp" json:"success,omitempty"`
}

func NewPMServiceSendFriendRequestResult() *PMServiceSendFriendRequestResult {
	return &PMServiceSendFriendRequestResult{}
}

func (p *PMServiceSendFriendRequestResult) InitDefault() {
}

var PMServiceSendFriendRequestResult_Success_DEFAULT *SendFriendRequestResp

func (p *PMServiceSendFriendRequestResult) GetSuccess() (v *SendFriendRequestResp) {
	if !p.IsSetSuccess() {
		return PMServiceSendFriendRequestResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PMServiceSendFriendRequestResult) SetSuccess(x interface{}) {
	p.Success = x.(*SendFriendRequestResp)
}

func (p *PMServiceSendFriendRequestResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PMServiceSendFriendRequestResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PMServiceSendFriendRequestResult(%+v)", *p)
}

var fieldIDToName_PMServiceSendFriendRequestResult = map[int16]string{
	0: "success",
}

type PMServiceHandleFriendRequestArgs struct {
	Req *HandleFriendRequestReq `thrift:"req,1" frugal:"1,default,HandleFriendRequestReq" json:"req"`
}

func NewPMServiceHandleFriendRequestArgs() *PMServiceHandleFriendRequestArgs {
	return &PMServiceHandleFriendRequestArgs{}
}

func (p *PMServiceHandleFriendRequestArgs) InitDefault() {
}

var PMServiceHandleFriendRequestArgs_Req_DEFAULT *HandleFriendRequestReq

func (p *PMServiceHandleFriendRequestArgs) GetReq() (v *HandleFriendRequestReq) {
	if !p.IsSetReq() {
		return PMServiceHandleFriendRequestArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PMServiceHandleFriendRequestArgs) SetReq(val *HandleFriendRequestReq) {
	p.Req = val
}

func (p *PMServiceHandleFriendRequestArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PMServiceHandleFriendRequestArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PMServiceHandleFriendRequestArgs(%+v)", *p)
}

var fieldIDToName_PMServiceHandleFriendRequestArgs = map[int16]string{
	1: "req",
}

type PMServiceHandleFriendRequestResult struct {
	Success *HandleFriendRequestResp `thrift:"success,0,optional" frugal:"0,optional,HandleFriendRequestResp" json:"success,omitempty"`
}

func NewPMServiceHandleFriendRequestResult() *PMServiceHandleFriendRequestResult {
	return &PMServiceHandleFriendRequestResult{}
}

func (p *PMServiceHandleFriendRequestResult) InitDefault() {
}

var PMServiceHandleFriendRequestResult_Success_DEFAULT *HandleFriendRequestResp

func (p *PMServiceHandleFriendRequestResult) GetSuccess() (v *HandleFriendRequestResp) {
	if !p.IsSetSuccess() {
		return PMServiceHandleFriendRequestResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PMServiceHandleFriendRequestResult) SetSuccess(x interface{}) {
	p.Success = x.(*HandleFriendRequestResp)
}

func (p *PMServiceHandleFriendRequestResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PMServiceHandleFriendRequestResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PMServiceHandleFriendRequestResult(%+v)", *p)
}

var fieldIDToName_PMServiceHandleFriendRequestResult = map[int16]string{
	0: "success",
}

type PMServiceUnfriendArgs struct {
	Req *UnfriendReq `thrift:"req,1" frugal:"1,default,UnfriendReq" json:"req"`
}

func NewPMServiceUnfriendArgs() *PMServiceUnfriendArgs {
	return &PMServiceUnfriendArgs{}
}

func (p *PMServiceUnfriendArgs) InitDefault() {
}

var PMServiceUnfriendArgs_Req_DEFAULT *UnfriendReq

func (p *PMServiceUnfriendArgs) GetReq() (v *UnfriendReq) {
	if !p.IsSetReq() {
		return PMServiceUnfriendArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PMServiceUnfriendArgs) SetReq(val *UnfriendReq) {
	p.Req = val
}

func (p *PMServiceUnfriendArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PMServiceUnfriendArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PMServiceUnfriendArgs(%+v)", *p)
}

var fieldIDToName_PMServiceUnfriendArgs = map[int16]string{
	1: "req",
}

type PMServiceUnfriendResult struct {
	Success *UnfriendResp `thrift:"success,0,optional" frugal:"0,optional,UnfriendResp" json:"success,omitempty"`
}

func NewPMServiceUnfriendResult() *PMServiceUnfriendResult {
	return &PMServiceUnfriendResult{}
}

func (p *PMServiceUnfriendResult) InitDefault() {
}

var PMServiceUnfriendResult_Success_DEFAULT *UnfriendResp

func (p *PMServiceUnfriendResult) GetSuccess() (v *UnfriendResp) {
	if !p.IsSetSuccess() {
		return PMServiceUnfriendResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PMServiceUnfriendResult) SetSuccess(x interface{}) {
	p.Success = x.(*UnfriendResp)
}

func (p *PMServiceUnfriendResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PMServiceUnfriendResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PMServiceUnfriendResult(%+v)", *p)
}

var fieldIDToName_PMServiceUnfriendResult = map[int16]string{
	0: "success",
}

type PMServiceBlockUserArgs struct {
	Req *BlockUserReq `thrift:"req,1" frugal:"1,default,BlockUserReq" json:"req"`
}

func NewPMServiceBlockUserArgs() *PMServiceBlockUserArgs {
	return &PMServiceBlockUserArgs{}
}

func (p *PMServiceBlockUserArgs) InitDefault() {
}

var PMServiceBlockUserArgs_Req_DEFAULT *BlockUserReq

func (p *PMServiceBlockUserArgs) GetReq() (v *BlockUserReq) {
	if !p.IsSetReq() {
		return PMServiceBlockUserArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PMServiceBlockUserArgs) SetReq(val *BlockUserReq) {
	p.Req = val
}

func (p *PMServiceBlockUserArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PMServiceBlockUserArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PMServiceBlockUserArgs(%+v)", *p)
}

var fieldIDToName_PMServiceBlockUserArgs = map[int16]string{
	1: "req",
}

type PMServiceBlockUserResult struct {
	Success *BlockUserResp `thrift:"success,0,optional" frugal:"0,optional,BlockUserResp" json:"success,omitempty"`
}

func NewPMServiceBlockUserResult() *PMServiceBlockUserResult {
	return &PMServiceBlockUserResult{}
}

func (p *PMServiceBlockUserResult) InitDefault() {
}

var PMServiceBlockUserResult_Success_DEFAULT *BlockUserResp

func (p *PMServiceBlockUserResult) GetSuccess() (v *BlockUserResp) {
	if !p.IsSetSuccess() {
		return PMServiceBlockUserResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PMServiceBlockUserResult) SetSuccess(x interface{}) {
	p.Success = x.(*BlockUserResp)
}

func (p *PMServiceBlockUserResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PMServiceBlockUserResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PMServiceBlockUserResult(%+v)", *p)
}

var fieldIDToName_PMServiceBlockUserResult = map[int16]string{
	0: "success",
}

type PMServiceUnblockUserArgs struct {
	Req *UnblockUserReq `thrift:"req,1" frugal:"1,default,UnblockUserReq" json:"req"`
}

func NewPMServiceUnblockUserArgs() *PMServiceUnblockUserArgs {
	return &PMServiceUnblockUserArgs{}
}

func (p *PMServiceUnblockUserArgs) InitDefault() {
}

var PMServiceUnblockUserArgs_Req_DEFAULT *UnblockUserReq

func (p *PMServiceUnblockUserArgs) GetReq() (v *UnblockUserReq) {
	if !p.IsSetReq() {
		return PMServiceUnblockUserArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PMServiceUnblockUserArgs) SetReq(val *UnblockUserReq) {
	p.Req = val
}

func (p *PMServiceUnblockUserArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PMServiceUnblockUserArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PMServiceUnblockUserArgs(%+v)", *p)
}

var fieldIDToName_PMServiceUnblockUserArgs = map[int16]string{
	1: "req",
}

type PMServiceUnblockUserResult struct {
	Success *UnblockUserResp `thrift:"success,0,optional" frugal:"0,optional,UnblockUserResp" json:"success,omitempty"`
}

func NewPMServiceUnblockUserResult() *PMServiceUnblockUserResult {
	return &PMServiceUnblockUserResult{}
}

func (p *PMServiceUnblockUserResult) InitDefault() {
}

var PMServiceUnblockUserResult_Success_DEFAULT *UnblockUserResp

func (p *PMServiceUnblockUserResult) GetSuccess() (v *UnblockUserResp) {
	if !p.IsSetSuccess() {
		return PMServiceUnblockUserResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PMServiceUnblockUserResult) SetSuccess(x interface{}) {
	p.Success = x.(*UnblockUserResp)
}

func (p *PMServiceUnblockUserResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PMServiceUnblockUserResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PMServiceUnblockUserResult(%+v)", *p)
}

var fieldIDToName_PMServiceUnblockUserResult = map[int16]string{
	0: "success",
}

type PMServiceListFriendRequestsArgs struct {
	Req *ListFriendRequestsReq `thrift:"req,1" frugal:"1,default,ListFriendRequestsReq" json:"req"`
}

func NewPMServiceListFriendRequestsArgs() *PMServiceListFriendRequestsArgs {
	return &PMServiceListFriendRequestsArgs{}
}

func (p *PMServiceListFriendRequestsArgs) InitDefault() {
}

var PMServiceListFriendRequestsArgs_Req_DEFAULT *ListFriendRequestsReq

func (p *PMServiceListFriendRequestsArgs) GetReq() (v *ListFriendRequestsReq) {
	if !p.IsSetReq() {
		return PMServiceListFriendRequestsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PMServiceListFriendRequestsArgs) SetReq(val *ListFriendRequestsReq) {
	p.Req = val
}

func (p *PMServiceListFriendRequestsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PMServiceListFriendRequestsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PMServiceListFriendRequestsArgs(%+v)", *p)
}

var fieldIDToName_PMServiceListFriendRequestsArgs = map[int16]string{
	1: "req",
}

type PMServiceListFriendRequestsResult struct {
	Success *ListFriendRequestsResp `thrift:"success,0,optional" frugal:"0,optional,ListFriendRequestsResp" json:"success,omitempty"`
}

func NewPMServiceListFriendRequestsResult() *PMServiceListFriendRequestsResult {
	return &PMServiceListFriendRequestsResult{}
}

func (p *PMServiceListFriendRequestsResult) InitDefault() {
}

var PMServiceListFriendRequestsResult_Success_DEFAULT *ListFriendRequestsResp

func (p *PMServiceListFriendRequestsResult) GetSuccess() (v *ListFriendRequestsResp) {
	if !p.IsSetSuccess() {
		return PMServiceListFriendRequestsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PMServiceListFriendRequestsResult) SetSuccess(x interface{}) {
	p.Success = x.(*ListFriendRequestsResp)
}

func (p *PMServiceListFriendRequestsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PMServiceListFriendRequestsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PMServiceListFriendRequestsResult(%+v)", *p)
}

var fieldIDToName_PMServiceListFriendRequestsResult = map[int16]string{
	0: "success",
}

type PMServiceListFriendsArgs struct {
	Req *ListFriendsReq `thrift:"req,1" frugal:"1,default,ListFriendsReq" json:"req"`
}

func NewPMServiceListFriendsArgs() *PMServiceListFriendsArgs {
	return &PMServiceListFriendsArgs{}
}

func (p *PMServiceListFriendsArgs) InitDefault() {
}

var PMServiceListFriendsArgs_Req_DEFAULT *ListFriendsReq

func (p *PMServiceListFriendsArgs) GetReq() (v *ListFriendsReq) {
	if !p.IsSetReq() {
		return PMServiceListFriendsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PMServiceListFriendsArgs) SetReq(val *ListFriendsReq) {
	p.Req = val
}

func (p *PMServiceListFriendsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PMServiceListFriendsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PMServiceListFriendsArgs(%+v)", *p)
}

var fieldIDToName_PMServiceListFriendsArgs = map[int16]string{
	1: "req",
}

type PMServiceListFriendsResult struct {
	Success *ListFriendsResp `thrift:"success,0,optional" frugal:"0,optional,ListFriendsResp" json:"success,omitempty"`
}

func NewPMServiceListFriendsResult() *PMServiceListFriendsResult {
	return &PMServiceListFriendsResult{}
}

func (p *PMServiceListFriendsResult) InitDefault() {
}

var PMServiceListFriendsResult_Success_DEFAULT *ListFriendsResp

func (p *PMServiceListFriendsResult) GetSuccess() (v *ListFriendsResp) {
	if !p.IsSetSuccess() {
		return PMServiceListFriendsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PMServiceListFriendsResult) SetSuccess(x interface{}) {
	p.Success = x.(*ListFriendsResp)
}

func (p *PMServiceListFriendsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PMServiceListFriendsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PMServiceListFriendsResult(%+v)", *p)
}

var fieldIDToName_PMServiceListFriendsResult = map[int16]string{
	0: "success",
}

type PMServiceUpdateFriendRemarkArgs struct {
	Req *UpdateFriendRemarkReq `thrift:"req,1" frugal:"1,default,UpdateFriendRemarkReq" json:"req"`
}

func NewPMServiceUpdateFriendRemarkArgs() *PMServiceUpdateFriendRemarkArgs {
	return &PMServiceUpdateFriendRemarkArgs{}
}

func (p *PMServiceUpdateFriendRemarkArgs) InitDefault() {
}

var PMServiceUpdateFriendRemarkArgs_Req_DEFAULT *UpdateFriendRemarkReq

func (p *PMServiceUpdateFriendRemarkArgs) GetReq() (v *UpdateFriendRemarkReq) {
	if !p.IsSetReq() {
		return PMServiceUpdateFriendRemarkArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PMServiceUpdateFriendRemarkArgs) SetReq(val *UpdateFriendRemarkReq) {
	p.Req = val
}

func (p *PMServiceUpdateFriendRemarkArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PMServiceUpdateFriendRemarkArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PMServiceUpdateFriendRemarkArgs(%+v)", *p)
}

var fieldIDToName_PMServiceUpdateFriendRemarkArgs = map[int16]string{
	1: "req",
}

type PMServiceUpdateFriendRemarkResult struct {
	Success *UpdateFriendRemarkResp `thrift:"success,0,optional" frugal:"0,optional,UpdateFriendRemarkResp" json:"success,omitempty"`
}

func NewPMServiceUpdateFriendRemarkResult() *PMServiceUpdateFriendRemarkResult {
	return &PMServiceUpdateFriendRemarkResult{}
}

func (p *PMServiceUpdateFriendRemarkResult) InitDefault() {
}

var PMServiceUpdateFriendRemarkResult_Success_DEFAULT *UpdateFriendRemarkResp

func (p *PMServiceUpdateFriendRemarkResult) GetSuccess() (v *UpdateFriendRemarkResp) {
	if !p.IsSetSuccess() {
		return PMServiceUpdateFriendRemarkResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PMServiceUpdateFriendRemarkResult) SetSuccess(x interface{}) {
	p.Success = x.(*UpdateFriendRemarkResp)
}

func (p *PMServiceUpdateFriendRemarkResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PMServiceUpdateFriendRemarkResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PMServiceUpdateFriendRemarkResult(%+v)", *p)
}

var fieldIDToName_PMServiceUpdateFriendRemarkResult = map[int16]string{
	0: "success",
}
