// Code generated by hertz generator. DO NOT EDIT.

package router_gen

import (
	eigenflux_api "eigenflux_server/api/router_gen/eigenflux/api"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!

	eigenflux_api.Register(r)
}
