// Code generated by thriftgo (0.4.2). DO NOT EDIT.

package profile

import (
	"context"
	"eigenflux_server/kitex_gen/eigenflux/base"
	"fmt"
)

type Agent struct {
	Id          int64    `thrift:"id,1,required" frugal:"1,required,i64" json:"id"`
	Email       string   `thrift:"email,2,required" frugal:"2,required,string" json:"email"`
	AgentName   string   `thrift:"agent_name,3,required" frugal:"3,required,string" json:"agent_name"`
	Bio         string   `thrift:"bio,4,required" frugal:"4,required,string" json:"bio"`
	CreatedAt   int64    `thrift:"created_at,5,required" frugal:"5,required,i64" json:"created_at"`
	UpdatedAt   int64    `thrift:"updated_at,6,required" frugal:"6,required,i64" json:"updated_at"`
	Country     *string  `thrift:"country,7,optional" frugal:"7,optional,string" json:"country,omitempty"`
	Keywords    []string `thrift:"keywords,8,optional" frugal:"8,optional,list<string>" json:"keywords,omitempty"`
	ShortId     *string  `thrift:"short_id,9,optional" frugal:"9,optional,string" json:"short_id,omitempty"`
	DisplayName *string  `thrift:"display_name,10,optional" frugal:"10,optional,string" json:"display_name,omitempty"`
}

func NewAgent() *Agent {
	return &Agent{}
}

func (p *Agent) InitDefault() {
}

func (p *Agent) GetId() (v int64) {
	return p.Id
}

func (p *Agent) GetEmail() (v string) {
	return p.Email
}

func (p *Agent) GetAgentName() (v string) {
	return p.AgentName
}

func (p *Agent) GetBio() (v string) {
	return p.Bio
}

func (p *Agent) GetCreatedAt() (v int64) {
	return p.CreatedAt
}

func (p *Agent) GetUpdatedAt() (v int64) {
	return p.UpdatedAt
}

var Agent_Country_DEFAULT string

func (p *Agent) GetCountry() (v string) {
	if !p.IsSetCountry() {
		return Agent_Country_DEFAULT
	}
	return *p.Country
}

var Agent_Keywords_DEFAULT []string

func (p *Agent) GetKeywords() (v []string) {
	if !p.IsSetKeywords() {
		return Agent_Keywords_DEFAULT
	}
	return p.Keywords
}

var Agent_ShortId_DEFAULT string

func (p *Agent) GetShortId() (v string) {
	if !p.IsSetShortId() {
		return Agent_ShortId_DEFAULT
	}
	return *p.ShortId
}

var Agent_DisplayName_DEFAULT string

func (p *Agent) GetDisplayName() (v string) {
	if !p.IsSetDisplayName() {
		return Agent_DisplayName_DEFAULT
	}
	return *p.DisplayName
}
func (p *Agent) SetId(val int64) {
	p.Id = val
}
func (p *Agent) SetEmail(val string) {
	p.Email = val
}
func (p *Agent) SetAgentName(val string) {
	p.AgentName = val
}
func (p *Agent) SetBio(val string) {
	p.Bio = val
}
func (p *Agent) SetCreatedAt(val int64) {
	p.CreatedAt = val
}
func (p *Agent) SetUpdatedAt(val int64) {
	p.UpdatedAt = val
}
func (p *Agent) SetCountry(val *string) {
	p.Country = val
}
func (p *Agent) SetKeywords(val []string) {
	p.Keywords = val
}
func (p *Agent) SetShortId(val *string) {
	p.ShortId = val
}
func (p *Agent) SetDisplayName(val *string) {
	p.DisplayName = val
}

func (p *Agent) IsSetCountry() bool {
	return p.Country != nil
}

func (p *Agent) IsSetKeywords() bool {
	return p.Keywords != nil
}

func (p *Agent) IsSetShortId() bool {
	return p.ShortId != nil
}

func (p *Agent) IsSetDisplayName() bool {
	return p.DisplayName != nil
}

func (p *Agent) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Agent(%+v)", *p)
}

var fieldIDToName_Agent = map[int16]string{
	1:  "id",
	2:  "email",
	3:  "agent_name",
	4:  "bio",
	5:  "created_at",
	6:  "updated_at",
	7:  "country",
	8:  "keywords",
	9:  "short_id",
	10: "display_name",
}

type RegisterAgentReq struct {
	Email     string  `thrift:"email,1,required" frugal:"1,required,string" json:"email"`
	AgentName *string `thrift:"agent_name,2,optional" frugal:"2,optional,string" json:"agent_name,omitempty"`
	Bio       *string `thrift:"bio,3,optional" frugal:"3,optional,string" json:"bio,omitempty"`
}

func NewRegisterAgentReq() *RegisterAgentReq {
	return &RegisterAgentReq{}
}

func (p *RegisterAgentReq) InitDefault() {
}

func (p *RegisterAgentReq) GetEmail() (v string) {
	return p.Email
}

var RegisterAgentReq_AgentName_DEFAULT string

func (p *RegisterAgentReq) GetAgentName() (v string) {
	if !p.IsSetAgentName() {
		return RegisterAgentReq_AgentName_DEFAULT
	}
	return *p.AgentName
}

var RegisterAgentReq_Bio_DEFAULT string

func (p *RegisterAgentReq) GetBio() (v string) {
	if !p.IsSetBio() {
		return RegisterAgentReq_Bio_DEFAULT
	}
	return *p.Bio
}
func (p *RegisterAgentReq) SetEmail(val string) {
	p.Email = val
}
func (p *RegisterAgentReq) SetAgentName(val *string) {
	p.AgentName = val
}
func (p *RegisterAgentReq) SetBio(val *string) {
	p.Bio = val
}

func (p *RegisterAgentReq) IsSetAgentName() bool {
	return p.AgentName != nil
}

func (p *RegisterAgentReq) IsSetBio() bool {
	return p.Bio != nil
}

func (p *RegisterAgentReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RegisterAgentReq(%+v)", *p)
}

var fieldIDToName_RegisterAgentReq = map[int16]string{
	1: "email",
	2: "agent_name",
	3: "bio",
}

type RegisterAgentResp struct {
	AgentId     int64          `thrift:"agent_id,1,required" frugal:"1,required,i64" json:"agent_id"`
	ShortId     *string        `thrift:"short_id,2,optional" frugal:"2,optional,string" json:"short_id,omitempty"`
	DisplayName *string        `thrift:"display_name,3,optional" frugal:"3,optional,string" json:"display_name,omitempty"`
	BaseResp    *base.BaseResp `thrift:"base_resp,255,required" frugal:"255,required,base.BaseResp" json:"base_resp"`
}

func NewRegisterAgentResp() *RegisterAgentResp {
	return &RegisterAgentResp{}
}

func (p *RegisterAgentResp) InitDefault() {
}

func (p *RegisterAgentResp) GetAgentId() (v int64) {
	return p.AgentId
}

var RegisterAgentResp_ShortId_DEFAULT string

func (p *RegisterAgentResp) GetShortId() (v string) {
	if !p.IsSetShortId() {
		return RegisterAgentResp_ShortId_DEFAULT
	}
	return *p.ShortId
}

var RegisterAgentResp_DisplayName_DEFAULT string

func (p *RegisterAgentResp) GetDisplayName() (v string) {
	if !p.IsSetDisplayName() {
		return RegisterAgentResp_DisplayName_DEFAULT
	}
	return *p.DisplayName
}

var RegisterAgentResp_BaseResp_DEFAULT *base.BaseResp

func (p *RegisterAgentResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return RegisterAgentResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *RegisterAgentResp) SetAgentId(val int64) {
	p.AgentId = val
}
func (p *RegisterAgentResp) SetShortId(val *string) {
	p.ShortId = val
}
func (p *RegisterAgentResp) SetDisplayName(val *string) {
	p.DisplayName = val
}
func (p *RegisterAgentResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *RegisterAgentResp) IsSetShortId() bool {
	return p.ShortId != nil
}

func (p *RegisterAgentResp) IsSetDisplayName() bool {
	return p.DisplayName != nil
}

func (p *RegisterAgentResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *RegisterAgentResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RegisterAgentResp(%+v)", *p)
}

var fieldIDToName_RegisterAgentResp = map[int16]string{
	1:   "agent_id",
	2:   "short_id",
	3:   "display_name",
	255: "base_resp",
}

type UpdateProfileReq struct {
	AgentId   int64   `thrift:"agent_id,1,required" frugal:"1,required,i64" json:"agent_id"`
	AgentName *string `thrift:"agent_name,2,optional" frugal:"2,optional,string" json:"agent_name,omitempty"`
	Bio       *string `thrift:"bio,3,optional" frugal:"3,optional,string" json:"bio,omitempty"`
}

func NewUpdateProfileReq() *UpdateProfileReq {
	return &UpdateProfileReq{}
}

func (p *UpdateProfileReq) InitDefault() {
}

func (p *UpdateProfileReq) GetAgentId() (v int64) {
	return p.AgentId
}

var UpdateProfileReq_AgentName_DEFAULT string

func (p *UpdateProfileReq) GetAgentName() (v string) {
	if !p.IsSetAgentName() {
		return UpdateProfileReq_AgentName_DEFAULT
	}
	return *p.AgentName
}

var UpdateProfileReq_Bio_DEFAULT string

func (p *UpdateProfileReq) GetBio() (v string) {
	if !p.IsSetBio() {
		return UpdateProfileReq_Bio_DEFAULT
	}
	return *p.Bio
}
func (p *UpdateProfileReq) SetAgentId(val int64) {
	p.AgentId = val
}
func (p *UpdateProfileReq) SetAgentName(val *string) {
	p.AgentName = val
}
func (p *UpdateProfileReq) SetBio(val *string) {
	p.Bio = val
}

func (p *UpdateProfileReq) IsSetAgentName() bool {
	return p.AgentName != nil
}

func (p *UpdateProfileReq) IsSetBio() bool {
	return p.Bio != nil
}

func (p *UpdateProfileReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateProfileReq(%+v)", *p)
}

var fieldIDToName_UpdateProfileReq = map[int16]string{
	1: "agent_id",
	2: "agent_name",
	3: "bio",
}

type UpdateProfileResp struct {
	ProfileJustCompleted *bool          `thrift:"profile_just_completed,1,optional" frugal:"1,optional,bool" json:"profile_just_completed,omitempty"`
	BaseResp             *base.BaseResp `thrift:"base_resp,255,required" frugal:"255,required,base.BaseResp" json:"base_resp"`
}

func NewUpdateProfileResp() *UpdateProfileResp {
	return &UpdateProfileResp{}
}

func (p *UpdateProfileResp) InitDefault() {
}

var UpdateProfileResp_ProfileJustCompleted_DEFAULT bool

func (p *UpdateProfileResp) GetProfileJustCompleted() (v bool) {
	if !p.IsSetProfileJustCompleted() {
		return UpdateProfileResp_ProfileJustCompleted_DEFAULT
	}
	return *p.ProfileJustCompleted
}

var UpdateProfileResp_BaseResp_DEFAULT *base.BaseResp

func (p *UpdateProfileResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return UpdateProfileResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *UpdateProfileResp) SetProfileJustCompleted(val *bool) {
	p.ProfileJustCompleted = val
}
func (p *UpdateProfileResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *UpdateProfileResp) IsSetProfileJustCompleted() bool {
	return p.ProfileJustCompleted != nil
}

func (p *UpdateProfileResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *UpdateProfileResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateProfileResp(%+v)", *p)
}

var fieldIDToName_UpdateProfileResp = map[int16]string{
	1:   "profile_just_completed",
	255: "base_resp",
}

type GetAgentReq struct {
	AgentId int64 `thrift:"agent_id,1,required" frugal:"1,required,i64" json:"agent_id"`
}

func NewGetAgentReq() *GetAgentReq {
	return &GetAgentReq{}
}

func (p *GetAgentReq) InitDefault() {
}

func (p *GetAgentReq) GetAgentId() (v int64) {
	return p.AgentId
}
func (p *GetAgentReq) SetAgentId(val int64) {
	p.AgentId = val
}

func (p *GetAgentReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetAgentReq(%+v)", *p)
}

var fieldIDToName_GetAgentReq = map[int16]string{
	1: "agent_id",
}

type InfluenceMetrics struct {
	TotalItems    int64 `thrift:"total_items,1,required" frugal:"1,required,i64" json:"total_items"`
	TotalConsumed int64 `thrift:"total_consumed,2,required" frugal:"2,required,i64" json:"total_consumed"`
	TotalScored_1 int64 `thrift:"total_scored_1,3,required" frugal:"3,required,i64" json:"total_scored_1"`
	TotalScored_2 int64 `thrift:"total_scored_2,4,required" frugal:"4,required,i64" json:"total_scored_2"`
}

func NewInfluenceMetrics() *InfluenceMetrics {
	return &InfluenceMetrics{}
}

func (p *InfluenceMetrics) InitDefault() {
}

func (p *InfluenceMetrics) GetTotalItems() (v int64) {
	return p.TotalItems
}

func (p *InfluenceMetrics) GetTotalConsumed() (v int64) {
	return p.TotalConsumed
}

func (p *InfluenceMetrics) GetTotalScored_1() (v int64) {
	return p.TotalScored_1
}

func (p *InfluenceMetrics) GetTotalScored_2() (v int64) {
	return p.TotalScored_2
}
func (p *InfluenceMetrics) SetTotalItems(val int64) {
	p.TotalItems = val
}
func (p *InfluenceMetrics) SetTotalConsumed(val int64) {
	p.TotalConsumed = val
}
func (p *InfluenceMetrics) SetTotalScored_1(val int64) {
	p.TotalScored_1 = val
}
func (p *InfluenceMetrics) SetTotalScored_2(val int64) {
	p.TotalScored_2 = val
}

func (p *InfluenceMetrics) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("InfluenceMetrics(%+v)", *p)
}

var fieldIDToName_InfluenceMetrics = map[int16]string{
	1: "total_items",
	2: "total_consumed",
	3: "total_scored_1",
	4: "total_scored_2",
}

type GetAgentResp struct {
	Agent     *Agent            `thrift:"agent,1,required" frugal:"1,required,Agent" json:"agent"`
	Influence *InfluenceMetrics `thrift:"influence,2,required" frugal:"2,required,InfluenceMetrics" json:"influence"`
	BaseResp  *base.BaseResp    `thrift:"base_resp,255,required" frugal:"255,required,base.BaseResp" json:"base_resp"`
}

func NewGetAgentResp() *GetAgentResp {
	return &GetAgentResp{}
}

func (p *GetAgentResp) InitDefault() {
}

var GetAgentResp_Agent_DEFAULT *Agent

func (p *GetAgentResp) GetAgent() (v *Agent) {
	if !p.IsSetAgent() {
		return GetAgentResp_Agent_DEFAULT
	}
	return p.Agent
}

var GetAgentResp_Influence_DEFAULT *InfluenceMetrics

func (p *GetAgentResp) GetInfluence() (v *InfluenceMetrics) {
	if !p.IsSetInfluence() {
		return GetAgentResp_Influence_DEFAULT
	}
	return p.Influence
}

var GetAgentResp_BaseResp_DEFAULT *base.BaseResp

func (p *GetAgentResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return GetAgentResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *GetAgentResp) SetAgent(val *Agent) {
	p.Agent = val
}
func (p *GetAgentResp) SetInfluence(val *InfluenceMetrics) {
	p.Influence = val
}
func (p *GetAgentResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *GetAgentResp) IsSetAgent() bool {
	return p.Agent != nil
}

func (p *GetAgentResp) IsSetInfluence() bool {
	return p.Influence != nil
}

func (p *GetAgentResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *GetAgentResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetAgentResp(%+v)", *p)
}

var fieldIDToName_GetAgentResp = map[int16]string{
	1:   "agent",
	2:   "influence",
	255: "base_resp",
}

type MatchAgentsByKeywordsReq struct {
	Keywords       []string `thrift:"keywords,1,required" frugal:"1,required,list<string>" json:"keywords"`
	ExcludeAgentId *int64   `thrift:"exclude_agent_id,2,optional" frugal:"2,optional,i64" json:"exclude_agent_id,omitempty"`
	Limit          *int32   `thrift:"limit,3,optional" frugal:"3,optional,i32" json:"limit,omitempty"`
}

func NewMatchAgentsByKeywordsReq() *MatchAgentsByKeywordsReq {
	return &MatchAgentsByKeywordsReq{}
}

func (p *MatchAgentsByKeywordsReq) InitDefault() {
}

func (p *MatchAgentsByKeywordsReq) GetKeywords() (v []string) {
	return p.Keywords
}

var MatchAgentsByKeywordsReq_ExcludeAgentId_DEFAULT int64

func (p *MatchAgentsByKeywordsReq) GetExcludeAgentId() (v int64) {
	if !p.IsSetExcludeAgentId() {
		return MatchAgentsByKeywordsReq_ExcludeAgentId_DEFAULT
	}
	return *p.ExcludeAgentId
}

var MatchAgentsByKeywordsReq_Limit_DEFAULT int32

func (p *MatchAgentsByKeywordsReq) GetLimit() (v int32) {
	if !p.IsSetLimit() {
		return MatchAgentsByKeywordsReq_Limit_DEFAULT
	}
	return *p.Limit
}
func (p *MatchAgentsByKeywordsReq) SetKeywords(val []string) {
	p.Keywords = val
}
func (p *MatchAgentsByKeywordsReq) SetExcludeAgentId(val *int64) {
	p.ExcludeAgentId = val
}
func (p *MatchAgentsByKeywordsReq) SetLimit(val *int32) {
	p.Limit = val
}

func (p *MatchAgentsByKeywordsReq) IsSetExcludeAgentId() bool {
	return p.ExcludeAgentId != nil
}

func (p *MatchAgentsByKeywordsReq) IsSetLimit() bool {
	return p.Limit != nil
}

func (p *MatchAgentsByKeywordsReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MatchAgentsByKeywordsReq(%+v)", *p)
}

var fieldIDToName_MatchAgentsByKeywordsReq = map[int16]string{
	1: "keywords",
	2: "exclude_agent_id",
	3: "limit",
}

type MatchAgentsByKeywordsResp struct {
	AgentIds []int64        `thrift:"agent_ids,1,required" frugal:"1,required,list<i64>" json:"agent_ids"`
	BaseResp *base.BaseResp `thrift:"base_resp,255,required" frugal:"255,required,base.BaseResp" json:"base_resp"`
}

func NewMatchAgentsByKeywordsResp() *MatchAgentsByKeywordsResp {
	return &MatchAgentsByKeywordsResp{}
}

func (p *MatchAgentsByKeywordsResp) InitDefault() {
}

func (p *MatchAgentsByKeywordsResp) GetAgentIds() (v []int64) {
	return p.AgentIds
}

var MatchAgentsByKeywordsResp_BaseResp_DEFAULT *base.BaseResp

func (p *MatchAgentsByKeywordsResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return MatchAgentsByKeywordsResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *MatchAgentsByKeywordsResp) SetAgentIds(val []int64) {
	p.AgentIds = val
}
func (p *MatchAgentsByKeywordsResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *MatchAgentsByKeywordsResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *MatchAgentsByKeywordsResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MatchAgentsByKeywordsResp(%+v)", *p)
}

var fieldIDToName_MatchAgentsByKeywordsResp = map[int16]string{
	1:   "agent_ids",
	255: "base_resp",
}

type ProfileService interface {
	RegisterAgent(ctx context.Context, req *RegisterAgentReq) (r *RegisterAgentResp, err error)

	UpdateProfile(ctx context.Context, req *UpdateProfileReq) (r *UpdateProfileResp, err error)

	GetAgent(ctx context.Context, req *GetAgentReq) (r *GetAgentResp, err error)

	MatchAgentsByKeywords(ctx context.Context, req *MatchAgentsByKeywordsReq) (r *MatchAgentsByKeywordsResp, err error)
}

type ProfileServiceRegisterAgentArgs struct {
	Req *RegisterAgentReq `thrift:"req,1" frugal:"1,default,RegisterAgentReq" json:"req"`
}

func NewProfileServiceRegisterAgentArgs() *ProfileServiceRegisterAgentArgs {
	return &ProfileServiceRegisterAgentArgs{}
}

func (p *ProfileServiceRegisterAgentArgs) InitDefault() {
}

var ProfileServiceRegisterAgentArgs_Req_DEFAULT *RegisterAgentReq

func (p *ProfileServiceRegisterAgentArgs) GetReq() (v *RegisterAgentReq) {
	if !p.IsSetReq() {
		return ProfileServiceRegisterAgentArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ProfileServiceRegisterAgentArgs) SetReq(val *RegisterAgentReq) {
	p.Req = val
}

func (p *ProfileServiceRegisterAgentArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ProfileServiceRegisterAgentArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProfileServiceRegisterAgentArgs(%+v)", *p)
}

var fieldIDToName_ProfileServiceRegisterAgentArgs = map[int16]string{
	1: "req",
}

type ProfileServiceRegisterAgentResult struct {
	Success *RegisterAgentResp `thrift:"success,0,optional" frugal:"0,optional,RegisterAgentResp" json:"success,omitempty"`
}

func NewProfileServiceRegisterAgentResult() *ProfileServiceRegisterAgentResult {
	return &ProfileServiceRegisterAgentResult{}
}

func (p *ProfileServiceRegisterAgentResult) InitDefault() {
}

var ProfileServiceRegisterAgentResult_Success_DEFAULT *RegisterAgentResp

func (p *ProfileServiceRegisterAgentResult) GetSuccess() (v *RegisterAgentResp) {
	if !p.IsSetSuccess() {
		return ProfileServiceRegisterAgentResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ProfileServiceRegisterAgentResult) SetSuccess(x interface{}) {
	p.Success = x.(*RegisterAgentResp)
}

func (p *ProfileServiceRegisterAgentResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ProfileServiceRegisterAgentResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProfileServiceRegisterAgentResult(%+v)", *p)
}

var fieldIDToName_ProfileServiceRegisterAgentResult = map[int16]string{
	0: "success",
}

type ProfileServiceUpdateProfileArgs struct {
	Req *UpdateProfileReq `thrift:"req,1" frugal:"1,default,UpdateProfileReq" json:"req"`
}

func NewProfileServiceUpdateProfileArgs() *ProfileServiceUpdateProfileArgs {
	return &ProfileServiceUpdateProfileArgs{}
}

func (p *ProfileServiceUpdateProfileArgs) InitDefault() {
}

var ProfileServiceUpdateProfileArgs_Req_DEFAULT *UpdateProfileReq

func (p *ProfileServiceUpdateProfileArgs) GetReq() (v *UpdateProfileReq) {
	if !p.IsSetReq() {
		return ProfileServiceUpdateProfileArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ProfileServiceUpdateProfileArgs) SetReq(val *UpdateProfileReq) {
	p.Req = val
}

func (p *ProfileServiceUpdateProfileArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ProfileServiceUpdateProfileArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProfileServiceUpdateProfileArgs(%+v)", *p)
}

var fieldIDToName_ProfileServiceUpdateProfileArgs = map[int16]string{
	1: "req",
}

type ProfileServiceUpdateProfileResult struct {
	Success *UpdateProfileResp `thrift:"success,0,optional" frugal:"0,optional,UpdateProfileResp" json:"success,omitempty"`
}

func NewProfileServiceUpdateProfileResult() *ProfileServiceUpdateProfileResult {
	return &ProfileServiceUpdateProfileResult{}
}

func (p *ProfileServiceUpdateProfileResult) InitDefault() {
}

var ProfileServiceUpdateProfileResult_Success_DEFAULT *UpdateProfileResp

func (p *ProfileServiceUpdateProfileResult) GetSuccess() (v *UpdateProfileResp) {
	if !p.IsSetSuccess() {
		return ProfileServiceUpdateProfileResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ProfileServiceUpdateProfileResult) SetSuccess(x interface{}) {
	p.Success = x.(*UpdateProfileResp)
}

func (p *ProfileServiceUpdateProfileResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ProfileServiceUpdateProfileResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProfileServiceUpdateProfileResult(%+v)", *p)
}

var fieldIDToName_ProfileServiceUpdateProfileResult = map[int16]string{
	0: "success",
}

type ProfileServiceGetAgentArgs struct {
	Req *GetAgentReq `thrift:"req,1" frugal:"1,default,GetAgentReq" json:"req"`
}

func NewProfileServiceGetAgentArgs() *ProfileServiceGetAgentArgs {
	return &ProfileServiceGetAgentArgs{}
}

func (p *ProfileServiceGetAgentArgs) InitDefault() {
}

var ProfileServiceGetAgentArgs_Req_DEFAULT *GetAgentReq

func (p *ProfileServiceGetAgentArgs) GetReq() (v *GetAgentReq) {
	if !p.IsSetReq() {
		return ProfileServiceGetAgentArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ProfileServiceGetAgentArgs) SetReq(val *GetAgentReq) {
	p.Req = val
}

func (p *ProfileServiceGetAgentArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ProfileServiceGetAgentArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProfileServiceGetAgentArgs(%+v)", *p)
}

var fieldIDToName_ProfileServiceGetAgentArgs = map[int16]string{
	1: "req",
}

type ProfileServiceGetAgentResult struct {
	Success *GetAgentResp `thrift:"success,0,optional" frugal:"0,optional,GetAgentResp" json:"success,omitempty"`
}

func NewProfileServiceGetAgentResult() *ProfileServiceGetAgentResult {
	return &ProfileServiceGetAgentResult{}
}

func (p *ProfileServiceGetAgentResult) InitDefault() {
}

var ProfileServiceGetAgentResult_Success_DEFAULT *GetAgentResp

func (p *ProfileServiceGetAgentResult) GetSuccess() (v *GetAgentResp) {
	if !p.IsSetSuccess() {
		return ProfileServiceGetAgentResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ProfileServiceGetAgentResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetAgentResp)
}

func (p *ProfileServiceGetAgentResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ProfileServiceGetAgentResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProfileServiceGetAgentResult(%+v)", *p)
}

var fieldIDToName_ProfileServiceGetAgentResult = map[int16]string{
	0: "success",
}

type ProfileServiceMatchAgentsByKeywordsArgs struct {
	Req *MatchAgentsByKeywordsReq `thrift:"req,1" frugal:"1,default,MatchAgentsByKeywordsReq" json:"req"`
}

func NewProfileServiceMatchAgentsByKeywordsArgs() *ProfileServiceMatchAgentsByKeywordsArgs {
	return &ProfileServiceMatchAgentsByKeywordsArgs{}
}

func (p *ProfileServiceMatchAgentsByKeywordsArgs) InitDefault() {
}

var ProfileServiceMatchAgentsByKeywordsArgs_Req_DEFAULT *MatchAgentsByKeywordsReq

func (p *ProfileServiceMatchAgentsByKeywordsArgs) GetReq() (v *MatchAgentsByKeywordsReq) {
	if !p.IsSetReq() {
		return ProfileServiceMatchAgentsByKeywordsArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *ProfileServiceMatchAgentsByKeywordsArgs) SetReq(val *MatchAgentsByKeywordsReq) {
	p.Req = val
}

func (p *ProfileServiceMatchAgentsByKeywordsArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ProfileServiceMatchAgentsByKeywordsArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProfileServiceMatchAgentsByKeywordsArgs(%+v)", *p)
}

var fieldIDToName_ProfileServiceMatchAgentsByKeywordsArgs = map[int16]string{
	1: "req",
}

type ProfileServiceMatchAgentsByKeywordsResult struct {
	Success *MatchAgentsByKeywordsResp `thrift:"success,0,optional" frugal:"0,optional,MatchAgentsByKeywordsResp" json:"success,omitempty"`
}

func NewProfileServiceMatchAgentsByKeywordsResult() *ProfileServiceMatchAgentsByKeywordsResult {
	return &ProfileServiceMatchAgentsByKeywordsResult{}
}

func (p *ProfileServiceMatchAgentsByKeywordsResult) InitDefault() {
}

var ProfileServiceMatchAgentsByKeywordsResult_Success_DEFAULT *MatchAgentsByKeywordsResp

func (p *ProfileServiceMatchAgentsByKeywordsResult) GetSuccess() (v *MatchAgentsByKeywordsResp) {
	if !p.IsSetSuccess() {
		return ProfileServiceMatchAgentsByKeywordsResult_Success_DEFAULT
	}
	return p.Success
}
func (p *ProfileServiceMatchAgentsByKeywordsResult) SetSuccess(x interface{}) {
	p.Success = x.(*MatchAgentsByKeywordsResp)
}

func (p *ProfileServiceMatchAgentsByKeywordsResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ProfileServiceMatchAgentsByKeywordsResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ProfileServiceMatchAgentsByKeywordsResult(%+v)", *p)
}

var fieldIDToName_ProfileServiceMatchAgentsByKeywordsResult = map[int16]string{
	0: "success",
}
