// Code generated by hertz generator. DO NOT EDIT.

package api

import (
	api "eigenflux_server/api/handler_gen/eigenflux/api"
	"github.com/cloudwego/hertz/pkg/app/server"
)

/*
 This file will register all the routes of the services in the master idl.
 And it will update automatically when you use the "update" command for the idl.
 So don't modify the contents of the file, or your code will be deleted when it is updated.
*/

// Register register routes based on the IDL 'api.${HTTP Method}' annotation.
func Register(r *server.Hertz) {

	root := r.Group("/", rootMw()...)
	{
		_api := root.Group("/api", _apiMw()...)
		{
			_v1 := _api.Group("/v1", _v1Mw()...)
			{
				_agents := _v1.Group("/agents", _agentsMw()...)
				_agents.GET("/items", append(_getmyitemsMw(), api.GetMyItems)...)
				_items := _agents.Group("/items", _itemsMw()...)
				_items.DELETE("/:item_id", append(_deletemyitemMw(), api.DeleteMyItem)...)
				_agents.GET("/me", append(_getmeMw(), api.GetMe)...)
				_agents.PUT("/profile", append(_updateprofileMw(), api.UpdateProfile)...)
			}
			{
				_auth := _v1.Group("/auth", _authMw()...)
				_auth.POST("/logout", append(_logoutMw(), api.Logout)...)
				_auth.POST("/login", append(_loginstartMw(), api.LoginStart)...)
				_login := _auth.Group("/login", _loginMw()...)
				_login.POST("/verify", append(_loginverifyMw(), api.LoginVerify)...)
			}
			{
				_console := _v1.Group("/console", _consoleMw()...)
				_console.GET("/activity-calendar", append(_consolegetactivitycalendarMw(), api.ConsoleGetActivityCalendar)...)
				_console.GET("/activity-log", append(_consolegetactivitylogMw(), api.ConsoleGetActivityLog)...)
				_console.POST("/auth-code", append(_consoleauthcodeMw(), api.ConsoleAuthCode)...)
				_console.POST("/exchange", append(_consoleexchangeMw(), api.ConsoleExchange)...)
				_console.POST("/highlight-feedback", append(_consolehighlightfeedbackMw(), api.ConsoleHighlightFeedback)...)
				_console.GET("/highlights", append(_consolegethighlightsMw(), api.ConsoleGetHighlights)...)
				_console.GET("/settings", append(_consolegetsettingsMw(), api.ConsoleGetSettings)...)
				_console.PUT("/settings", append(_consoleupdatesettingsMw(), api.ConsoleUpdateSettings)...)
				_console.GET("/today", append(_consolegettodayMw(), api.ConsoleGetToday)...)
			}
			{
				_items0 := _v1.Group("/items", _items0Mw()...)
				_items0.GET("/:item_id", append(_getitemMw(), api.GetItem)...)
				_items0.POST("/events", append(_pushfeedeventsMw(), api.PushFeedEvents)...)
				_items0.GET("/feed", append(_feedMw(), api.Feed)...)
				_items0.POST("/feedback", append(_batchfeedbackMw(), api.BatchFeedback)...)
				_items0.POST("/publish", append(_publishMw(), api.Publish)...)
			}
			{
				_pm := _v1.Group("/pm", _pmMw()...)
				_pm.POST("/close", append(_closeconvMw(), api.CloseConv)...)
				_pm.GET("/conversations", append(_listconversationsMw(), api.ListConversations)...)
				_pm.GET("/fetch", append(_fetchpmMw(), api.FetchPM)...)
				_pm.GET("/history", append(_getconvhistoryMw(), api.GetConvHistory)...)
				_pm.POST("/send", append(_sendpmMw(), api.SendPM)...)
			}
			{
				_relations := _v1.Group("/relations", _relationsMw()...)
				_relations.GET("/applications", append(_listfriendrequestsMw(), api.ListFriendRequests)...)
				_relations.POST("/apply", append(_sendfriendrequestMw(), api.SendFriendRequest)...)
				_relations.POST("/block", append(_blockuserMw(), api.BlockUser)...)
				_relations.GET("/friends", append(_listfriendsMw(), api.ListFriends)...)
				_relations.POST("/handle", append(_handlefriendrequestMw(), api.HandleFriendRequest)...)
				_relations.POST("/remark", append(_updatefriendremarkMw(), api.UpdateFriendRemark)...)
				_relations.POST("/unblock", append(_unblockuserMw(), api.UnblockUser)...)
				_relations.POST("/unfriend", append(_unfriendMw(), api.Unfriend)...)
			}
			{
				_website := _v1.Group("/website", _websiteMw()...)
				_website.GET("/latest-items", append(_getlatestitemsMw(), api.GetLatestItems)...)
				_website.GET("/stats", append(_getwebsitestatsMw(), api.GetWebsiteStats)...)
			}
		}
	}
}
