// Code generated by hertz generator.

// @title           eigenflux_server Console API
// @version         1.0
// @description     EigenFlux Console API for querying and managing agents and items
// @host            localhost:8090
// @BasePath        /

package main

import (
	"context"
	"log"
	"os"
	"strings"

	"github.com/cloudwego/hertz/pkg/app"

	_ "console.eigenflux.ai/docs"
	consoleHandler "console.eigenflux.ai/handler_gen/eigenflux/console"
	"console.eigenflux.ai/internal/config"
	"console.eigenflux.ai/internal/dashboard"
	"console.eigenflux.ai/internal/metrics"
	"console.eigenflux.ai/internal/db"
	"console.eigenflux.ai/internal/idgen"
	"console.eigenflux.ai/internal/logger"
	"console.eigenflux.ai/internal/notification"
	"console.eigenflux.ai/internal/telemetry"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/hertz-contrib/cors"
	hertztracing "github.com/hertz-contrib/obs-opentelemetry/tracing"
	hertzSwagger "github.com/hertz-contrib/swagger"
	swaggerFiles "github.com/swaggo/files"
	oteltrace "go.opentelemetry.io/otel/trace"
)

func main() {
	cfg := config.Load()
	logFlush := logger.Init("console-api", cfg.EffectiveLokiURL(), cfg.LogLevel)
	defer logFlush()

	shutdown, err := telemetry.Init("console-api", cfg.OtelExporterEndpoint, cfg.MonitorEnabled)
	if err != nil {
		log.Fatalf("failed to init telemetry: %v", err)
	}
	defer shutdown(context.Background())

	go metrics.StartMetricsServer(9091)

	db.InitPostgres(cfg.PgDSN)
	log.Println("PostgreSQL connected")

	db.InitRedis(cfg.RedisAddr, cfg.RedisPassword)
	log.Println("Redis connected")

	etcdEndpoints := config.EtcdEndpoints(cfg.EtcdAddr)
	notifIDGen, err := idgen.NewManagedGenerator(context.Background(), idgen.ManagedGeneratorConfig{
		Endpoints:      etcdEndpoints,
		WorkerPrefix:   cfg.IDWorkerPrefix,
		ServiceName:    "console-notif-id",
		InstanceID:     cfg.IDInstanceID,
		LeaseTTLSecond: cfg.IDWorkerLeaseTTL,
		EpochMS:        cfg.IDSnowflakeEpoch,
	})
	if err != nil {
		log.Fatalf("failed to init notification id generator: %v", err)
	}
	defer func() { _ = notifIDGen.Close(context.Background()) }()
	consoleHandler.InitNotificationService(notifIDGen)

	notifSvc := notification.NewService(db.DB, db.RDB)
	if recoverErr := notifSvc.RecoverActiveNotifications(context.Background()); recoverErr != nil {
		log.Printf("[console] Warning: failed to recover active notifications: %v", recoverErr)
	}

	// Start dashboard snapshot cron
	dashCtx, dashCancel := context.WithCancel(context.Background())
	defer dashCancel()
	go dashboard.StartSnapshotCron(dashCtx, db.DB, db.RDB)

	tracer, tracerCfg := hertztracing.NewServerTracer()
	h := server.Default(
		server.WithHostPorts(cfg.ListenAddr()),
		tracer,
	)
	h.Use(hertztracing.ServerMiddleware(tracerCfg))
	h.Use(traceIDMiddleware())
	h.Use(metrics.HertzMiddleware())

	allowOrigins := parseAllowOrigins()
	h.Use(cors.New(cors.Config{
		AllowOrigins:     allowOrigins,
		AllowMethods:     []string{"GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"},
		AllowHeaders:     []string{"Origin", "Content-Type", "Accept"},
		AllowCredentials: false,
	}))

	h.GET("/swagger/*any", hertzSwagger.WrapHandler(swaggerFiles.Handler))

	register(h)

	log.Printf("Console API gateway starting on %s", cfg.ListenAddr())
	h.Spin()
}

func traceIDMiddleware() app.HandlerFunc {
	return func(ctx context.Context, c *app.RequestContext) {
		c.Next(ctx)
		sc := oteltrace.SpanFromContext(ctx).SpanContext()
		if sc.HasTraceID() {
			c.Header("X-Trace-Id", sc.TraceID().String())
		}
	}
}

func parseAllowOrigins() []string {
	raw := strings.TrimSpace(os.Getenv("CONSOLE_CORS_ALLOW_ORIGINS"))
	if raw == "" {
		return []string{"*"}
	}
	parts := strings.Split(raw, ",")
	origins := make([]string, 0, len(parts))
	for _, part := range parts {
		origin := strings.TrimSpace(part)
		if origin != "" {
			origins = append(origins, origin)
		}
	}
	if len(origins) == 0 {
		return []string{"*"}
	}
	return origins
}
