// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package auth

import (
	"context"
	"eigenflux_server/kitex_gen/eigenflux/base"
	"fmt"
)

type StartLoginReq struct {
	LoginMethod string  `thrift:"login_method,1,required" frugal:"1,required,string" json:"login_method"`
	Email       string  `thrift:"email,2,required" frugal:"2,required,string" json:"email"`
	ClientIp    *string `thrift:"client_ip,3,optional" frugal:"3,optional,string" json:"client_ip,omitempty"`
	UserAgent   *string `thrift:"user_agent,4,optional" frugal:"4,optional,string" json:"user_agent,omitempty"`
}

func NewStartLoginReq() *StartLoginReq {
	return &StartLoginReq{}
}

func (p *StartLoginReq) InitDefault() {
}

func (p *StartLoginReq) GetLoginMethod() (v string) {
	return p.LoginMethod
}

func (p *StartLoginReq) GetEmail() (v string) {
	return p.Email
}

var StartLoginReq_ClientIp_DEFAULT string

func (p *StartLoginReq) GetClientIp() (v string) {
	if !p.IsSetClientIp() {
		return StartLoginReq_ClientIp_DEFAULT
	}
	return *p.ClientIp
}

var StartLoginReq_UserAgent_DEFAULT string

func (p *StartLoginReq) GetUserAgent() (v string) {
	if !p.IsSetUserAgent() {
		return StartLoginReq_UserAgent_DEFAULT
	}
	return *p.UserAgent
}
func (p *StartLoginReq) SetLoginMethod(val string) {
	p.LoginMethod = val
}
func (p *StartLoginReq) SetEmail(val string) {
	p.Email = val
}
func (p *StartLoginReq) SetClientIp(val *string) {
	p.ClientIp = val
}
func (p *StartLoginReq) SetUserAgent(val *string) {
	p.UserAgent = val
}

func (p *StartLoginReq) IsSetClientIp() bool {
	return p.ClientIp != nil
}

func (p *StartLoginReq) IsSetUserAgent() bool {
	return p.UserAgent != nil
}

func (p *StartLoginReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("StartLoginReq(%+v)", *p)
}

var fieldIDToName_StartLoginReq = map[int16]string{
	1: "login_method",
	2: "email",
	3: "client_ip",
	4: "user_agent",
}

type StartLoginResp struct {
	ChallengeId            *string        `thrift:"challenge_id,1,optional" frugal:"1,optional,string" json:"challenge_id,omitempty"`
	ExpiresInSec           *int32         `thrift:"expires_in_sec,2,optional" frugal:"2,optional,i32" json:"expires_in_sec,omitempty"`
	ResendAfterSec         *int32         `thrift:"resend_after_sec,3,optional" frugal:"3,optional,i32" json:"resend_after_sec,omitempty"`
	AgentId                *int64         `thrift:"agent_id,4,optional" frugal:"4,optional,i64" json:"agent_id,omitempty"`
	AccessToken            *string        `thrift:"access_token,5,optional" frugal:"5,optional,string" json:"access_token,omitempty"`
	ExpiresAt              *int64         `thrift:"expires_at,6,optional" frugal:"6,optional,i64" json:"expires_at,omitempty"`
	IsNewAgent             *bool          `thrift:"is_new_agent,7,optional" frugal:"7,optional,bool" json:"is_new_agent,omitempty"`
	NeedsProfileCompletion *bool          `thrift:"needs_profile_completion,8,optional" frugal:"8,optional,bool" json:"needs_profile_completion,omitempty"`
	ProfileCompletedAt     *int64         `thrift:"profile_completed_at,9,optional" frugal:"9,optional,i64" json:"profile_completed_at,omitempty"`
	VerificationRequired   *bool          `thrift:"verification_required,10,optional" frugal:"10,optional,bool" json:"verification_required,omitempty"`
	BaseResp               *base.BaseResp `thrift:"base_resp,255,required" frugal:"255,required,base.BaseResp" json:"base_resp"`
}

func NewStartLoginResp() *StartLoginResp {
	return &StartLoginResp{}
}

func (p *StartLoginResp) InitDefault() {
}

var StartLoginResp_ChallengeId_DEFAULT string

func (p *StartLoginResp) GetChallengeId() (v string) {
	if !p.IsSetChallengeId() {
		return StartLoginResp_ChallengeId_DEFAULT
	}
	return *p.ChallengeId
}

var StartLoginResp_ExpiresInSec_DEFAULT int32

func (p *StartLoginResp) GetExpiresInSec() (v int32) {
	if !p.IsSetExpiresInSec() {
		return StartLoginResp_ExpiresInSec_DEFAULT
	}
	return *p.ExpiresInSec
}

var StartLoginResp_ResendAfterSec_DEFAULT int32

func (p *StartLoginResp) GetResendAfterSec() (v int32) {
	if !p.IsSetResendAfterSec() {
		return StartLoginResp_ResendAfterSec_DEFAULT
	}
	return *p.ResendAfterSec
}

var StartLoginResp_AgentId_DEFAULT int64

func (p *StartLoginResp) GetAgentId() (v int64) {
	if !p.IsSetAgentId() {
		return StartLoginResp_AgentId_DEFAULT
	}
	return *p.AgentId
}

var StartLoginResp_AccessToken_DEFAULT string

func (p *StartLoginResp) GetAccessToken() (v string) {
	if !p.IsSetAccessToken() {
		return StartLoginResp_AccessToken_DEFAULT
	}
	return *p.AccessToken
}

var StartLoginResp_ExpiresAt_DEFAULT int64

func (p *StartLoginResp) GetExpiresAt() (v int64) {
	if !p.IsSetExpiresAt() {
		return StartLoginResp_ExpiresAt_DEFAULT
	}
	return *p.ExpiresAt
}

var StartLoginResp_IsNewAgent_DEFAULT bool

func (p *StartLoginResp) GetIsNewAgent() (v bool) {
	if !p.IsSetIsNewAgent() {
		return StartLoginResp_IsNewAgent_DEFAULT
	}
	return *p.IsNewAgent
}

var StartLoginResp_NeedsProfileCompletion_DEFAULT bool

func (p *StartLoginResp) GetNeedsProfileCompletion() (v bool) {
	if !p.IsSetNeedsProfileCompletion() {
		return StartLoginResp_NeedsProfileCompletion_DEFAULT
	}
	return *p.NeedsProfileCompletion
}

var StartLoginResp_ProfileCompletedAt_DEFAULT int64

func (p *StartLoginResp) GetProfileCompletedAt() (v int64) {
	if !p.IsSetProfileCompletedAt() {
		return StartLoginResp_ProfileCompletedAt_DEFAULT
	}
	return *p.ProfileCompletedAt
}

var StartLoginResp_VerificationRequired_DEFAULT bool

func (p *StartLoginResp) GetVerificationRequired() (v bool) {
	if !p.IsSetVerificationRequired() {
		return StartLoginResp_VerificationRequired_DEFAULT
	}
	return *p.VerificationRequired
}

var StartLoginResp_BaseResp_DEFAULT *base.BaseResp

func (p *StartLoginResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return StartLoginResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *StartLoginResp) SetChallengeId(val *string) {
	p.ChallengeId = val
}
func (p *StartLoginResp) SetExpiresInSec(val *int32) {
	p.ExpiresInSec = val
}
func (p *StartLoginResp) SetResendAfterSec(val *int32) {
	p.ResendAfterSec = val
}
func (p *StartLoginResp) SetAgentId(val *int64) {
	p.AgentId = val
}
func (p *StartLoginResp) SetAccessToken(val *string) {
	p.AccessToken = val
}
func (p *StartLoginResp) SetExpiresAt(val *int64) {
	p.ExpiresAt = val
}
func (p *StartLoginResp) SetIsNewAgent(val *bool) {
	p.IsNewAgent = val
}
func (p *StartLoginResp) SetNeedsProfileCompletion(val *bool) {
	p.NeedsProfileCompletion = val
}
func (p *StartLoginResp) SetProfileCompletedAt(val *int64) {
	p.ProfileCompletedAt = val
}
func (p *StartLoginResp) SetVerificationRequired(val *bool) {
	p.VerificationRequired = val
}
func (p *StartLoginResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *StartLoginResp) IsSetChallengeId() bool {
	return p.ChallengeId != nil
}

func (p *StartLoginResp) IsSetExpiresInSec() bool {
	return p.ExpiresInSec != nil
}

func (p *StartLoginResp) IsSetResendAfterSec() bool {
	return p.ResendAfterSec != nil
}

func (p *StartLoginResp) IsSetAgentId() bool {
	return p.AgentId != nil
}

func (p *StartLoginResp) IsSetAccessToken() bool {
	return p.AccessToken != nil
}

func (p *StartLoginResp) IsSetExpiresAt() bool {
	return p.ExpiresAt != nil
}

func (p *StartLoginResp) IsSetIsNewAgent() bool {
	return p.IsNewAgent != nil
}

func (p *StartLoginResp) IsSetNeedsProfileCompletion() bool {
	return p.NeedsProfileCompletion != nil
}

func (p *StartLoginResp) IsSetProfileCompletedAt() bool {
	return p.ProfileCompletedAt != nil
}

func (p *StartLoginResp) IsSetVerificationRequired() bool {
	return p.VerificationRequired != nil
}

func (p *StartLoginResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *StartLoginResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("StartLoginResp(%+v)", *p)
}

var fieldIDToName_StartLoginResp = map[int16]string{
	1:   "challenge_id",
	2:   "expires_in_sec",
	3:   "resend_after_sec",
	4:   "agent_id",
	5:   "access_token",
	6:   "expires_at",
	7:   "is_new_agent",
	8:   "needs_profile_completion",
	9:   "profile_completed_at",
	10:  "verification_required",
	255: "base_resp",
}

type VerifyLoginReq struct {
	LoginMethod string  `thrift:"login_method,1,required" frugal:"1,required,string" json:"login_method"`
	ChallengeId string  `thrift:"challenge_id,2,required" frugal:"2,required,string" json:"challenge_id"`
	Code        *string `thrift:"code,3,optional" frugal:"3,optional,string" json:"code,omitempty"`
	ClientIp    *string `thrift:"client_ip,5,optional" frugal:"5,optional,string" json:"client_ip,omitempty"`
	UserAgent   *string `thrift:"user_agent,6,optional" frugal:"6,optional,string" json:"user_agent,omitempty"`
}

func NewVerifyLoginReq() *VerifyLoginReq {
	return &VerifyLoginReq{}
}

func (p *VerifyLoginReq) InitDefault() {
}

func (p *VerifyLoginReq) GetLoginMethod() (v string) {
	return p.LoginMethod
}

func (p *VerifyLoginReq) GetChallengeId() (v string) {
	return p.ChallengeId
}

var VerifyLoginReq_Code_DEFAULT string

func (p *VerifyLoginReq) GetCode() (v string) {
	if !p.IsSetCode() {
		return VerifyLoginReq_Code_DEFAULT
	}
	return *p.Code
}

var VerifyLoginReq_ClientIp_DEFAULT string

func (p *VerifyLoginReq) GetClientIp() (v string) {
	if !p.IsSetClientIp() {
		return VerifyLoginReq_ClientIp_DEFAULT
	}
	return *p.ClientIp
}

var VerifyLoginReq_UserAgent_DEFAULT string

func (p *VerifyLoginReq) GetUserAgent() (v string) {
	if !p.IsSetUserAgent() {
		return VerifyLoginReq_UserAgent_DEFAULT
	}
	return *p.UserAgent
}
func (p *VerifyLoginReq) SetLoginMethod(val string) {
	p.LoginMethod = val
}
func (p *VerifyLoginReq) SetChallengeId(val string) {
	p.ChallengeId = val
}
func (p *VerifyLoginReq) SetCode(val *string) {
	p.Code = val
}
func (p *VerifyLoginReq) SetClientIp(val *string) {
	p.ClientIp = val
}
func (p *VerifyLoginReq) SetUserAgent(val *string) {
	p.UserAgent = val
}

func (p *VerifyLoginReq) IsSetCode() bool {
	return p.Code != nil
}

func (p *VerifyLoginReq) IsSetClientIp() bool {
	return p.ClientIp != nil
}

func (p *VerifyLoginReq) IsSetUserAgent() bool {
	return p.UserAgent != nil
}

func (p *VerifyLoginReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VerifyLoginReq(%+v)", *p)
}

var fieldIDToName_VerifyLoginReq = map[int16]string{
	1: "login_method",
	2: "challenge_id",
	3: "code",
	5: "client_ip",
	6: "user_agent",
}

type VerifyLoginResp struct {
	AgentId                int64          `thrift:"agent_id,1,required" frugal:"1,required,i64" json:"agent_id"`
	AccessToken            string         `thrift:"access_token,2,required" frugal:"2,required,string" json:"access_token"`
	ExpiresAt              int64          `thrift:"expires_at,3,required" frugal:"3,required,i64" json:"expires_at"`
	IsNewAgent             bool           `thrift:"is_new_agent,4,required" frugal:"4,required,bool" json:"is_new_agent"`
	NeedsProfileCompletion bool           `thrift:"needs_profile_completion,5,required" frugal:"5,required,bool" json:"needs_profile_completion"`
	ProfileCompletedAt     *int64         `thrift:"profile_completed_at,6,optional" frugal:"6,optional,i64" json:"profile_completed_at,omitempty"`
	BaseResp               *base.BaseResp `thrift:"base_resp,255,required" frugal:"255,required,base.BaseResp" json:"base_resp"`
}

func NewVerifyLoginResp() *VerifyLoginResp {
	return &VerifyLoginResp{}
}

func (p *VerifyLoginResp) InitDefault() {
}

func (p *VerifyLoginResp) GetAgentId() (v int64) {
	return p.AgentId
}

func (p *VerifyLoginResp) GetAccessToken() (v string) {
	return p.AccessToken
}

func (p *VerifyLoginResp) GetExpiresAt() (v int64) {
	return p.ExpiresAt
}

func (p *VerifyLoginResp) GetIsNewAgent() (v bool) {
	return p.IsNewAgent
}

func (p *VerifyLoginResp) GetNeedsProfileCompletion() (v bool) {
	return p.NeedsProfileCompletion
}

var VerifyLoginResp_ProfileCompletedAt_DEFAULT int64

func (p *VerifyLoginResp) GetProfileCompletedAt() (v int64) {
	if !p.IsSetProfileCompletedAt() {
		return VerifyLoginResp_ProfileCompletedAt_DEFAULT
	}
	return *p.ProfileCompletedAt
}

var VerifyLoginResp_BaseResp_DEFAULT *base.BaseResp

func (p *VerifyLoginResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return VerifyLoginResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *VerifyLoginResp) SetAgentId(val int64) {
	p.AgentId = val
}
func (p *VerifyLoginResp) SetAccessToken(val string) {
	p.AccessToken = val
}
func (p *VerifyLoginResp) SetExpiresAt(val int64) {
	p.ExpiresAt = val
}
func (p *VerifyLoginResp) SetIsNewAgent(val bool) {
	p.IsNewAgent = val
}
func (p *VerifyLoginResp) SetNeedsProfileCompletion(val bool) {
	p.NeedsProfileCompletion = val
}
func (p *VerifyLoginResp) SetProfileCompletedAt(val *int64) {
	p.ProfileCompletedAt = val
}
func (p *VerifyLoginResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *VerifyLoginResp) IsSetProfileCompletedAt() bool {
	return p.ProfileCompletedAt != nil
}

func (p *VerifyLoginResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *VerifyLoginResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VerifyLoginResp(%+v)", *p)
}

var fieldIDToName_VerifyLoginResp = map[int16]string{
	1:   "agent_id",
	2:   "access_token",
	3:   "expires_at",
	4:   "is_new_agent",
	5:   "needs_profile_completion",
	6:   "profile_completed_at",
	255: "base_resp",
}

type ValidateSessionReq struct {
	AccessToken string `thrift:"access_token,1,required" frugal:"1,required,string" json:"access_token"`
}

func NewValidateSessionReq() *ValidateSessionReq {
	return &ValidateSessionReq{}
}

func (p *ValidateSessionReq) InitDefault() {
}

func (p *ValidateSessionReq) GetAccessToken() (v string) {
	return p.AccessToken
}
func (p *ValidateSessionReq) SetAccessToken(val string) {
	p.AccessToken = val
}

func (p *ValidateSessionReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ValidateSessionReq(%+v)", *p)
}

var fieldIDToName_ValidateSessionReq = map[int16]string{
	1: "access_token",
}

type ValidateSessionResp struct {
	AgentId  int64          `thrift:"agent_id,1,required" frugal:"1,required,i64" json:"agent_id"`
	Email    *string        `thrift:"email,2,optional" frugal:"2,optional,string" json:"email,omitempty"`
	BaseResp *base.BaseResp `thrift:"base_resp,255,required" frugal:"255,required,base.BaseResp" json:"base_resp"`
}

func NewValidateSessionResp() *ValidateSessionResp {
	return &ValidateSessionResp{}
}

func (p *ValidateSessionResp) InitDefault() {
}

func (p *ValidateSessionResp) GetAgentId() (v int64) {
	return p.AgentId
}

var ValidateSessionResp_Email_DEFAULT string

func (p *ValidateSessionResp) GetEmail() (v string) {
	if !p.IsSetEmail() {
		return ValidateSessionResp_Email_DEFAULT
	}
	return *p.Email
}

var ValidateSessionResp_BaseResp_DEFAULT *base.BaseResp

func (p *ValidateSessionResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return ValidateSessionResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *ValidateSessionResp) SetAgentId(val int64) {
	p.AgentId = val
}
func (p *ValidateSessionResp) SetEmail(val *string) {
	p.Email = val
}
func (p *ValidateSessionResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *ValidateSessionResp) IsSetEmail() bool {
	return p.Email != nil
}

func (p *ValidateSessionResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *ValidateSessionResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ValidateSessionResp(%+v)", *p)
}

var fieldIDToName_ValidateSessionResp = map[int16]string{
	1:   "agent_id",
	2:   "email",
	255: "base_resp",
}

type LogoutReq struct {
	AccessToken string `thrift:"access_token,1,required" frugal:"1,required,string" json:"access_token"`
}

func NewLogoutReq() *LogoutReq {
	return &LogoutReq{}
}

func (p *LogoutReq) InitDefault() {
}

func (p *LogoutReq) GetAccessToken() (v string) {
	return p.AccessToken
}
func (p *LogoutReq) SetAccessToken(val string) {
	p.AccessToken = val
}

func (p *LogoutReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LogoutReq(%+v)", *p)
}

var fieldIDToName_LogoutReq = map[int16]string{
	1: "access_token",
}

type LogoutResp struct {
	BaseResp *base.BaseResp `thrift:"base_resp,255,required" frugal:"255,required,base.BaseResp" json:"base_resp"`
}

func NewLogoutResp() *LogoutResp {
	return &LogoutResp{}
}

func (p *LogoutResp) InitDefault() {
}

var LogoutResp_BaseResp_DEFAULT *base.BaseResp

func (p *LogoutResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return LogoutResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *LogoutResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *LogoutResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *LogoutResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LogoutResp(%+v)", *p)
}

var fieldIDToName_LogoutResp = map[int16]string{
	255: "base_resp",
}

type AuthService interface {
	StartLogin(ctx context.Context, req *StartLoginReq) (r *StartLoginResp, err error)

	VerifyLogin(ctx context.Context, req *VerifyLoginReq) (r *VerifyLoginResp, err error)

	ValidateSession(ctx context.Context, req *ValidateSessionReq) (r *ValidateSessionResp, err error)

	Logout(ctx context.Context, req *LogoutReq) (r *LogoutResp, err error)
}

type AuthServiceStartLoginArgs struct {
	Req *StartLoginReq `thrift:"req,1" frugal:"1,default,StartLoginReq" json:"req"`
}

func NewAuthServiceStartLoginArgs() *AuthServiceStartLoginArgs {
	return &AuthServiceStartLoginArgs{}
}

func (p *AuthServiceStartLoginArgs) InitDefault() {
}

var AuthServiceStartLoginArgs_Req_DEFAULT *StartLoginReq

func (p *AuthServiceStartLoginArgs) GetReq() (v *StartLoginReq) {
	if !p.IsSetReq() {
		return AuthServiceStartLoginArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AuthServiceStartLoginArgs) SetReq(val *StartLoginReq) {
	p.Req = val
}

func (p *AuthServiceStartLoginArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AuthServiceStartLoginArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AuthServiceStartLoginArgs(%+v)", *p)
}

var fieldIDToName_AuthServiceStartLoginArgs = map[int16]string{
	1: "req",
}

type AuthServiceStartLoginResult struct {
	Success *StartLoginResp `thrift:"success,0,optional" frugal:"0,optional,StartLoginResp" json:"success,omitempty"`
}

func NewAuthServiceStartLoginResult() *AuthServiceStartLoginResult {
	return &AuthServiceStartLoginResult{}
}

func (p *AuthServiceStartLoginResult) InitDefault() {
}

var AuthServiceStartLoginResult_Success_DEFAULT *StartLoginResp

func (p *AuthServiceStartLoginResult) GetSuccess() (v *StartLoginResp) {
	if !p.IsSetSuccess() {
		return AuthServiceStartLoginResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AuthServiceStartLoginResult) SetSuccess(x interface{}) {
	p.Success = x.(*StartLoginResp)
}

func (p *AuthServiceStartLoginResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AuthServiceStartLoginResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AuthServiceStartLoginResult(%+v)", *p)
}

var fieldIDToName_AuthServiceStartLoginResult = map[int16]string{
	0: "success",
}

type AuthServiceVerifyLoginArgs struct {
	Req *VerifyLoginReq `thrift:"req,1" frugal:"1,default,VerifyLoginReq" json:"req"`
}

func NewAuthServiceVerifyLoginArgs() *AuthServiceVerifyLoginArgs {
	return &AuthServiceVerifyLoginArgs{}
}

func (p *AuthServiceVerifyLoginArgs) InitDefault() {
}

var AuthServiceVerifyLoginArgs_Req_DEFAULT *VerifyLoginReq

func (p *AuthServiceVerifyLoginArgs) GetReq() (v *VerifyLoginReq) {
	if !p.IsSetReq() {
		return AuthServiceVerifyLoginArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AuthServiceVerifyLoginArgs) SetReq(val *VerifyLoginReq) {
	p.Req = val
}

func (p *AuthServiceVerifyLoginArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AuthServiceVerifyLoginArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AuthServiceVerifyLoginArgs(%+v)", *p)
}

var fieldIDToName_AuthServiceVerifyLoginArgs = map[int16]string{
	1: "req",
}

type AuthServiceVerifyLoginResult struct {
	Success *VerifyLoginResp `thrift:"success,0,optional" frugal:"0,optional,VerifyLoginResp" json:"success,omitempty"`
}

func NewAuthServiceVerifyLoginResult() *AuthServiceVerifyLoginResult {
	return &AuthServiceVerifyLoginResult{}
}

func (p *AuthServiceVerifyLoginResult) InitDefault() {
}

var AuthServiceVerifyLoginResult_Success_DEFAULT *VerifyLoginResp

func (p *AuthServiceVerifyLoginResult) GetSuccess() (v *VerifyLoginResp) {
	if !p.IsSetSuccess() {
		return AuthServiceVerifyLoginResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AuthServiceVerifyLoginResult) SetSuccess(x interface{}) {
	p.Success = x.(*VerifyLoginResp)
}

func (p *AuthServiceVerifyLoginResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AuthServiceVerifyLoginResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AuthServiceVerifyLoginResult(%+v)", *p)
}

var fieldIDToName_AuthServiceVerifyLoginResult = map[int16]string{
	0: "success",
}

type AuthServiceValidateSessionArgs struct {
	Req *ValidateSessionReq `thrift:"req,1" frugal:"1,default,ValidateSessionReq" json:"req"`
}

func NewAuthServiceValidateSessionArgs() *AuthServiceValidateSessionArgs {
	return &AuthServiceValidateSessionArgs{}
}

func (p *AuthServiceValidateSessionArgs) InitDefault() {
}

var AuthServiceValidateSessionArgs_Req_DEFAULT *ValidateSessionReq

func (p *AuthServiceValidateSessionArgs) GetReq() (v *ValidateSessionReq) {
	if !p.IsSetReq() {
		return AuthServiceValidateSessionArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AuthServiceValidateSessionArgs) SetReq(val *ValidateSessionReq) {
	p.Req = val
}

func (p *AuthServiceValidateSessionArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AuthServiceValidateSessionArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AuthServiceValidateSessionArgs(%+v)", *p)
}

var fieldIDToName_AuthServiceValidateSessionArgs = map[int16]string{
	1: "req",
}

type AuthServiceValidateSessionResult struct {
	Success *ValidateSessionResp `thrift:"success,0,optional" frugal:"0,optional,ValidateSessionResp" json:"success,omitempty"`
}

func NewAuthServiceValidateSessionResult() *AuthServiceValidateSessionResult {
	return &AuthServiceValidateSessionResult{}
}

func (p *AuthServiceValidateSessionResult) InitDefault() {
}

var AuthServiceValidateSessionResult_Success_DEFAULT *ValidateSessionResp

func (p *AuthServiceValidateSessionResult) GetSuccess() (v *ValidateSessionResp) {
	if !p.IsSetSuccess() {
		return AuthServiceValidateSessionResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AuthServiceValidateSessionResult) SetSuccess(x interface{}) {
	p.Success = x.(*ValidateSessionResp)
}

func (p *AuthServiceValidateSessionResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AuthServiceValidateSessionResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AuthServiceValidateSessionResult(%+v)", *p)
}

var fieldIDToName_AuthServiceValidateSessionResult = map[int16]string{
	0: "success",
}

type AuthServiceLogoutArgs struct {
	Req *LogoutReq `thrift:"req,1" frugal:"1,default,LogoutReq" json:"req"`
}

func NewAuthServiceLogoutArgs() *AuthServiceLogoutArgs {
	return &AuthServiceLogoutArgs{}
}

func (p *AuthServiceLogoutArgs) InitDefault() {
}

var AuthServiceLogoutArgs_Req_DEFAULT *LogoutReq

func (p *AuthServiceLogoutArgs) GetReq() (v *LogoutReq) {
	if !p.IsSetReq() {
		return AuthServiceLogoutArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *AuthServiceLogoutArgs) SetReq(val *LogoutReq) {
	p.Req = val
}

func (p *AuthServiceLogoutArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *AuthServiceLogoutArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AuthServiceLogoutArgs(%+v)", *p)
}

var fieldIDToName_AuthServiceLogoutArgs = map[int16]string{
	1: "req",
}

type AuthServiceLogoutResult struct {
	Success *LogoutResp `thrift:"success,0,optional" frugal:"0,optional,LogoutResp" json:"success,omitempty"`
}

func NewAuthServiceLogoutResult() *AuthServiceLogoutResult {
	return &AuthServiceLogoutResult{}
}

func (p *AuthServiceLogoutResult) InitDefault() {
}

var AuthServiceLogoutResult_Success_DEFAULT *LogoutResp

func (p *AuthServiceLogoutResult) GetSuccess() (v *LogoutResp) {
	if !p.IsSetSuccess() {
		return AuthServiceLogoutResult_Success_DEFAULT
	}
	return p.Success
}
func (p *AuthServiceLogoutResult) SetSuccess(x interface{}) {
	p.Success = x.(*LogoutResp)
}

func (p *AuthServiceLogoutResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *AuthServiceLogoutResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AuthServiceLogoutResult(%+v)", *p)
}

var fieldIDToName_AuthServiceLogoutResult = map[int16]string{
	0: "success",
}
